// AUTO-GENERATED by scripts/generate.ts from .generated-specs (modal_proto → smithy). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as T from "../traits.ts";
import {
  ModalProtocol,
  type ModalOpError,
  type ModalOpContext,
} from "../protocol.ts";
import { UnknownModalError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { ModalOpError, ModalOpContext };

export type FileDescriptor =
  | "FILE_DESCRIPTOR_UNSPECIFIED"
  | "FILE_DESCRIPTOR_STDOUT"
  | "FILE_DESCRIPTOR_STDERR"
  | "FILE_DESCRIPTOR_INFO";
export const FileDescriptor = S.String;

export interface AppCountLogsRequest {
  appId?: string;
  taskId?: string;
  functionId?: string;
  functionCallId?: string;
  sandboxId?: string;
  searchText?: string;
  since?: string;
  until?: string;
  bucketSecs?: number;
  source?: FileDescriptor | (string & {});
  /** Restrict logs to this exact Function ID, including when it is the base Function. */
  parametrizedFunctionId?: string;
}
export const AppCountLogsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    taskId: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    functionId: S.optional(S.String.pipe(T.ProtoField({ n: 3, t: "string" }))),
    functionCallId: S.optional(
      S.String.pipe(T.ProtoField({ n: 4, t: "string" })),
    ),
    sandboxId: S.optional(S.String.pipe(T.ProtoField({ n: 5, t: "string" }))),
    searchText: S.optional(S.String.pipe(T.ProtoField({ n: 6, t: "string" }))),
    since: S.optional(
      S.String.pipe(T.ProtoField({ n: 7, t: "wkt", w: "Timestamp" })),
    ),
    until: S.optional(
      S.String.pipe(T.ProtoField({ n: 8, t: "wkt", w: "Timestamp" })),
    ),
    bucketSecs: S.optional(S.Number.pipe(T.ProtoField({ n: 9, t: "uint32" }))),
    source: S.optional(
      FileDescriptor.pipe(
        T.ProtoField({
          n: 10,
          t: "enum",
          e: {
            FILE_DESCRIPTOR_UNSPECIFIED: 0,
            FILE_DESCRIPTOR_STDOUT: 1,
            FILE_DESCRIPTOR_STDERR: 2,
            FILE_DESCRIPTOR_INFO: 3,
          },
        }),
      ),
    ),
    parametrizedFunctionId: S.optional(
      S.String.pipe(T.ProtoField({ n: 11, t: "string" })),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/AppCountLogs",
      code: 200,
    }),
  ),
).annotate({
  identifier: "AppCountLogsRequest",
}) as any as S.Schema<AppCountLogsRequest>;

export interface AppCountLogsResponseLogBucket {
  bucketStartAt?: string;
  stdoutLogs?: string;
  stderrLogs?: string;
  systemLogs?: string;
}
export const AppCountLogsResponseLogBucket = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    bucketStartAt: S.optional(
      S.String.pipe(T.ProtoField({ n: 1, t: "wkt", w: "Timestamp" })),
    ),
    stdoutLogs: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "uint64" }))),
    stderrLogs: S.optional(S.String.pipe(T.ProtoField({ n: 3, t: "uint64" }))),
    systemLogs: S.optional(S.String.pipe(T.ProtoField({ n: 4, t: "uint64" }))),
  }),
).annotate({
  identifier: "AppCountLogsResponseLogBucket",
}) as any as S.Schema<AppCountLogsResponseLogBucket>;

export type AppCountLogsResponseLogBucketList =
  Array<AppCountLogsResponseLogBucket>;
export const AppCountLogsResponseLogBucketList = /*@__PURE__*/ S.Array(
  AppCountLogsResponseLogBucket,
) as any as S.Schema<AppCountLogsResponseLogBucketList>;

export interface AppCountLogsResponse {
  appId?: string;
  buckets?: AppCountLogsResponseLogBucketList;
}
export const AppCountLogsResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    buckets: S.optional(
      AppCountLogsResponseLogBucketList.pipe(
        T.ProtoField({ n: 2, t: "message", rep: true }),
      ),
    ),
  }),
).annotate({
  identifier: "AppCountLogsResponse",
}) as any as S.Schema<AppCountLogsResponse>;

export interface AppDeploymentHistoryRequest {
  appId?: string;
}
export const AppDeploymentHistoryRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/AppDeploymentHistory",
      code: 200,
    }),
  ),
).annotate({
  identifier: "AppDeploymentHistoryRequest",
}) as any as S.Schema<AppDeploymentHistoryRequest>;

export interface CommitInfo {
  vcs?: string;
  /** Only git is supported for now */
  branch?: string;
  commitHash?: string;
  commitTimestamp?: string;
  dirty?: boolean;
  authorName?: string;
  authorEmail?: string;
  repoUrl?: string;
}
export const CommitInfo = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    vcs: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    branch: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    commitHash: S.optional(S.String.pipe(T.ProtoField({ n: 3, t: "string" }))),
    commitTimestamp: S.optional(
      S.String.pipe(T.ProtoField({ n: 4, t: "int64" })),
    ),
    dirty: S.optional(S.Boolean.pipe(T.ProtoField({ n: 5, t: "bool" }))),
    authorName: S.optional(S.String.pipe(T.ProtoField({ n: 6, t: "string" }))),
    authorEmail: S.optional(S.String.pipe(T.ProtoField({ n: 7, t: "string" }))),
    repoUrl: S.optional(S.String.pipe(T.ProtoField({ n: 8, t: "string" }))),
  }),
).annotate({ identifier: "CommitInfo" }) as any as S.Schema<CommitInfo>;

export type DeploymentType =
  | "DEPLOYMENT_TYPE_UNSPECIFIED"
  | "DEPLOYMENT_TYPE_STANDARD"
  | "DEPLOYMENT_TYPE_ROLLBACK"
  | "DEPLOYMENT_TYPE_ROLLOVER"
  | "DEPLOYMENT_TYPE_PROMOTION"
  | "DEPLOYMENT_TYPE_STAGED";
export const DeploymentType = S.String;

export interface AppDeploymentHistory2 {
  appId?: string;
  version?: number;
  clientVersion?: string;
  deployedAt?: number;
  deployedBy?: string;
  deployedByAvatarUrl?: string;
  tag?: string;
  rollbackVersion?: number;
  rollbackAllowed?: boolean;
  commitInfo?: CommitInfo;
  deploymentType?: DeploymentType;
}
export const AppDeploymentHistory2 = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    version: S.optional(S.Number.pipe(T.ProtoField({ n: 2, t: "uint32" }))),
    clientVersion: S.optional(
      S.String.pipe(T.ProtoField({ n: 3, t: "string" })),
    ),
    deployedAt: S.optional(S.Number.pipe(T.ProtoField({ n: 4, t: "double" }))),
    deployedBy: S.optional(S.String.pipe(T.ProtoField({ n: 5, t: "string" }))),
    deployedByAvatarUrl: S.optional(
      S.String.pipe(T.ProtoField({ n: 9, t: "string" })),
    ),
    tag: S.optional(S.String.pipe(T.ProtoField({ n: 6, t: "string" }))),
    rollbackVersion: S.optional(
      S.Number.pipe(T.ProtoField({ n: 7, t: "uint32" })),
    ),
    rollbackAllowed: S.optional(
      S.Boolean.pipe(T.ProtoField({ n: 8, t: "bool" })),
    ),
    commitInfo: S.optional(
      CommitInfo.pipe(T.ProtoField({ n: 10, t: "message" })),
    ),
    deploymentType: S.optional(
      DeploymentType.pipe(
        T.ProtoField({
          n: 11,
          t: "enum",
          e: {
            DEPLOYMENT_TYPE_UNSPECIFIED: 0,
            DEPLOYMENT_TYPE_STANDARD: 1,
            DEPLOYMENT_TYPE_ROLLBACK: 2,
            DEPLOYMENT_TYPE_ROLLOVER: 3,
            DEPLOYMENT_TYPE_PROMOTION: 4,
            DEPLOYMENT_TYPE_STAGED: 5,
          },
        }),
      ),
    ),
  }),
).annotate({
  identifier: "AppDeploymentHistory2",
}) as any as S.Schema<AppDeploymentHistory2>;

export type AppDeploymentHistory2List = Array<AppDeploymentHistory2>;
export const AppDeploymentHistory2List = /*@__PURE__*/ S.Array(
  AppDeploymentHistory2,
) as any as S.Schema<AppDeploymentHistory2List>;

export interface AppDeploymentHistoryResponse {
  appDeploymentHistories?: AppDeploymentHistory2List;
  productionAppVersion?: number;
}
export const AppDeploymentHistoryResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appDeploymentHistories: S.optional(
      AppDeploymentHistory2List.pipe(
        T.ProtoField({ n: 1, t: "message", rep: true }),
      ),
    ),
    productionAppVersion: S.optional(
      S.Number.pipe(T.ProtoField({ n: 2, t: "uint32" })),
    ),
  }),
).annotate({
  identifier: "AppDeploymentHistoryResponse",
}) as any as S.Schema<AppDeploymentHistoryResponse>;

export interface AppFetchLogsRequest {
  appId?: string;
  since?: string;
  until?: string;
  limit?: number;
  source?: FileDescriptor | (string & {});
  functionId?: string;
  functionCallId?: string;
  taskId?: string;
  sandboxId?: string;
  searchText?: string;
  /** Restrict logs to this exact Function ID, including when it is the base Function. */
  parametrizedFunctionId?: string;
}
export const AppFetchLogsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    since: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "wkt", w: "Timestamp" })),
    ),
    until: S.optional(
      S.String.pipe(T.ProtoField({ n: 3, t: "wkt", w: "Timestamp" })),
    ),
    limit: S.optional(S.Number.pipe(T.ProtoField({ n: 4, t: "uint32" }))),
    source: S.optional(
      FileDescriptor.pipe(
        T.ProtoField({
          n: 5,
          t: "enum",
          e: {
            FILE_DESCRIPTOR_UNSPECIFIED: 0,
            FILE_DESCRIPTOR_STDOUT: 1,
            FILE_DESCRIPTOR_STDERR: 2,
            FILE_DESCRIPTOR_INFO: 3,
          },
        }),
      ),
    ),
    functionId: S.optional(S.String.pipe(T.ProtoField({ n: 6, t: "string" }))),
    functionCallId: S.optional(
      S.String.pipe(T.ProtoField({ n: 7, t: "string" })),
    ),
    taskId: S.optional(S.String.pipe(T.ProtoField({ n: 8, t: "string" }))),
    sandboxId: S.optional(S.String.pipe(T.ProtoField({ n: 9, t: "string" }))),
    searchText: S.optional(S.String.pipe(T.ProtoField({ n: 10, t: "string" }))),
    parametrizedFunctionId: S.optional(
      S.String.pipe(T.ProtoField({ n: 11, t: "string" })),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/AppFetchLogs",
      code: 200,
    }),
  ),
).annotate({
  identifier: "AppFetchLogsRequest",
}) as any as S.Schema<AppFetchLogsRequest>;

export type TaskState =
  | "TASK_STATE_UNSPECIFIED"
  | "TASK_STATE_CREATED"
  | "TASK_STATE_QUEUED"
  | "TASK_STATE_WORKER_ASSIGNED"
  | "TASK_STATE_LOADING_IMAGE"
  | "TASK_STATE_ACTIVE"
  | "TASK_STATE_COMPLETED"
  | "TASK_STATE_CREATING_CONTAINER"
  | "TASK_STATE_IDLE"
  | "TASK_STATE_PREEMPTIBLE"
  | "TASK_STATE_PREEMPTED"
  | "TASK_STATE_LOADING_CHECKPOINT_IMAGE";
export const TaskState = S.String;

export type ProgressType = "IMAGE_SNAPSHOT_UPLOAD" | "FUNCTION_QUEUED";
export const ProgressType = S.String;

export interface TaskProgress {
  len?: string;
  pos?: string;
  progressType?: ProgressType;
  description?: string;
}
export const TaskProgress = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    len: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "uint64" }))),
    pos: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "uint64" }))),
    progressType: S.optional(
      ProgressType.pipe(
        T.ProtoField({
          n: 3,
          t: "enum",
          e: { IMAGE_SNAPSHOT_UPLOAD: 0, FUNCTION_QUEUED: 1 },
        }),
      ),
    ),
    description: S.optional(S.String.pipe(T.ProtoField({ n: 4, t: "string" }))),
  }),
).annotate({ identifier: "TaskProgress" }) as any as S.Schema<TaskProgress>;

export interface TaskLogs {
  data?: string;
  taskState?: TaskState;
  timestamp?: number;
  fileDescriptor?: FileDescriptor;
  taskProgress?: TaskProgress;
  functionCallId?: string;
  inputId?: string;
  timestampNs?: string;
  containerId?: string;
  containerName?: string;
}
export const TaskLogs = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    data: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    taskState: S.optional(
      TaskState.pipe(
        T.ProtoField({
          n: 6,
          t: "enum",
          e: {
            TASK_STATE_UNSPECIFIED: 0,
            TASK_STATE_CREATED: 6,
            TASK_STATE_QUEUED: 1,
            TASK_STATE_WORKER_ASSIGNED: 2,
            TASK_STATE_LOADING_IMAGE: 3,
            TASK_STATE_ACTIVE: 4,
            TASK_STATE_COMPLETED: 5,
            TASK_STATE_CREATING_CONTAINER: 7,
            TASK_STATE_IDLE: 8,
            TASK_STATE_PREEMPTIBLE: 9,
            TASK_STATE_PREEMPTED: 10,
            TASK_STATE_LOADING_CHECKPOINT_IMAGE: 11,
          },
        }),
      ),
    ),
    timestamp: S.optional(S.Number.pipe(T.ProtoField({ n: 7, t: "double" }))),
    fileDescriptor: S.optional(
      FileDescriptor.pipe(
        T.ProtoField({
          n: 8,
          t: "enum",
          e: {
            FILE_DESCRIPTOR_UNSPECIFIED: 0,
            FILE_DESCRIPTOR_STDOUT: 1,
            FILE_DESCRIPTOR_STDERR: 2,
            FILE_DESCRIPTOR_INFO: 3,
          },
        }),
      ),
    ),
    taskProgress: S.optional(
      TaskProgress.pipe(T.ProtoField({ n: 9, t: "message" })),
    ),
    functionCallId: S.optional(
      S.String.pipe(T.ProtoField({ n: 10, t: "string" })),
    ),
    inputId: S.optional(S.String.pipe(T.ProtoField({ n: 11, t: "string" }))),
    timestampNs: S.optional(
      S.String.pipe(T.ProtoField({ n: 12, t: "uint64" })),
    ),
    containerId: S.optional(
      S.String.pipe(T.ProtoField({ n: 13, t: "string" })),
    ),
    containerName: S.optional(
      S.String.pipe(T.ProtoField({ n: 14, t: "string" })),
    ),
  }),
).annotate({ identifier: "TaskLogs" }) as any as S.Schema<TaskLogs>;

export type TaskLogsList = Array<TaskLogs>;
export const TaskLogsList = /*@__PURE__*/ S.Array(
  TaskLogs,
) as any as S.Schema<TaskLogsList>;

export interface TaskLogsBatch {
  taskId?: string;
  items?: TaskLogsList;
  entryId?: string;
  appDone?: boolean;
  functionId?: string;
  inputId?: string;
  imageId?: string;
  /** Used for image logs */
  eof?: boolean;
  ptyExecId?: string;
  /** Used for interactive functions */
  rootFunctionId?: string;
  ttlDays?: number;
}
export const TaskLogsBatch = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    taskId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    items: S.optional(
      TaskLogsList.pipe(T.ProtoField({ n: 2, t: "message", rep: true })),
    ),
    entryId: S.optional(S.String.pipe(T.ProtoField({ n: 5, t: "string" }))),
    appDone: S.optional(S.Boolean.pipe(T.ProtoField({ n: 10, t: "bool" }))),
    functionId: S.optional(S.String.pipe(T.ProtoField({ n: 11, t: "string" }))),
    inputId: S.optional(S.String.pipe(T.ProtoField({ n: 12, t: "string" }))),
    imageId: S.optional(S.String.pipe(T.ProtoField({ n: 13, t: "string" }))),
    eof: S.optional(S.Boolean.pipe(T.ProtoField({ n: 14, t: "bool" }))),
    ptyExecId: S.optional(S.String.pipe(T.ProtoField({ n: 15, t: "string" }))),
    rootFunctionId: S.optional(
      S.String.pipe(T.ProtoField({ n: 16, t: "string" })),
    ),
    ttlDays: S.optional(S.Number.pipe(T.ProtoField({ n: 17, t: "uint32" }))),
  }),
).annotate({ identifier: "TaskLogsBatch" }) as any as S.Schema<TaskLogsBatch>;

export type TaskLogsBatchList = Array<TaskLogsBatch>;
export const TaskLogsBatchList = /*@__PURE__*/ S.Array(
  TaskLogsBatch,
) as any as S.Schema<TaskLogsBatchList>;

export interface AppFetchLogsResponse {
  batches?: TaskLogsBatchList;
}
export const AppFetchLogsResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    batches: S.optional(
      TaskLogsBatchList.pipe(T.ProtoField({ n: 1, t: "message", rep: true })),
    ),
  }),
).annotate({
  identifier: "AppFetchLogsResponse",
}) as any as S.Schema<AppFetchLogsResponse>;

export interface AppGetByDeploymentNameRequest {
  /** removed namespace */
  name?: string;
  environmentName?: string;
}
export const AppGetByDeploymentNameRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    environmentName: S.optional(
      S.String.pipe(T.ProtoField({ n: 4, t: "string" })),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/AppGetByDeploymentName",
      code: 200,
    }),
  ),
).annotate({
  identifier: "AppGetByDeploymentNameRequest",
}) as any as S.Schema<AppGetByDeploymentNameRequest>;

/** NOTE: make sure to update the frontend if we add a new state here https://github.com/modal-labs/modal/blob/main/frontend/src/routes/(dashboard)/%5B%5Bworkspace%5D%5D/apps/+page.svelte#L95 */
export type AppState =
  | "APP_STATE_UNSPECIFIED"
  | "APP_STATE_EPHEMERAL"
  | "APP_STATE_DETACHED"
  | "APP_STATE_DEPLOYED"
  | "APP_STATE_STOPPING"
  | "APP_STATE_STOPPED"
  | "APP_STATE_INITIALIZING"
  | "APP_STATE_DISABLED"
  | "APP_STATE_DETACHED_DISCONNECTED"
  | "APP_STATE_DERIVED";
export const AppState = S.String;

/** tag -> class id */
export interface AppLifecycle {
  appState?: AppState;
  createdAt?: number;
  createdBy?: string;
  /** User or service user name */
  deployedAt?: number;
  /** Most recent deployment event */
  deployedBy?: string;
  /** User or service user name */
  version?: number;
  /** Only meaningful when App is deployed */
  stoppedAt?: number;
  /** Unset when App is still running */
  stoppedBy?: string;
}
export const AppLifecycle = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appState: S.optional(
      AppState.pipe(
        T.ProtoField({
          n: 1,
          t: "enum",
          e: {
            APP_STATE_UNSPECIFIED: 0,
            APP_STATE_EPHEMERAL: 1,
            APP_STATE_DETACHED: 2,
            APP_STATE_DEPLOYED: 3,
            APP_STATE_STOPPING: 4,
            APP_STATE_STOPPED: 5,
            APP_STATE_INITIALIZING: 6,
            APP_STATE_DISABLED: 7,
            APP_STATE_DETACHED_DISCONNECTED: 8,
            APP_STATE_DERIVED: 9,
          },
        }),
      ),
    ),
    createdAt: S.optional(S.Number.pipe(T.ProtoField({ n: 2, t: "double" }))),
    createdBy: S.optional(S.String.pipe(T.ProtoField({ n: 3, t: "string" }))),
    deployedAt: S.optional(S.Number.pipe(T.ProtoField({ n: 4, t: "double" }))),
    deployedBy: S.optional(S.String.pipe(T.ProtoField({ n: 5, t: "string" }))),
    version: S.optional(S.Number.pipe(T.ProtoField({ n: 6, t: "int32" }))),
    stoppedAt: S.optional(S.Number.pipe(T.ProtoField({ n: 7, t: "double" }))),
    stoppedBy: S.optional(S.String.pipe(T.ProtoField({ n: 8, t: "string" }))),
  }),
).annotate({ identifier: "AppLifecycle" }) as any as S.Schema<AppLifecycle>;

export interface AppGetByDeploymentNameResponse {
  appId?: string;
  /** Null when App with requested name is not deployed */
  previousAppId?: string;
  /** Populated if App with requested name was recently stopped */
  environmentName?: string;
  /** Populated because server may resolve default environment */
  lifecycle?: AppLifecycle;
}
export const AppGetByDeploymentNameResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    previousAppId: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "string" })),
    ),
    environmentName: S.optional(
      S.String.pipe(T.ProtoField({ n: 3, t: "string" })),
    ),
    lifecycle: S.optional(
      AppLifecycle.pipe(T.ProtoField({ n: 4, t: "message" })),
    ),
  }),
).annotate({
  identifier: "AppGetByDeploymentNameResponse",
}) as any as S.Schema<AppGetByDeploymentNameResponse>;

export interface AppGetInfoRequest {
  appId?: string;
}
export const AppGetInfoRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/AppGetInfo",
      code: 200,
    }),
  ),
).annotate({
  identifier: "AppGetInfoRequest",
}) as any as S.Schema<AppGetInfoRequest>;

export type StringMap = { [key: string]: string | undefined };
export const StringMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<StringMap>;

export interface AppHandleMetadata {
  description?: string;
  appId?: string;
  environmentName?: string;
  lifecycle?: AppLifecycle;
  functions?: StringMap;
  /** tag -> function id */
  servers?: StringMap;
}
export const AppHandleMetadata = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    description: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    environmentName: S.optional(
      S.String.pipe(T.ProtoField({ n: 3, t: "string" })),
    ),
    lifecycle: S.optional(
      AppLifecycle.pipe(T.ProtoField({ n: 4, t: "message" })),
    ),
    functions: S.optional(
      StringMap.pipe(
        T.ProtoField({ n: 5, t: "map", k: "string", v: { t: "string" } }),
      ),
    ),
    servers: S.optional(
      StringMap.pipe(
        T.ProtoField({ n: 6, t: "map", k: "string", v: { t: "string" } }),
      ),
    ),
  }),
).annotate({
  identifier: "AppHandleMetadata",
}) as any as S.Schema<AppHandleMetadata>;

export interface AppGetInfoResponse {
  info?: AppHandleMetadata;
}
export const AppGetInfoResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    info: S.optional(
      AppHandleMetadata.pipe(T.ProtoField({ n: 1, t: "message" })),
    ),
  }),
).annotate({
  identifier: "AppGetInfoResponse",
}) as any as S.Schema<AppGetInfoResponse>;

export interface AppGetLayoutRequest {
  appId?: string;
}
export const AppGetLayoutRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/AppGetLayout",
      code: 200,
    }),
  ),
).annotate({
  identifier: "AppGetLayoutRequest",
}) as any as S.Schema<AppGetLayoutRequest>;

export type FunctionFunctionType =
  | "FUNCTION_TYPE_UNSPECIFIED"
  | "FUNCTION_TYPE_GENERATOR"
  | "FUNCTION_TYPE_FUNCTION";
export const FunctionFunctionType = S.String;

export type ClassParameterInfoParameterSerializationFormat =
  | "PARAM_SERIALIZATION_FORMAT_UNSPECIFIED"
  | "PARAM_SERIALIZATION_FORMAT_PICKLE"
  | "PARAM_SERIALIZATION_FORMAT_PROTO";
export const ClassParameterInfoParameterSerializationFormat = S.String;

export type ParameterType =
  | "PARAM_TYPE_UNSPECIFIED"
  | "PARAM_TYPE_STRING"
  | "PARAM_TYPE_INT"
  | "PARAM_TYPE_PICKLE"
  | "PARAM_TYPE_BYTES"
  | "PARAM_TYPE_UNKNOWN"
  | "PARAM_TYPE_LIST"
  | "PARAM_TYPE_DICT"
  | "PARAM_TYPE_NONE"
  | "PARAM_TYPE_BOOL";
export const ParameterType = S.String;

export type GenericPayloadTypeList = Array<GenericPayloadType>;
export const GenericPayloadTypeList = /*@__PURE__*/ S.Array(
  S.suspend(() => GenericPayloadType),
) as any as S.Schema<GenericPayloadTypeList>;

export interface GenericPayloadType {
  baseType?: ParameterType;
  subTypes?: GenericPayloadTypeList;
}
export const GenericPayloadType = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    baseType: S.optional(
      ParameterType.pipe(
        T.ProtoField({
          n: 1,
          t: "enum",
          e: {
            PARAM_TYPE_UNSPECIFIED: 0,
            PARAM_TYPE_STRING: 1,
            PARAM_TYPE_INT: 2,
            PARAM_TYPE_PICKLE: 3,
            PARAM_TYPE_BYTES: 4,
            PARAM_TYPE_UNKNOWN: 5,
            PARAM_TYPE_LIST: 6,
            PARAM_TYPE_DICT: 7,
            PARAM_TYPE_NONE: 8,
            PARAM_TYPE_BOOL: 9,
          },
        }),
      ),
    ),
    subTypes: S.optional(
      GenericPayloadTypeList.pipe(
        T.ProtoField({ n: 2, t: "message", rep: true }),
      ),
    ),
  }),
).annotate({
  identifier: "GenericPayloadType",
}) as any as S.Schema<GenericPayloadType>;

export interface ClassParameterSpec {
  /** TODO: rename into NamedPayloadType or similar */
  name?: string;
  type?: ParameterType;
  /** TODO: deprecate - use full_type instead */
  hasDefault?: boolean;
  /** Default *values* are only registered for class parameters */
  stringDefault?: string;
  intDefault?: string;
  pickleDefault?: string;
  bytesDefault?: string;
  boolDefault?: boolean;
  fullType?: GenericPayloadType;
}
export const ClassParameterSpec = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    type: S.optional(
      ParameterType.pipe(
        T.ProtoField({
          n: 2,
          t: "enum",
          e: {
            PARAM_TYPE_UNSPECIFIED: 0,
            PARAM_TYPE_STRING: 1,
            PARAM_TYPE_INT: 2,
            PARAM_TYPE_PICKLE: 3,
            PARAM_TYPE_BYTES: 4,
            PARAM_TYPE_UNKNOWN: 5,
            PARAM_TYPE_LIST: 6,
            PARAM_TYPE_DICT: 7,
            PARAM_TYPE_NONE: 8,
            PARAM_TYPE_BOOL: 9,
          },
        }),
      ),
    ),
    hasDefault: S.optional(S.Boolean.pipe(T.ProtoField({ n: 3, t: "bool" }))),
    stringDefault: S.optional(
      S.String.pipe(T.ProtoField({ n: 4, t: "string" })),
    ),
    intDefault: S.optional(S.String.pipe(T.ProtoField({ n: 5, t: "int64" }))),
    pickleDefault: S.optional(
      S.String.pipe(T.ProtoField({ n: 6, t: "bytes" })),
    ),
    bytesDefault: S.optional(S.String.pipe(T.ProtoField({ n: 7, t: "bytes" }))),
    boolDefault: S.optional(S.Boolean.pipe(T.ProtoField({ n: 9, t: "bool" }))),
    fullType: S.optional(
      GenericPayloadType.pipe(T.ProtoField({ n: 8, t: "message" })),
    ),
  }),
).annotate({
  identifier: "ClassParameterSpec",
}) as any as S.Schema<ClassParameterSpec>;

export type ClassParameterSpecList = Array<ClassParameterSpec>;
export const ClassParameterSpecList = /*@__PURE__*/ S.Array(
  ClassParameterSpec,
) as any as S.Schema<ClassParameterSpecList>;

export interface ClassParameterInfo {
  /** new format using api.FunctionParameterSet */
  format?: ClassParameterInfoParameterSerializationFormat;
  schema?: ClassParameterSpecList;
}
export const ClassParameterInfo = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    format: S.optional(
      ClassParameterInfoParameterSerializationFormat.pipe(
        T.ProtoField({
          n: 1,
          t: "enum",
          e: {
            PARAM_SERIALIZATION_FORMAT_UNSPECIFIED: 0,
            PARAM_SERIALIZATION_FORMAT_PICKLE: 1,
            PARAM_SERIALIZATION_FORMAT_PROTO: 2,
          },
        }),
      ),
    ),
    schema: S.optional(
      ClassParameterSpecList.pipe(
        T.ProtoField({ n: 2, t: "message", rep: true }),
      ),
    ),
  }),
).annotate({
  identifier: "ClassParameterInfo",
}) as any as S.Schema<ClassParameterInfo>;

export type FunctionHandleMetadataMap = {
  [key: string]: FunctionHandleMetadata | undefined;
};
export const FunctionHandleMetadataMap = /*@__PURE__*/ S.Record(
  S.String,
  S.suspend(() => FunctionHandleMetadata),
) as any as S.Schema<FunctionHandleMetadataMap>;

export type FunctionSchemaFunctionSchemaType =
  | "FUNCTION_SCHEMA_UNSPECIFIED"
  | "FUNCTION_SCHEMA_V1";
export const FunctionSchemaFunctionSchemaType = S.String;

export interface FunctionSchema {
  schemaType?: FunctionSchemaFunctionSchemaType;
  /** allows easy disambiguation between empty schema and no schema collection etc. */
  arguments?: ClassParameterSpecList;
  returnType?: GenericPayloadType;
}
export const FunctionSchema = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    schemaType: S.optional(
      FunctionSchemaFunctionSchemaType.pipe(
        T.ProtoField({
          n: 1,
          t: "enum",
          e: { FUNCTION_SCHEMA_UNSPECIFIED: 0, FUNCTION_SCHEMA_V1: 1 },
        }),
      ),
    ),
    arguments: S.optional(
      ClassParameterSpecList.pipe(
        T.ProtoField({ n: 2, t: "message", rep: true }),
      ),
    ),
    returnType: S.optional(
      GenericPayloadType.pipe(T.ProtoField({ n: 3, t: "message" })),
    ),
  }),
).annotate({ identifier: "FunctionSchema" }) as any as S.Schema<FunctionSchema>;

export type StringList = Array<string>;
export const StringList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<StringList>;

/** Which data format a binary message is encoded with. */
export type DataFormat =
  | "DATA_FORMAT_UNSPECIFIED"
  | "DATA_FORMAT_PICKLE"
  | "DATA_FORMAT_ASGI"
  | "DATA_FORMAT_GENERATOR_DONE"
  | "DATA_FORMAT_CBOR";
export const DataFormat = S.String;

export type DataFormatList = Array<DataFormat>;
export const DataFormatList = /*@__PURE__*/ S.Array(
  DataFormat,
) as any as S.Schema<DataFormatList>;

export interface FunctionHandleMetadata {
  /** contains all the info about a function that is needed to trigger the right behaviour when using a FunctionHandler. Notably excludes things purely used for *executing* the function in a container entrypoint Should be a subset and use IDs/types from `Function` above */
  functionName?: string;
  functionType?: FunctionFunctionType;
  webUrl?: string;
  isMethod?: boolean;
  useFunctionId?: string;
  /** used for methods */
  useMethodName?: string;
  /** used for methods */
  definitionId?: string;
  classParameterInfo?: ClassParameterInfo;
  /** Mapping of method names to their metadata, only non-empty for class service functions */
  methodHandleMetadata?: FunctionHandleMetadataMap;
  functionSchema?: FunctionSchema;
  inputPlaneUrl?: string;
  inputPlaneRegion?: string;
  /** Use optional to ensure unset values default to None instead of 0 */
  maxObjectSizeBytes?: string;
  maxAsyncObjectSizeBytes?: string;
  ExperimentalFlashUrls?: StringList;
  /** (Optional) urls for flash services */
  supportedInputFormats?: DataFormatList;
  supportedOutputFormats?: DataFormatList;
  appId?: string;
  /** The base Function ID for a variant, or the Function's own ID otherwise. */
  baseFunctionId?: string;
}
export const FunctionHandleMetadata = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    functionName: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "string" })),
    ),
    functionType: S.optional(
      FunctionFunctionType.pipe(
        T.ProtoField({
          n: 8,
          t: "enum",
          e: {
            FUNCTION_TYPE_UNSPECIFIED: 0,
            FUNCTION_TYPE_GENERATOR: 1,
            FUNCTION_TYPE_FUNCTION: 2,
          },
        }),
      ),
    ),
    webUrl: S.optional(S.String.pipe(T.ProtoField({ n: 28, t: "string" }))),
    isMethod: S.optional(S.Boolean.pipe(T.ProtoField({ n: 39, t: "bool" }))),
    useFunctionId: S.optional(
      S.String.pipe(T.ProtoField({ n: 40, t: "string" })),
    ),
    useMethodName: S.optional(
      S.String.pipe(T.ProtoField({ n: 41, t: "string" })),
    ),
    definitionId: S.optional(
      S.String.pipe(T.ProtoField({ n: 42, t: "string" })),
    ),
    classParameterInfo: S.optional(
      ClassParameterInfo.pipe(T.ProtoField({ n: 43, t: "message" })),
    ),
    methodHandleMetadata: S.optional(
      FunctionHandleMetadataMap.pipe(
        T.ProtoField({ n: 44, t: "map", k: "string", v: { t: "message" } }),
      ),
    ),
    functionSchema: S.optional(
      FunctionSchema.pipe(T.ProtoField({ n: 45, t: "message" })),
    ),
    inputPlaneUrl: S.optional(
      S.String.pipe(T.ProtoField({ n: 46, t: "string" })),
    ),
    inputPlaneRegion: S.optional(
      S.String.pipe(T.ProtoField({ n: 47, t: "string" })),
    ),
    maxObjectSizeBytes: S.optional(
      S.String.pipe(T.ProtoField({ n: 48, t: "uint64" })),
    ),
    maxAsyncObjectSizeBytes: S.optional(
      S.String.pipe(T.ProtoField({ n: 53, t: "uint64" })),
    ),
    ExperimentalFlashUrls: S.optional(
      StringList.pipe(T.ProtoField({ n: 49, t: "string", rep: true })),
    ),
    supportedInputFormats: S.optional(
      DataFormatList.pipe(
        T.ProtoField({
          n: 50,
          t: "enum",
          e: {
            DATA_FORMAT_UNSPECIFIED: 0,
            DATA_FORMAT_PICKLE: 1,
            DATA_FORMAT_ASGI: 2,
            DATA_FORMAT_GENERATOR_DONE: 3,
            DATA_FORMAT_CBOR: 4,
          },
          rep: true,
        }),
      ),
    ),
    supportedOutputFormats: S.optional(
      DataFormatList.pipe(
        T.ProtoField({
          n: 51,
          t: "enum",
          e: {
            DATA_FORMAT_UNSPECIFIED: 0,
            DATA_FORMAT_PICKLE: 1,
            DATA_FORMAT_ASGI: 2,
            DATA_FORMAT_GENERATOR_DONE: 3,
            DATA_FORMAT_CBOR: 4,
          },
          rep: true,
        }),
      ),
    ),
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 52, t: "string" }))),
    baseFunctionId: S.optional(
      S.String.pipe(T.ProtoField({ n: 54, t: "string" })),
    ),
  }),
).annotate({
  identifier: "FunctionHandleMetadata",
}) as any as S.Schema<FunctionHandleMetadata>;

export interface MountHandleMetadata {
  contentChecksumSha256Hex?: string;
}
export const MountHandleMetadata = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    contentChecksumSha256Hex: S.optional(
      S.String.pipe(T.ProtoField({ n: 1, t: "string" })),
    ),
  }),
).annotate({
  identifier: "MountHandleMetadata",
}) as any as S.Schema<MountHandleMetadata>;

export interface ClassMethod {
  functionName?: string;
  functionId?: string;
  /** Class methods need to hydrate all functions on the class */
  functionHandleMetadata?: FunctionHandleMetadata;
}
export const ClassMethod = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    functionName: S.optional(
      S.String.pipe(T.ProtoField({ n: 1, t: "string" })),
    ),
    functionId: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    functionHandleMetadata: S.optional(
      FunctionHandleMetadata.pipe(T.ProtoField({ n: 3, t: "message" })),
    ),
  }),
).annotate({ identifier: "ClassMethod" }) as any as S.Schema<ClassMethod>;

export type ClassMethodList = Array<ClassMethod>;
export const ClassMethodList = /*@__PURE__*/ S.Array(
  ClassMethod,
) as any as S.Schema<ClassMethodList>;

export interface ClassHandleMetadata {
  methods?: ClassMethodList;
  classFunctionId?: string;
  classFunctionMetadata?: FunctionHandleMetadata;
}
export const ClassHandleMetadata = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    methods: S.optional(
      ClassMethodList.pipe(T.ProtoField({ n: 1, t: "message", rep: true })),
    ),
    classFunctionId: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "string" })),
    ),
    classFunctionMetadata: S.optional(
      FunctionHandleMetadata.pipe(T.ProtoField({ n: 3, t: "message" })),
    ),
  }),
).annotate({
  identifier: "ClassHandleMetadata",
}) as any as S.Schema<ClassHandleMetadata>;

/** Used for both tasks and function outputs */
export type GenericResultGenericStatus =
  | "GENERIC_STATUS_UNSPECIFIED"
  | "GENERIC_STATUS_SUCCESS"
  | "GENERIC_STATUS_FAILURE"
  | "GENERIC_STATUS_TERMINATED"
  | "GENERIC_STATUS_TIMEOUT"
  | "GENERIC_STATUS_INIT_FAILURE"
  | "GENERIC_STATUS_INTERNAL_FAILURE"
  | "GENERIC_STATUS_IDLE_TIMEOUT"
  | "GENERIC_STATUS_MEMORY_MANAGER_EVICTION";
export const GenericResultGenericStatus = S.String;

/** sub-type for generic types like lists */
export interface GenericResult {
  status?: GenericResultGenericStatus;
  /** Status of the task or function output. */
  exception?: string;
  /** Exception message for failures, if available. */
  exitcode?: number;
  /** Status code of the container entrypoint or builder process if it terminates unexpectedly. */
  traceback?: string;
  /** String value of the Python traceback. */
  serializedTb?: string;
  /** Pickled traceback object. */
  tbLineCache?: string;
  /** Pickled line cache for traceback object. */
  data?: string;
  /** Inline data of the result. */
  dataBlobId?: string;
  /** Blob ID for large data. */
  propagationReason?: string;
}
export const GenericResult = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    status: S.optional(
      GenericResultGenericStatus.pipe(
        T.ProtoField({
          n: 1,
          t: "enum",
          e: {
            GENERIC_STATUS_UNSPECIFIED: 0,
            GENERIC_STATUS_SUCCESS: 1,
            GENERIC_STATUS_FAILURE: 2,
            GENERIC_STATUS_TERMINATED: 3,
            GENERIC_STATUS_TIMEOUT: 4,
            GENERIC_STATUS_INIT_FAILURE: 5,
            GENERIC_STATUS_INTERNAL_FAILURE: 6,
            GENERIC_STATUS_IDLE_TIMEOUT: 7,
            GENERIC_STATUS_MEMORY_MANAGER_EVICTION: 8,
          },
        }),
      ),
    ),
    exception: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    exitcode: S.optional(S.Number.pipe(T.ProtoField({ n: 3, t: "int32" }))),
    traceback: S.optional(S.String.pipe(T.ProtoField({ n: 4, t: "string" }))),
    serializedTb: S.optional(
      S.String.pipe(T.ProtoField({ n: 11, t: "bytes" })),
    ),
    tbLineCache: S.optional(S.String.pipe(T.ProtoField({ n: 12, t: "bytes" }))),
    data: S.optional(S.String.pipe(T.ProtoField({ n: 5, t: "bytes" }))),
    dataBlobId: S.optional(S.String.pipe(T.ProtoField({ n: 10, t: "string" }))),
    propagationReason: S.optional(
      S.String.pipe(T.ProtoField({ n: 13, t: "string" })),
    ),
  }),
).annotate({ identifier: "GenericResult" }) as any as S.Schema<GenericResult>;

export interface SandboxHandleMetadata {
  result?: GenericResult;
  appId?: string;
}
export const SandboxHandleMetadata = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    result: S.optional(
      GenericResult.pipe(T.ProtoField({ n: 1, t: "message" })),
    ),
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
  }),
).annotate({
  identifier: "SandboxHandleMetadata",
}) as any as S.Schema<SandboxHandleMetadata>;

/** HTTP/2 tunnel */
export type VolumeFsVersion =
  | "VOLUME_FS_VERSION_UNSPECIFIED"
  | "VOLUME_FS_VERSION_V1"
  | "VOLUME_FS_VERSION_V2";
export const VolumeFsVersion = S.String;

export interface CreationInfo {
  /** This message is used in metadata for resource objects like Dict, Queue, Volume, etc. */
  createdAt?: number;
  /** Timestamp of resource creation */
  createdBy?: string;
}
export const CreationInfo = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    createdAt: S.optional(S.Number.pipe(T.ProtoField({ n: 1, t: "double" }))),
    createdBy: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
  }),
).annotate({ identifier: "CreationInfo" }) as any as S.Schema<CreationInfo>;

export interface VolumeMetadata {
  version?: VolumeFsVersion;
  name?: string;
  creationInfo?: CreationInfo;
}
export const VolumeMetadata = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    version: S.optional(
      VolumeFsVersion.pipe(
        T.ProtoField({
          n: 1,
          t: "enum",
          e: {
            VOLUME_FS_VERSION_UNSPECIFIED: 0,
            VOLUME_FS_VERSION_V1: 1,
            VOLUME_FS_VERSION_V2: 2,
          },
        }),
      ),
    ),
    name: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    creationInfo: S.optional(
      CreationInfo.pipe(T.ProtoField({ n: 3, t: "message" })),
    ),
  }),
).annotate({ identifier: "VolumeMetadata" }) as any as S.Schema<VolumeMetadata>;

export interface Object {
  objectId?: string;
  functionHandleMetadata?: FunctionHandleMetadata;
  mountHandleMetadata?: MountHandleMetadata;
  classHandleMetadata?: ClassHandleMetadata;
  sandboxHandleMetadata?: SandboxHandleMetadata;
  volumeMetadata?: VolumeMetadata;
}
export const Object = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    objectId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    functionHandleMetadata: S.optional(
      FunctionHandleMetadata.pipe(T.ProtoField({ n: 3, t: "message" })),
    ),
    mountHandleMetadata: S.optional(
      MountHandleMetadata.pipe(T.ProtoField({ n: 4, t: "message" })),
    ),
    classHandleMetadata: S.optional(
      ClassHandleMetadata.pipe(T.ProtoField({ n: 5, t: "message" })),
    ),
    sandboxHandleMetadata: S.optional(
      SandboxHandleMetadata.pipe(T.ProtoField({ n: 6, t: "message" })),
    ),
    volumeMetadata: S.optional(
      VolumeMetadata.pipe(T.ProtoField({ n: 7, t: "message" })),
    ),
  }),
).annotate({ identifier: "Object" }) as any as S.Schema<Object>;

export type ObjectList = Array<Object>;
export const ObjectList = /*@__PURE__*/ S.Array(
  Object,
) as any as S.Schema<ObjectList>;

export interface AppLayout {
  objects?: ObjectList;
  functionIds?: StringMap;
  /** tag -> function id */
  classIds?: StringMap;
}
export const AppLayout = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    objects: S.optional(
      ObjectList.pipe(T.ProtoField({ n: 1, t: "message", rep: true })),
    ),
    functionIds: S.optional(
      StringMap.pipe(
        T.ProtoField({ n: 2, t: "map", k: "string", v: { t: "string" } }),
      ),
    ),
    classIds: S.optional(
      StringMap.pipe(
        T.ProtoField({ n: 3, t: "map", k: "string", v: { t: "string" } }),
      ),
    ),
  }),
).annotate({ identifier: "AppLayout" }) as any as S.Schema<AppLayout>;

export interface AppGetLayoutResponse {
  appLayout?: AppLayout;
}
export const AppGetLayoutResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appLayout: S.optional(AppLayout.pipe(T.ProtoField({ n: 1, t: "message" }))),
  }),
).annotate({
  identifier: "AppGetLayoutResponse",
}) as any as S.Schema<AppGetLayoutResponse>;

export interface AppGetLifecycleRequest {
  appId?: string;
}
export const AppGetLifecycleRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/AppGetLifecycle",
      code: 200,
    }),
  ),
).annotate({
  identifier: "AppGetLifecycleRequest",
}) as any as S.Schema<AppGetLifecycleRequest>;

export interface AppGetLifecycleResponse {
  lifecycle?: AppLifecycle;
}
export const AppGetLifecycleResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    lifecycle: S.optional(
      AppLifecycle.pipe(T.ProtoField({ n: 1, t: "message" })),
    ),
  }),
).annotate({
  identifier: "AppGetLifecycleResponse",
}) as any as S.Schema<AppGetLifecycleResponse>;

export interface AppGetObjectsRequest {
  appId?: string;
  includeUnindexed?: boolean;
  onlyClassFunction?: boolean;
}
export const AppGetObjectsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    includeUnindexed: S.optional(
      S.Boolean.pipe(T.ProtoField({ n: 2, t: "bool" })),
    ),
    onlyClassFunction: S.optional(
      S.Boolean.pipe(T.ProtoField({ n: 3, t: "bool" })),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/AppGetObjects",
      code: 200,
    }),
  ),
).annotate({
  identifier: "AppGetObjectsRequest",
}) as any as S.Schema<AppGetObjectsRequest>;

export interface AppGetObjectsItem {
  tag?: string;
  object?: Object;
}
export const AppGetObjectsItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    tag: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    object: S.optional(Object.pipe(T.ProtoField({ n: 6, t: "message" }))),
  }),
).annotate({
  identifier: "AppGetObjectsItem",
}) as any as S.Schema<AppGetObjectsItem>;

export type AppGetObjectsItemList = Array<AppGetObjectsItem>;
export const AppGetObjectsItemList = /*@__PURE__*/ S.Array(
  AppGetObjectsItem,
) as any as S.Schema<AppGetObjectsItemList>;

export interface AppGetObjectsResponse {
  items?: AppGetObjectsItemList;
}
export const AppGetObjectsResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    items: S.optional(
      AppGetObjectsItemList.pipe(
        T.ProtoField({ n: 2, t: "message", rep: true }),
      ),
    ),
  }),
).annotate({
  identifier: "AppGetObjectsResponse",
}) as any as S.Schema<AppGetObjectsResponse>;

export type ObjectCreationType =
  | "OBJECT_CREATION_TYPE_UNSPECIFIED"
  | "OBJECT_CREATION_TYPE_CREATE_IF_MISSING"
  | "OBJECT_CREATION_TYPE_CREATE_FAIL_IF_EXISTS"
  | "OBJECT_CREATION_TYPE_CREATE_OVERWRITE_IF_EXISTS"
  | "OBJECT_CREATION_TYPE_ANONYMOUS_OWNED_BY_APP"
  | "OBJECT_CREATION_TYPE_EPHEMERAL";
export const ObjectCreationType = S.String;

export interface AppGetOrCreateRequest {
  appName?: string;
  environmentName?: string;
  objectCreationType?: ObjectCreationType | (string & {});
}
export const AppGetOrCreateRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appName: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    environmentName: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "string" })),
    ),
    objectCreationType: S.optional(
      ObjectCreationType.pipe(
        T.ProtoField({
          n: 3,
          t: "enum",
          e: {
            OBJECT_CREATION_TYPE_UNSPECIFIED: 0,
            OBJECT_CREATION_TYPE_CREATE_IF_MISSING: 1,
            OBJECT_CREATION_TYPE_CREATE_FAIL_IF_EXISTS: 2,
            OBJECT_CREATION_TYPE_CREATE_OVERWRITE_IF_EXISTS: 3,
            OBJECT_CREATION_TYPE_ANONYMOUS_OWNED_BY_APP: 4,
            OBJECT_CREATION_TYPE_EPHEMERAL: 5,
          },
        }),
      ),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/AppGetOrCreate",
      code: 200,
    }),
  ),
).annotate({
  identifier: "AppGetOrCreateRequest",
}) as any as S.Schema<AppGetOrCreateRequest>;

export interface AppGetOrCreateResponse {
  appId?: string;
  handleMetadata?: AppHandleMetadata;
}
export const AppGetOrCreateResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    handleMetadata: S.optional(
      AppHandleMetadata.pipe(T.ProtoField({ n: 2, t: "message" })),
    ),
  }),
).annotate({
  identifier: "AppGetOrCreateResponse",
}) as any as S.Schema<AppGetOrCreateResponse>;

export interface AppGetTagsRequest {
  appId?: string;
}
export const AppGetTagsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/AppGetTags",
      code: 200,
    }),
  ),
).annotate({
  identifier: "AppGetTagsRequest",
}) as any as S.Schema<AppGetTagsRequest>;

export interface AppGetTagsResponse {
  tags?: StringMap;
}
export const AppGetTagsResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    tags: S.optional(
      StringMap.pipe(
        T.ProtoField({ n: 1, t: "map", k: "string", v: { t: "string" } }),
      ),
    ),
  }),
).annotate({
  identifier: "AppGetTagsResponse",
}) as any as S.Schema<AppGetTagsResponse>;

export interface AppHeartbeatRequest {
  appId?: string;
}
export const AppHeartbeatRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/AppHeartbeat",
      code: 200,
    }),
  ),
).annotate({
  identifier: "AppHeartbeatRequest",
}) as any as S.Schema<AppHeartbeatRequest>;

export interface AppHeartbeatResponse {}
export const AppHeartbeatResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "AppHeartbeatResponse",
}) as any as S.Schema<AppHeartbeatResponse>;

export interface AppRollbackRequest {
  appId?: string;
  version?: number;
}
export const AppRollbackRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    version: S.optional(S.Number.pipe(T.ProtoField({ n: 2, t: "int32" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/AppRollback",
      code: 200,
    }),
  ),
).annotate({
  identifier: "AppRollbackRequest",
}) as any as S.Schema<AppRollbackRequest>;

export type WarningWarningType =
  | "WARNING_TYPE_UNSPECIFIED"
  | "WARNING_TYPE_CLIENT_DEPRECATION"
  | "WARNING_TYPE_RESOURCE_LIMIT"
  | "WARNING_TYPE_FUNCTION_CONFIGURATION";
export const WarningWarningType = S.String;

export interface Warning {
  type?: WarningWarningType;
  message?: string;
}
export const Warning = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.optional(
      WarningWarningType.pipe(
        T.ProtoField({
          n: 1,
          t: "enum",
          e: {
            WARNING_TYPE_UNSPECIFIED: 0,
            WARNING_TYPE_CLIENT_DEPRECATION: 1,
            WARNING_TYPE_RESOURCE_LIMIT: 2,
            WARNING_TYPE_FUNCTION_CONFIGURATION: 3,
          },
        }),
      ),
    ),
    message: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
  }),
).annotate({ identifier: "Warning" }) as any as S.Schema<Warning>;

export type WarningList = Array<Warning>;
export const WarningList = /*@__PURE__*/ S.Array(
  Warning,
) as any as S.Schema<WarningList>;

export interface AppRollbackResponse {
  url?: string;
  serverWarnings?: WarningList;
  deployedAt?: number;
}
export const AppRollbackResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    url: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    serverWarnings: S.optional(
      WarningList.pipe(T.ProtoField({ n: 3, t: "message", rep: true })),
    ),
    deployedAt: S.optional(S.Number.pipe(T.ProtoField({ n: 4, t: "double" }))),
  }),
).annotate({
  identifier: "AppRollbackResponse",
}) as any as S.Schema<AppRollbackResponse>;

export interface AppRolloverRequest {
  appId?: string;
}
export const AppRolloverRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/AppRollover",
      code: 200,
    }),
  ),
).annotate({
  identifier: "AppRolloverRequest",
}) as any as S.Schema<AppRolloverRequest>;

export interface AppRolloverResponse {
  url?: string;
  serverWarnings?: WarningList;
  deployedAt?: number;
}
export const AppRolloverResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    url: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    serverWarnings: S.optional(
      WarningList.pipe(T.ProtoField({ n: 3, t: "message", rep: true })),
    ),
    deployedAt: S.optional(S.Number.pipe(T.ProtoField({ n: 4, t: "double" }))),
  }),
).annotate({
  identifier: "AppRolloverResponse",
}) as any as S.Schema<AppRolloverResponse>;

export interface AppSetObjectsRequest {
  appId?: string;
  indexedObjectIds?: StringMap;
  clientId?: string;
  unindexedObjectIds?: StringList;
  newAppState?: AppState | (string & {});
}
export const AppSetObjectsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    indexedObjectIds: S.optional(
      StringMap.pipe(
        T.ProtoField({ n: 2, t: "map", k: "string", v: { t: "string" } }),
      ),
    ),
    clientId: S.optional(S.String.pipe(T.ProtoField({ n: 3, t: "string" }))),
    unindexedObjectIds: S.optional(
      StringList.pipe(T.ProtoField({ n: 4, t: "string", rep: true })),
    ),
    newAppState: S.optional(
      AppState.pipe(
        T.ProtoField({
          n: 5,
          t: "enum",
          e: {
            APP_STATE_UNSPECIFIED: 0,
            APP_STATE_EPHEMERAL: 1,
            APP_STATE_DETACHED: 2,
            APP_STATE_DEPLOYED: 3,
            APP_STATE_STOPPING: 4,
            APP_STATE_STOPPED: 5,
            APP_STATE_INITIALIZING: 6,
            APP_STATE_DISABLED: 7,
            APP_STATE_DETACHED_DISCONNECTED: 8,
            APP_STATE_DERIVED: 9,
          },
        }),
      ),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/AppSetObjects",
      code: 200,
    }),
  ),
).annotate({
  identifier: "AppSetObjectsRequest",
}) as any as S.Schema<AppSetObjectsRequest>;

export interface AppSetObjectsResponse {}
export const AppSetObjectsResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "AppSetObjectsResponse",
}) as any as S.Schema<AppSetObjectsResponse>;

export interface AppSetTagsRequest {
  appId?: string;
  tags?: StringMap;
}
export const AppSetTagsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    tags: S.optional(
      StringMap.pipe(
        T.ProtoField({ n: 2, t: "map", k: "string", v: { t: "string" } }),
      ),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/AppSetTags",
      code: 200,
    }),
  ),
).annotate({
  identifier: "AppSetTagsRequest",
}) as any as S.Schema<AppSetTagsRequest>;

export interface AppSetTagsResponse {}
export const AppSetTagsResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "AppSetTagsResponse",
}) as any as S.Schema<AppSetTagsResponse>;

export interface CreateAppRequest {
  clientId?: string;
  description?: string;
  /** Human readable label for the app */
  environmentName?: string;
  appState?: AppState | (string & {});
  tags?: StringMap;
}
export const CreateAppRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    clientId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    description: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    environmentName: S.optional(
      S.String.pipe(T.ProtoField({ n: 5, t: "string" })),
    ),
    appState: S.optional(
      AppState.pipe(
        T.ProtoField({
          n: 6,
          t: "enum",
          e: {
            APP_STATE_UNSPECIFIED: 0,
            APP_STATE_EPHEMERAL: 1,
            APP_STATE_DETACHED: 2,
            APP_STATE_DEPLOYED: 3,
            APP_STATE_STOPPING: 4,
            APP_STATE_STOPPED: 5,
            APP_STATE_INITIALIZING: 6,
            APP_STATE_DISABLED: 7,
            APP_STATE_DETACHED_DISCONNECTED: 8,
            APP_STATE_DERIVED: 9,
          },
        }),
      ),
    ),
    tags: S.optional(
      StringMap.pipe(
        T.ProtoField({ n: 7, t: "map", k: "string", v: { t: "string" } }),
      ),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/AppCreate",
      code: 200,
    }),
  ),
).annotate({
  identifier: "CreateAppRequest",
}) as any as S.Schema<CreateAppRequest>;

export interface CreateAppResponse {
  appId?: string;
  appPageUrl?: string;
  appLogsUrl?: string;
}
export const CreateAppResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    appPageUrl: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    appLogsUrl: S.optional(S.String.pipe(T.ProtoField({ n: 3, t: "string" }))),
  }),
).annotate({
  identifier: "CreateAppResponse",
}) as any as S.Schema<CreateAppResponse>;

/** gRPC protos for Modal's public API surface. Warning: direct usage of Modal's gRPC API is discouraged, and no support or compatibility guarantees are provided. Message fields or entire RPCs may be changed or removed without notice. We recommend using official SDKs instead. */
export type AppDeployVisibility =
  | "APP_DEPLOY_VISIBILITY_UNSPECIFIED"
  | "APP_DEPLOY_VISIBILITY_WORKSPACE"
  | "APP_DEPLOY_VISIBILITY_PUBLIC";
export const AppDeployVisibility = S.String;

export interface DeployAppRequest {
  appId?: string;
  /** namespace */
  name?: string;
  objectEntity?: string;
  visibility?: AppDeployVisibility | (string & {});
  tag?: string;
}
export const DeployAppRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    name: S.optional(S.String.pipe(T.ProtoField({ n: 3, t: "string" }))),
    objectEntity: S.optional(
      S.String.pipe(T.ProtoField({ n: 4, t: "string" })),
    ),
    visibility: S.optional(
      AppDeployVisibility.pipe(
        T.ProtoField({
          n: 5,
          t: "enum",
          e: {
            APP_DEPLOY_VISIBILITY_UNSPECIFIED: 0,
            APP_DEPLOY_VISIBILITY_WORKSPACE: 1,
            APP_DEPLOY_VISIBILITY_PUBLIC: 2,
          },
        }),
      ),
    ),
    tag: S.optional(S.String.pipe(T.ProtoField({ n: 6, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/AppDeploy",
      code: 200,
    }),
  ),
).annotate({
  identifier: "DeployAppRequest",
}) as any as S.Schema<DeployAppRequest>;

export interface DeployAppResponse {
  url?: string;
}
export const DeployAppResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    url: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
  }),
).annotate({
  identifier: "DeployAppResponse",
}) as any as S.Schema<DeployAppResponse>;

export type AppDisconnectReason =
  | "APP_DISCONNECT_REASON_UNSPECIFIED"
  | "APP_DISCONNECT_REASON_LOCAL_EXCEPTION"
  | "APP_DISCONNECT_REASON_KEYBOARD_INTERRUPT"
  | "APP_DISCONNECT_REASON_ENTRYPOINT_COMPLETED"
  | "APP_DISCONNECT_REASON_DEPLOYMENT_EXCEPTION"
  | "APP_DISCONNECT_REASON_REMOTE_EXCEPTION";
export const AppDisconnectReason = S.String;

export interface DisconnectAppClientRequest {
  appId?: string;
  reason?: AppDisconnectReason | (string & {});
  exception?: string;
}
export const DisconnectAppClientRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    reason: S.optional(
      AppDisconnectReason.pipe(
        T.ProtoField({
          n: 2,
          t: "enum",
          e: {
            APP_DISCONNECT_REASON_UNSPECIFIED: 0,
            APP_DISCONNECT_REASON_LOCAL_EXCEPTION: 1,
            APP_DISCONNECT_REASON_KEYBOARD_INTERRUPT: 2,
            APP_DISCONNECT_REASON_ENTRYPOINT_COMPLETED: 3,
            APP_DISCONNECT_REASON_DEPLOYMENT_EXCEPTION: 4,
            APP_DISCONNECT_REASON_REMOTE_EXCEPTION: 5,
          },
        }),
      ),
    ),
    exception: S.optional(S.String.pipe(T.ProtoField({ n: 3, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/AppClientDisconnect",
      code: 200,
    }),
  ),
).annotate({
  identifier: "DisconnectAppClientRequest",
}) as any as S.Schema<DisconnectAppClientRequest>;

export interface DisconnectAppClientResponse {}
export const DisconnectAppClientResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "DisconnectAppClientResponse",
}) as any as S.Schema<DisconnectAppClientResponse>;

export interface ListAppRequest {
  environmentName?: string;
}
export const ListAppRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    environmentName: S.optional(
      S.String.pipe(T.ProtoField({ n: 1, t: "string" })),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/AppList",
      code: 200,
    }),
  ),
).annotate({ identifier: "ListAppRequest" }) as any as S.Schema<ListAppRequest>;

export interface ListAppResponseAppListItem {
  appId?: string;
  description?: string;
  state?: AppState;
  createdAt?: number;
  stoppedAt?: number;
  nRunningTasks?: number;
  name?: string;
}
export const ListAppResponseAppListItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    description: S.optional(S.String.pipe(T.ProtoField({ n: 3, t: "string" }))),
    state: S.optional(
      AppState.pipe(
        T.ProtoField({
          n: 4,
          t: "enum",
          e: {
            APP_STATE_UNSPECIFIED: 0,
            APP_STATE_EPHEMERAL: 1,
            APP_STATE_DETACHED: 2,
            APP_STATE_DEPLOYED: 3,
            APP_STATE_STOPPING: 4,
            APP_STATE_STOPPED: 5,
            APP_STATE_INITIALIZING: 6,
            APP_STATE_DISABLED: 7,
            APP_STATE_DETACHED_DISCONNECTED: 8,
            APP_STATE_DERIVED: 9,
          },
        }),
      ),
    ),
    createdAt: S.optional(S.Number.pipe(T.ProtoField({ n: 5, t: "double" }))),
    stoppedAt: S.optional(S.Number.pipe(T.ProtoField({ n: 6, t: "double" }))),
    nRunningTasks: S.optional(
      S.Number.pipe(T.ProtoField({ n: 8, t: "int32" })),
    ),
    name: S.optional(S.String.pipe(T.ProtoField({ n: 10, t: "string" }))),
  }),
).annotate({
  identifier: "ListAppResponseAppListItem",
}) as any as S.Schema<ListAppResponseAppListItem>;

export type ListAppResponseAppListItemList = Array<ListAppResponseAppListItem>;
export const ListAppResponseAppListItemList = /*@__PURE__*/ S.Array(
  ListAppResponseAppListItem,
) as any as S.Schema<ListAppResponseAppListItemList>;

export interface ListAppResponse {
  apps?: ListAppResponseAppListItemList;
}
export const ListAppResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    apps: S.optional(
      ListAppResponseAppListItemList.pipe(
        T.ProtoField({ n: 1, t: "message", rep: true }),
      ),
    ),
  }),
).annotate({
  identifier: "ListAppResponse",
}) as any as S.Schema<ListAppResponse>;

export interface LookupAppRequest {
  appName?: string;
  environmentName?: string;
}
export const LookupAppRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appName: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    environmentName: S.optional(
      S.String.pipe(T.ProtoField({ n: 3, t: "string" })),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/AppLookup",
      code: 200,
    }),
  ),
).annotate({
  identifier: "LookupAppRequest",
}) as any as S.Schema<LookupAppRequest>;

export interface LookupAppResponse {
  appId?: string;
}
export const LookupAppResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
  }),
).annotate({
  identifier: "LookupAppResponse",
}) as any as S.Schema<LookupAppResponse>;

export interface PromoteAppRequest {
  appId?: string;
  version?: number;
}
export const PromoteAppRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    version: S.optional(S.Number.pipe(T.ProtoField({ n: 2, t: "int32" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/AppPromote",
      code: 200,
    }),
  ),
).annotate({
  identifier: "PromoteAppRequest",
}) as any as S.Schema<PromoteAppRequest>;

export interface PromoteAppResponse {
  url?: string;
  serverWarnings?: WarningList;
  deployedAt?: number;
}
export const PromoteAppResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    url: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    serverWarnings: S.optional(
      WarningList.pipe(T.ProtoField({ n: 2, t: "message", rep: true })),
    ),
    deployedAt: S.optional(S.Number.pipe(T.ProtoField({ n: 3, t: "double" }))),
  }),
).annotate({
  identifier: "PromoteAppResponse",
}) as any as S.Schema<PromoteAppResponse>;

export interface PublishAppRequest {
  appId?: string;
  name?: string;
  deploymentTag?: string;
  /** Additional metadata to identify a deployment */
  appState?: AppState | (string & {});
  /** Published app will be in this state */
  functionIds?: StringMap;
  /** function_name -> function_id */
  classIds?: StringMap;
  /** class_name -> class_id */
  definitionIds?: StringMap;
  /** function_id -> definition_id */
  rollbackVersion?: number;
  /** Unused by client, but used internally */
  clientVersion?: string;
  /** Unused by client, but used internally */
  commitInfo?: CommitInfo;
  /** Git information for deployment tracking */
  tags?: StringMap;
  /** Additional metadata to attach to the App If true, create a version pinned deployment but don't update the production deployment definition on publish */
  staged?: boolean;
  deploymentType?: DeploymentType | (string & {});
}
export const PublishAppRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    name: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    deploymentTag: S.optional(
      S.String.pipe(T.ProtoField({ n: 3, t: "string" })),
    ),
    appState: S.optional(
      AppState.pipe(
        T.ProtoField({
          n: 4,
          t: "enum",
          e: {
            APP_STATE_UNSPECIFIED: 0,
            APP_STATE_EPHEMERAL: 1,
            APP_STATE_DETACHED: 2,
            APP_STATE_DEPLOYED: 3,
            APP_STATE_STOPPING: 4,
            APP_STATE_STOPPED: 5,
            APP_STATE_INITIALIZING: 6,
            APP_STATE_DISABLED: 7,
            APP_STATE_DETACHED_DISCONNECTED: 8,
            APP_STATE_DERIVED: 9,
          },
        }),
      ),
    ),
    functionIds: S.optional(
      StringMap.pipe(
        T.ProtoField({ n: 5, t: "map", k: "string", v: { t: "string" } }),
      ),
    ),
    classIds: S.optional(
      StringMap.pipe(
        T.ProtoField({ n: 6, t: "map", k: "string", v: { t: "string" } }),
      ),
    ),
    definitionIds: S.optional(
      StringMap.pipe(
        T.ProtoField({ n: 7, t: "map", k: "string", v: { t: "string" } }),
      ),
    ),
    rollbackVersion: S.optional(
      S.Number.pipe(T.ProtoField({ n: 8, t: "uint32" })),
    ),
    clientVersion: S.optional(
      S.String.pipe(T.ProtoField({ n: 9, t: "string" })),
    ),
    commitInfo: S.optional(
      CommitInfo.pipe(T.ProtoField({ n: 10, t: "message" })),
    ),
    tags: S.optional(
      StringMap.pipe(
        T.ProtoField({ n: 11, t: "map", k: "string", v: { t: "string" } }),
      ),
    ),
    staged: S.optional(S.Boolean.pipe(T.ProtoField({ n: 12, t: "bool" }))),
    deploymentType: S.optional(
      DeploymentType.pipe(
        T.ProtoField({
          n: 13,
          t: "enum",
          e: {
            DEPLOYMENT_TYPE_UNSPECIFIED: 0,
            DEPLOYMENT_TYPE_STANDARD: 1,
            DEPLOYMENT_TYPE_ROLLBACK: 2,
            DEPLOYMENT_TYPE_ROLLOVER: 3,
            DEPLOYMENT_TYPE_PROMOTION: 4,
            DEPLOYMENT_TYPE_STAGED: 5,
          },
        }),
      ),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/AppPublish",
      code: 200,
    }),
  ),
).annotate({
  identifier: "PublishAppRequest",
}) as any as S.Schema<PublishAppRequest>;

export interface PublishAppResponse {
  url?: string;
  serverWarnings?: WarningList;
  deployedAt?: number;
}
export const PublishAppResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    url: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    serverWarnings: S.optional(
      WarningList.pipe(T.ProtoField({ n: 3, t: "message", rep: true })),
    ),
    deployedAt: S.optional(S.Number.pipe(T.ProtoField({ n: 4, t: "double" }))),
  }),
).annotate({
  identifier: "PublishAppResponse",
}) as any as S.Schema<PublishAppResponse>;

export type AppStopSource =
  | "APP_STOP_SOURCE_UNSPECIFIED"
  | "APP_STOP_SOURCE_CLI"
  | "APP_STOP_SOURCE_PYTHON_CLIENT"
  | "APP_STOP_SOURCE_WEB";
export const AppStopSource = S.String;

export interface StopAppRequest {
  appId?: string;
  source?: AppStopSource | (string & {});
}
export const StopAppRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    source: S.optional(
      AppStopSource.pipe(
        T.ProtoField({
          n: 2,
          t: "enum",
          e: {
            APP_STOP_SOURCE_UNSPECIFIED: 0,
            APP_STOP_SOURCE_CLI: 1,
            APP_STOP_SOURCE_PYTHON_CLIENT: 2,
            APP_STOP_SOURCE_WEB: 3,
          },
        }),
      ),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/AppStop",
      code: 200,
    }),
  ),
).annotate({ identifier: "StopAppRequest" }) as any as S.Schema<StopAppRequest>;

export interface StopAppResponse {}
export const StopAppResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "StopAppResponse",
}) as any as S.Schema<StopAppResponse>;

export type AppCountLogsError = ModalOpError;
export const appCountLogs: API.OperationMethod<
  AppCountLogsRequest,
  AppCountLogsResponse,
  AppCountLogsError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AppCountLogsRequest,
  output: AppCountLogsResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type AppDeploymentHistoryError = ModalOpError;
export const appDeploymentHistory: API.OperationMethod<
  AppDeploymentHistoryRequest,
  AppDeploymentHistoryResponse,
  AppDeploymentHistoryError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AppDeploymentHistoryRequest,
  output: AppDeploymentHistoryResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type AppFetchLogsError = ModalOpError;
export const appFetchLogs: API.OperationMethod<
  AppFetchLogsRequest,
  AppFetchLogsResponse,
  AppFetchLogsError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AppFetchLogsRequest,
  output: AppFetchLogsResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type AppGetByDeploymentNameError = ModalOpError;
export const appGetByDeploymentName: API.OperationMethod<
  AppGetByDeploymentNameRequest,
  AppGetByDeploymentNameResponse,
  AppGetByDeploymentNameError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AppGetByDeploymentNameRequest,
  output: AppGetByDeploymentNameResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type AppGetInfoError = ModalOpError;
export const appGetInfo: API.OperationMethod<
  AppGetInfoRequest,
  AppGetInfoResponse,
  AppGetInfoError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AppGetInfoRequest,
  output: AppGetInfoResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type AppGetLayoutError = ModalOpError;
export const appGetLayout: API.OperationMethod<
  AppGetLayoutRequest,
  AppGetLayoutResponse,
  AppGetLayoutError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AppGetLayoutRequest,
  output: AppGetLayoutResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type AppGetLifecycleError = ModalOpError;
export const appGetLifecycle: API.OperationMethod<
  AppGetLifecycleRequest,
  AppGetLifecycleResponse,
  AppGetLifecycleError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AppGetLifecycleRequest,
  output: AppGetLifecycleResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type AppGetObjectsError = ModalOpError;
export const appGetObjects: API.OperationMethod<
  AppGetObjectsRequest,
  AppGetObjectsResponse,
  AppGetObjectsError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AppGetObjectsRequest,
  output: AppGetObjectsResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type AppGetOrCreateError = ModalOpError;
export const appGetOrCreate: API.OperationMethod<
  AppGetOrCreateRequest,
  AppGetOrCreateResponse,
  AppGetOrCreateError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AppGetOrCreateRequest,
  output: AppGetOrCreateResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type AppGetTagsError = ModalOpError;
export const appGetTags: API.OperationMethod<
  AppGetTagsRequest,
  AppGetTagsResponse,
  AppGetTagsError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AppGetTagsRequest,
  output: AppGetTagsResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type AppHeartbeatError = ModalOpError;
export const appHeartbeat: API.OperationMethod<
  AppHeartbeatRequest,
  AppHeartbeatResponse,
  AppHeartbeatError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AppHeartbeatRequest,
  output: AppHeartbeatResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type AppRollbackError = ModalOpError;
export const appRollback: API.OperationMethod<
  AppRollbackRequest,
  AppRollbackResponse,
  AppRollbackError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AppRollbackRequest,
  output: AppRollbackResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type AppRolloverError = ModalOpError;
export const appRollover: API.OperationMethod<
  AppRolloverRequest,
  AppRolloverResponse,
  AppRolloverError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AppRolloverRequest,
  output: AppRolloverResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type AppSetObjectsError = ModalOpError;
export const appSetObjects: API.OperationMethod<
  AppSetObjectsRequest,
  AppSetObjectsResponse,
  AppSetObjectsError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AppSetObjectsRequest,
  output: AppSetObjectsResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type AppSetTagsError = ModalOpError;
export const appSetTags: API.OperationMethod<
  AppSetTagsRequest,
  AppSetTagsResponse,
  AppSetTagsError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AppSetTagsRequest,
  output: AppSetTagsResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type CreateAppError = ModalOpError;
export const createApp: API.OperationMethod<
  CreateAppRequest,
  CreateAppResponse,
  CreateAppError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateAppRequest,
  output: CreateAppResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type DeployAppError = ModalOpError;
export const deployApp: API.OperationMethod<
  DeployAppRequest,
  DeployAppResponse,
  DeployAppError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeployAppRequest,
  output: DeployAppResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type DisconnectAppClientError = ModalOpError;
/** Apps */
export const disconnectAppClient: API.OperationMethod<
  DisconnectAppClientRequest,
  DisconnectAppClientResponse,
  DisconnectAppClientError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DisconnectAppClientRequest,
  output: DisconnectAppClientResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type ListAppError = ModalOpError;
export const listApp: API.OperationMethod<
  ListAppRequest,
  ListAppResponse,
  ListAppError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListAppRequest,
  output: ListAppResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type LookupAppError = ModalOpError;
export const lookupApp: API.OperationMethod<
  LookupAppRequest,
  LookupAppResponse,
  LookupAppError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: LookupAppRequest,
  output: LookupAppResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type PromoteAppError = ModalOpError;
export const promoteApp: API.OperationMethod<
  PromoteAppRequest,
  PromoteAppResponse,
  PromoteAppError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PromoteAppRequest,
  output: PromoteAppResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type PublishAppError = ModalOpError;
export const publishApp: API.OperationMethod<
  PublishAppRequest,
  PublishAppResponse,
  PublishAppError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PublishAppRequest,
  output: PublishAppResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type StopAppError = ModalOpError;
export const stopApp: API.OperationMethod<
  StopAppRequest,
  StopAppResponse,
  StopAppError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: StopAppRequest,
  output: StopAppResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));
