// AUTO-GENERATED by scripts/generate.ts from .generated-specs (modal_proto → smithy). Do not edit.
import * as S from "@rikalabs/distilled-core/schema";
import * as API from "@rikalabs/distilled-core/api";
import * as T from "../traits.ts";
import {
  ModalProtocol,
  type ModalOpError,
  type ModalOpContext,
} from "../protocol.ts";
import { UnknownModalError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { ModalOpError, ModalOpContext };

export interface AttemptAwaitRequest {
  attemptToken?: string;
  requestedAt?: number;
  /** Used for waypoints. */
  timeoutSecs?: number;
}
export const AttemptAwaitRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    attemptToken: S.optional(
      S.String.pipe(T.ProtoField({ n: 1, t: "string" })),
    ),
    requestedAt: S.optional(S.Number.pipe(T.ProtoField({ n: 2, t: "double" }))),
    timeoutSecs: S.optional(S.Number.pipe(T.ProtoField({ n: 3, t: "float" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/AttemptAwait",
      code: 200,
    }),
  ),
).annotate({
  identifier: "AttemptAwaitRequest",
}) as any as S.Schema<AttemptAwaitRequest>;

/** Used for both tasks and function outputs */
export type GenericResultGenericStatus =
  | "GENERIC_STATUS_UNSPECIFIED"
  | "GENERIC_STATUS_SUCCESS"
  | "GENERIC_STATUS_FAILURE"
  | "GENERIC_STATUS_TERMINATED"
  | "GENERIC_STATUS_TIMEOUT"
  | "GENERIC_STATUS_INIT_FAILURE"
  | "GENERIC_STATUS_INTERNAL_FAILURE"
  | "GENERIC_STATUS_IDLE_TIMEOUT"
  | "GENERIC_STATUS_MEMORY_MANAGER_EVICTION";
export const GenericResultGenericStatus = S.String;

/** sub-type for generic types like lists */
export interface GenericResult {
  status?: GenericResultGenericStatus;
  /** Status of the task or function output. */
  exception?: string;
  /** Exception message for failures, if available. */
  exitcode?: number;
  /** Status code of the container entrypoint or builder process if it terminates unexpectedly. */
  traceback?: string;
  /** String value of the Python traceback. */
  serializedTb?: string;
  /** Pickled traceback object. */
  tbLineCache?: string;
  /** Pickled line cache for traceback object. */
  data?: string;
  /** Inline data of the result. */
  dataBlobId?: string;
  /** Blob ID for large data. */
  propagationReason?: string;
}
export const GenericResult = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    status: S.optional(
      GenericResultGenericStatus.pipe(
        T.ProtoField({
          n: 1,
          t: "enum",
          e: {
            GENERIC_STATUS_UNSPECIFIED: 0,
            GENERIC_STATUS_SUCCESS: 1,
            GENERIC_STATUS_FAILURE: 2,
            GENERIC_STATUS_TERMINATED: 3,
            GENERIC_STATUS_TIMEOUT: 4,
            GENERIC_STATUS_INIT_FAILURE: 5,
            GENERIC_STATUS_INTERNAL_FAILURE: 6,
            GENERIC_STATUS_IDLE_TIMEOUT: 7,
            GENERIC_STATUS_MEMORY_MANAGER_EVICTION: 8,
          },
        }),
      ),
    ),
    exception: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    exitcode: S.optional(S.Number.pipe(T.ProtoField({ n: 3, t: "int32" }))),
    traceback: S.optional(S.String.pipe(T.ProtoField({ n: 4, t: "string" }))),
    serializedTb: S.optional(
      S.String.pipe(T.ProtoField({ n: 11, t: "bytes" })),
    ),
    tbLineCache: S.optional(S.String.pipe(T.ProtoField({ n: 12, t: "bytes" }))),
    data: S.optional(S.String.pipe(T.ProtoField({ n: 5, t: "bytes" }))),
    dataBlobId: S.optional(S.String.pipe(T.ProtoField({ n: 10, t: "string" }))),
    propagationReason: S.optional(
      S.String.pipe(T.ProtoField({ n: 13, t: "string" })),
    ),
  }),
).annotate({ identifier: "GenericResult" }) as any as S.Schema<GenericResult>;

/** Which data format a binary message is encoded with. */
export type DataFormat =
  | "DATA_FORMAT_UNSPECIFIED"
  | "DATA_FORMAT_PICKLE"
  | "DATA_FORMAT_ASGI"
  | "DATA_FORMAT_GENERATOR_DONE"
  | "DATA_FORMAT_CBOR";
export const DataFormat = S.String;

/** How long to sleep before requesting another input. */
export interface FunctionGetOutputsItem {
  result?: GenericResult;
  idx?: number;
  inputId?: string;
  dataFormat?: DataFormat;
  /** for result.data_oneof */
  taskId?: string;
  inputStartedAt?: number;
  outputCreatedAt?: number;
  retryCount?: number;
  fcTraceTag?: string;
}
export const FunctionGetOutputsItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    result: S.optional(
      GenericResult.pipe(T.ProtoField({ n: 1, t: "message" })),
    ),
    idx: S.optional(S.Number.pipe(T.ProtoField({ n: 2, t: "int32" }))),
    inputId: S.optional(S.String.pipe(T.ProtoField({ n: 3, t: "string" }))),
    dataFormat: S.optional(
      DataFormat.pipe(
        T.ProtoField({
          n: 5,
          t: "enum",
          e: {
            DATA_FORMAT_UNSPECIFIED: 0,
            DATA_FORMAT_PICKLE: 1,
            DATA_FORMAT_ASGI: 2,
            DATA_FORMAT_GENERATOR_DONE: 3,
            DATA_FORMAT_CBOR: 4,
          },
        }),
      ),
    ),
    taskId: S.optional(S.String.pipe(T.ProtoField({ n: 6, t: "string" }))),
    inputStartedAt: S.optional(
      S.Number.pipe(T.ProtoField({ n: 7, t: "double" })),
    ),
    outputCreatedAt: S.optional(
      S.Number.pipe(T.ProtoField({ n: 8, t: "double" })),
    ),
    retryCount: S.optional(S.Number.pipe(T.ProtoField({ n: 9, t: "uint32" }))),
    fcTraceTag: S.optional(S.String.pipe(T.ProtoField({ n: 10, t: "string" }))),
  }),
).annotate({
  identifier: "FunctionGetOutputsItem",
}) as any as S.Schema<FunctionGetOutputsItem>;

export interface AttemptAwaitResponse {
  output?: FunctionGetOutputsItem;
}
export const AttemptAwaitResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    output: S.optional(
      FunctionGetOutputsItem.pipe(T.ProtoField({ n: 1, t: "message" })),
    ),
  }),
).annotate({
  identifier: "AttemptAwaitResponse",
}) as any as S.Schema<AttemptAwaitResponse>;

export interface FunctionInput {
  /** serialized (args, kwargs). */
  args?: string;
  argsBlobId?: string;
  finalInput?: boolean;
  dataFormat?: DataFormat | (string & {});
  /** For args_oneof. */
  methodName?: string;
}
export const FunctionInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    args: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "bytes" }))),
    argsBlobId: S.optional(S.String.pipe(T.ProtoField({ n: 7, t: "string" }))),
    finalInput: S.optional(S.Boolean.pipe(T.ProtoField({ n: 9, t: "bool" }))),
    dataFormat: S.optional(
      DataFormat.pipe(
        T.ProtoField({
          n: 10,
          t: "enum",
          e: {
            DATA_FORMAT_UNSPECIFIED: 0,
            DATA_FORMAT_PICKLE: 1,
            DATA_FORMAT_ASGI: 2,
            DATA_FORMAT_GENERATOR_DONE: 3,
            DATA_FORMAT_CBOR: 4,
          },
        }),
      ),
    ),
    methodName: S.optional(S.String.pipe(T.ProtoField({ n: 11, t: "string" }))),
  }),
).annotate({ identifier: "FunctionInput" }) as any as S.Schema<FunctionInput>;

export type BlobUploadResultOutcome =
  | "OUTCOME_UNSPECIFIED"
  | "OUTCOME_SUCCESS"
  | "OUTCOME_FAILURE";
export const BlobUploadResultOutcome = S.String;

export interface BlobUploadResult {
  blobId?: string;
  /** The blob id (from BlobCreateResponse) that this upload attempt targeted. */
  outcome?: BlobUploadResultOutcome | (string & {});
  throughputBytesS?: string;
}
export const BlobUploadResult = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    blobId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    outcome: S.optional(
      BlobUploadResultOutcome.pipe(
        T.ProtoField({
          n: 2,
          t: "enum",
          e: { OUTCOME_UNSPECIFIED: 0, OUTCOME_SUCCESS: 1, OUTCOME_FAILURE: 2 },
        }),
      ),
    ),
    throughputBytesS: S.optional(
      S.String.pipe(T.ProtoField({ n: 3, t: "uint64" })),
    ),
  }),
).annotate({
  identifier: "BlobUploadResult",
}) as any as S.Schema<BlobUploadResult>;

export type BlobUploadResultList = Array<BlobUploadResult>;
export const BlobUploadResultList = /*@__PURE__*/ S.Array(
  BlobUploadResult,
) as any as S.Schema<BlobUploadResultList>;

export interface FunctionPutInputsItem {
  idx?: number;
  input?: FunctionInput;
  r2Failed?: boolean;
  /** r2_latency_ms */
  r2ThroughputBytesS?: string;
  blobUploadResults?: BlobUploadResultList;
}
export const FunctionPutInputsItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    idx: S.optional(S.Number.pipe(T.ProtoField({ n: 1, t: "int32" }))),
    input: S.optional(FunctionInput.pipe(T.ProtoField({ n: 2, t: "message" }))),
    r2Failed: S.optional(S.Boolean.pipe(T.ProtoField({ n: 3, t: "bool" }))),
    r2ThroughputBytesS: S.optional(
      S.String.pipe(T.ProtoField({ n: 5, t: "uint64" })),
    ),
    blobUploadResults: S.optional(
      BlobUploadResultList.pipe(
        T.ProtoField({ n: 6, t: "message", rep: true }),
      ),
    ),
  }),
).annotate({
  identifier: "FunctionPutInputsItem",
}) as any as S.Schema<FunctionPutInputsItem>;

export interface RetryAttemptRequest {
  functionId?: string;
  parentInputId?: string;
  input?: FunctionPutInputsItem;
  attemptToken?: string;
}
export const RetryAttemptRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    functionId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    parentInputId: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "string" })),
    ),
    input: S.optional(
      FunctionPutInputsItem.pipe(T.ProtoField({ n: 3, t: "message" })),
    ),
    attemptToken: S.optional(
      S.String.pipe(T.ProtoField({ n: 4, t: "string" })),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/AttemptRetry",
      code: 200,
    }),
  ),
).annotate({
  identifier: "RetryAttemptRequest",
}) as any as S.Schema<RetryAttemptRequest>;

export interface RetryAttemptResponse {
  attemptToken?: string;
}
export const RetryAttemptResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    attemptToken: S.optional(
      S.String.pipe(T.ProtoField({ n: 1, t: "string" })),
    ),
  }),
).annotate({
  identifier: "RetryAttemptResponse",
}) as any as S.Schema<RetryAttemptResponse>;

export interface StartAttemptRequest {
  functionId?: string;
  parentInputId?: string;
  input?: FunctionPutInputsItem;
  proxied?: boolean;
}
export const StartAttemptRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    functionId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    parentInputId: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "string" })),
    ),
    input: S.optional(
      FunctionPutInputsItem.pipe(T.ProtoField({ n: 3, t: "message" })),
    ),
    proxied: S.optional(S.Boolean.pipe(T.ProtoField({ n: 4, t: "bool" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/AttemptStart",
      code: 200,
    }),
  ),
).annotate({
  identifier: "StartAttemptRequest",
}) as any as S.Schema<StartAttemptRequest>;

export interface FunctionRetryPolicy {
  backoffCoefficient?: number;
  initialDelayMs?: number;
  maxDelayMs?: number;
  /** NOTE: two-byte field number not used for special reason. copy-paste error. Ref: PR #2542 */
  retries?: number;
}
export const FunctionRetryPolicy = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    backoffCoefficient: S.optional(
      S.Number.pipe(T.ProtoField({ n: 1, t: "float" })),
    ),
    initialDelayMs: S.optional(
      S.Number.pipe(T.ProtoField({ n: 2, t: "uint32" })),
    ),
    maxDelayMs: S.optional(S.Number.pipe(T.ProtoField({ n: 3, t: "uint32" }))),
    retries: S.optional(S.Number.pipe(T.ProtoField({ n: 18, t: "uint32" }))),
  }),
).annotate({
  identifier: "FunctionRetryPolicy",
}) as any as S.Schema<FunctionRetryPolicy>;

export interface StartAttemptResponse {
  attemptToken?: string;
  retryPolicy?: FunctionRetryPolicy;
}
export const StartAttemptResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    attemptToken: S.optional(
      S.String.pipe(T.ProtoField({ n: 1, t: "string" })),
    ),
    retryPolicy: S.optional(
      FunctionRetryPolicy.pipe(T.ProtoField({ n: 2, t: "message" })),
    ),
  }),
).annotate({
  identifier: "StartAttemptResponse",
}) as any as S.Schema<StartAttemptResponse>;

export type AttemptAwaitError = ModalOpError;
/** Input Plane */
export const attemptAwait: API.OperationMethod<
  AttemptAwaitRequest,
  AttemptAwaitResponse,
  AttemptAwaitError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: AttemptAwaitRequest,
  output: AttemptAwaitResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type RetryAttemptError = ModalOpError;
export const retryAttempt: API.OperationMethod<
  RetryAttemptRequest,
  RetryAttemptResponse,
  RetryAttemptError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: RetryAttemptRequest,
  output: RetryAttemptResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type StartAttemptError = ModalOpError;
export const startAttempt: API.OperationMethod<
  StartAttemptRequest,
  StartAttemptResponse,
  StartAttemptError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: StartAttemptRequest,
  output: StartAttemptResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));
