// AUTO-GENERATED by scripts/generate.ts from .generated-specs (modal_proto → smithy). Do not edit.
import * as S from "@rikalabs/distilled-core/schema";
import * as API from "@rikalabs/distilled-core/api";
import * as T from "../traits.ts";
import {
  ModalProtocol,
  type ModalOpError,
  type ModalOpContext,
} from "../protocol.ts";
import { UnknownModalError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { ModalOpError, ModalOpContext };

export type FunctionFunctionType =
  | "FUNCTION_TYPE_UNSPECIFIED"
  | "FUNCTION_TYPE_GENERATOR"
  | "FUNCTION_TYPE_FUNCTION";
export const FunctionFunctionType = S.String;

export type ClassParameterInfoParameterSerializationFormat =
  | "PARAM_SERIALIZATION_FORMAT_UNSPECIFIED"
  | "PARAM_SERIALIZATION_FORMAT_PICKLE"
  | "PARAM_SERIALIZATION_FORMAT_PROTO";
export const ClassParameterInfoParameterSerializationFormat = S.String;

export type ParameterType =
  | "PARAM_TYPE_UNSPECIFIED"
  | "PARAM_TYPE_STRING"
  | "PARAM_TYPE_INT"
  | "PARAM_TYPE_PICKLE"
  | "PARAM_TYPE_BYTES"
  | "PARAM_TYPE_UNKNOWN"
  | "PARAM_TYPE_LIST"
  | "PARAM_TYPE_DICT"
  | "PARAM_TYPE_NONE"
  | "PARAM_TYPE_BOOL";
export const ParameterType = S.String;

export type GenericPayloadTypeList = Array<GenericPayloadType>;
export const GenericPayloadTypeList = /*@__PURE__*/ S.Array(
  S.suspend(() => GenericPayloadType),
) as any as S.Schema<GenericPayloadTypeList>;

export interface GenericPayloadType {
  baseType?: ParameterType | (string & {});
  subTypes?: GenericPayloadTypeList;
}
export const GenericPayloadType = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    baseType: S.optional(
      ParameterType.pipe(
        T.ProtoField({
          n: 1,
          t: "enum",
          e: {
            PARAM_TYPE_UNSPECIFIED: 0,
            PARAM_TYPE_STRING: 1,
            PARAM_TYPE_INT: 2,
            PARAM_TYPE_PICKLE: 3,
            PARAM_TYPE_BYTES: 4,
            PARAM_TYPE_UNKNOWN: 5,
            PARAM_TYPE_LIST: 6,
            PARAM_TYPE_DICT: 7,
            PARAM_TYPE_NONE: 8,
            PARAM_TYPE_BOOL: 9,
          },
        }),
      ),
    ),
    subTypes: S.optional(
      GenericPayloadTypeList.pipe(
        T.ProtoField({ n: 2, t: "message", rep: true }),
      ),
    ),
  }),
).annotate({
  identifier: "GenericPayloadType",
}) as any as S.Schema<GenericPayloadType>;

export interface ClassParameterSpec {
  /** TODO: rename into NamedPayloadType or similar */
  name?: string;
  type?: ParameterType | (string & {});
  /** TODO: deprecate - use full_type instead */
  hasDefault?: boolean;
  /** Default *values* are only registered for class parameters */
  stringDefault?: string;
  intDefault?: string;
  pickleDefault?: string;
  bytesDefault?: string;
  boolDefault?: boolean;
  fullType?: GenericPayloadType;
}
export const ClassParameterSpec = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    type: S.optional(
      ParameterType.pipe(
        T.ProtoField({
          n: 2,
          t: "enum",
          e: {
            PARAM_TYPE_UNSPECIFIED: 0,
            PARAM_TYPE_STRING: 1,
            PARAM_TYPE_INT: 2,
            PARAM_TYPE_PICKLE: 3,
            PARAM_TYPE_BYTES: 4,
            PARAM_TYPE_UNKNOWN: 5,
            PARAM_TYPE_LIST: 6,
            PARAM_TYPE_DICT: 7,
            PARAM_TYPE_NONE: 8,
            PARAM_TYPE_BOOL: 9,
          },
        }),
      ),
    ),
    hasDefault: S.optional(S.Boolean.pipe(T.ProtoField({ n: 3, t: "bool" }))),
    stringDefault: S.optional(
      S.String.pipe(T.ProtoField({ n: 4, t: "string" })),
    ),
    intDefault: S.optional(S.String.pipe(T.ProtoField({ n: 5, t: "int64" }))),
    pickleDefault: S.optional(
      S.String.pipe(T.ProtoField({ n: 6, t: "bytes" })),
    ),
    bytesDefault: S.optional(S.String.pipe(T.ProtoField({ n: 7, t: "bytes" }))),
    boolDefault: S.optional(S.Boolean.pipe(T.ProtoField({ n: 9, t: "bool" }))),
    fullType: S.optional(
      GenericPayloadType.pipe(T.ProtoField({ n: 8, t: "message" })),
    ),
  }),
).annotate({
  identifier: "ClassParameterSpec",
}) as any as S.Schema<ClassParameterSpec>;

export type ClassParameterSpecList = Array<ClassParameterSpec>;
export const ClassParameterSpecList = /*@__PURE__*/ S.Array(
  ClassParameterSpec,
) as any as S.Schema<ClassParameterSpecList>;

export interface ClassParameterInfo {
  /** new format using api.FunctionParameterSet */
  format?: ClassParameterInfoParameterSerializationFormat | (string & {});
  schema?: ClassParameterSpecList;
}
export const ClassParameterInfo = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    format: S.optional(
      ClassParameterInfoParameterSerializationFormat.pipe(
        T.ProtoField({
          n: 1,
          t: "enum",
          e: {
            PARAM_SERIALIZATION_FORMAT_UNSPECIFIED: 0,
            PARAM_SERIALIZATION_FORMAT_PICKLE: 1,
            PARAM_SERIALIZATION_FORMAT_PROTO: 2,
          },
        }),
      ),
    ),
    schema: S.optional(
      ClassParameterSpecList.pipe(
        T.ProtoField({ n: 2, t: "message", rep: true }),
      ),
    ),
  }),
).annotate({
  identifier: "ClassParameterInfo",
}) as any as S.Schema<ClassParameterInfo>;

export type FunctionHandleMetadataMap = {
  [key: string]: FunctionHandleMetadata | undefined;
};
export const FunctionHandleMetadataMap = /*@__PURE__*/ S.Record(
  S.String,
  S.suspend(() => FunctionHandleMetadata),
) as any as S.Schema<FunctionHandleMetadataMap>;

export type FunctionSchemaFunctionSchemaType =
  | "FUNCTION_SCHEMA_UNSPECIFIED"
  | "FUNCTION_SCHEMA_V1";
export const FunctionSchemaFunctionSchemaType = S.String;

export interface FunctionSchema {
  schemaType?: FunctionSchemaFunctionSchemaType | (string & {});
  /** allows easy disambiguation between empty schema and no schema collection etc. */
  arguments?: ClassParameterSpecList;
  returnType?: GenericPayloadType;
}
export const FunctionSchema = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    schemaType: S.optional(
      FunctionSchemaFunctionSchemaType.pipe(
        T.ProtoField({
          n: 1,
          t: "enum",
          e: { FUNCTION_SCHEMA_UNSPECIFIED: 0, FUNCTION_SCHEMA_V1: 1 },
        }),
      ),
    ),
    arguments: S.optional(
      ClassParameterSpecList.pipe(
        T.ProtoField({ n: 2, t: "message", rep: true }),
      ),
    ),
    returnType: S.optional(
      GenericPayloadType.pipe(T.ProtoField({ n: 3, t: "message" })),
    ),
  }),
).annotate({ identifier: "FunctionSchema" }) as any as S.Schema<FunctionSchema>;

export type StringList = Array<string>;
export const StringList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<StringList>;

/** Which data format a binary message is encoded with. */
export type DataFormat =
  | "DATA_FORMAT_UNSPECIFIED"
  | "DATA_FORMAT_PICKLE"
  | "DATA_FORMAT_ASGI"
  | "DATA_FORMAT_GENERATOR_DONE"
  | "DATA_FORMAT_CBOR";
export const DataFormat = S.String;

export type DataFormatList = Array<DataFormat | (string & {})>;
export const DataFormatList = /*@__PURE__*/ S.Array(
  DataFormat,
) as any as S.Schema<DataFormatList>;

export interface FunctionHandleMetadata {
  /** contains all the info about a function that is needed to trigger the right behaviour when using a FunctionHandler. Notably excludes things purely used for *executing* the function in a container entrypoint Should be a subset and use IDs/types from `Function` above */
  functionName?: string;
  functionType?: FunctionFunctionType | (string & {});
  webUrl?: string;
  isMethod?: boolean;
  useFunctionId?: string;
  /** used for methods */
  useMethodName?: string;
  /** used for methods */
  definitionId?: string;
  classParameterInfo?: ClassParameterInfo;
  /** Mapping of method names to their metadata, only non-empty for class service functions */
  methodHandleMetadata?: FunctionHandleMetadataMap;
  functionSchema?: FunctionSchema;
  inputPlaneUrl?: string;
  inputPlaneRegion?: string;
  /** Use optional to ensure unset values default to None instead of 0 */
  maxObjectSizeBytes?: string;
  maxAsyncObjectSizeBytes?: string;
  ExperimentalFlashUrls?: StringList;
  /** (Optional) urls for flash services */
  supportedInputFormats?: DataFormatList;
  supportedOutputFormats?: DataFormatList;
  appId?: string;
  /** The base Function ID for a variant, or the Function's own ID otherwise. */
  baseFunctionId?: string;
}
export const FunctionHandleMetadata = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    functionName: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "string" })),
    ),
    functionType: S.optional(
      FunctionFunctionType.pipe(
        T.ProtoField({
          n: 8,
          t: "enum",
          e: {
            FUNCTION_TYPE_UNSPECIFIED: 0,
            FUNCTION_TYPE_GENERATOR: 1,
            FUNCTION_TYPE_FUNCTION: 2,
          },
        }),
      ),
    ),
    webUrl: S.optional(S.String.pipe(T.ProtoField({ n: 28, t: "string" }))),
    isMethod: S.optional(S.Boolean.pipe(T.ProtoField({ n: 39, t: "bool" }))),
    useFunctionId: S.optional(
      S.String.pipe(T.ProtoField({ n: 40, t: "string" })),
    ),
    useMethodName: S.optional(
      S.String.pipe(T.ProtoField({ n: 41, t: "string" })),
    ),
    definitionId: S.optional(
      S.String.pipe(T.ProtoField({ n: 42, t: "string" })),
    ),
    classParameterInfo: S.optional(
      ClassParameterInfo.pipe(T.ProtoField({ n: 43, t: "message" })),
    ),
    methodHandleMetadata: S.optional(
      FunctionHandleMetadataMap.pipe(
        T.ProtoField({ n: 44, t: "map", k: "string", v: { t: "message" } }),
      ),
    ),
    functionSchema: S.optional(
      FunctionSchema.pipe(T.ProtoField({ n: 45, t: "message" })),
    ),
    inputPlaneUrl: S.optional(
      S.String.pipe(T.ProtoField({ n: 46, t: "string" })),
    ),
    inputPlaneRegion: S.optional(
      S.String.pipe(T.ProtoField({ n: 47, t: "string" })),
    ),
    maxObjectSizeBytes: S.optional(
      S.String.pipe(T.ProtoField({ n: 48, t: "uint64" })),
    ),
    maxAsyncObjectSizeBytes: S.optional(
      S.String.pipe(T.ProtoField({ n: 53, t: "uint64" })),
    ),
    ExperimentalFlashUrls: S.optional(
      StringList.pipe(T.ProtoField({ n: 49, t: "string", rep: true })),
    ),
    supportedInputFormats: S.optional(
      DataFormatList.pipe(
        T.ProtoField({
          n: 50,
          t: "enum",
          e: {
            DATA_FORMAT_UNSPECIFIED: 0,
            DATA_FORMAT_PICKLE: 1,
            DATA_FORMAT_ASGI: 2,
            DATA_FORMAT_GENERATOR_DONE: 3,
            DATA_FORMAT_CBOR: 4,
          },
          rep: true,
        }),
      ),
    ),
    supportedOutputFormats: S.optional(
      DataFormatList.pipe(
        T.ProtoField({
          n: 51,
          t: "enum",
          e: {
            DATA_FORMAT_UNSPECIFIED: 0,
            DATA_FORMAT_PICKLE: 1,
            DATA_FORMAT_ASGI: 2,
            DATA_FORMAT_GENERATOR_DONE: 3,
            DATA_FORMAT_CBOR: 4,
          },
          rep: true,
        }),
      ),
    ),
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 52, t: "string" }))),
    baseFunctionId: S.optional(
      S.String.pipe(T.ProtoField({ n: 54, t: "string" })),
    ),
  }),
).annotate({
  identifier: "FunctionHandleMetadata",
}) as any as S.Schema<FunctionHandleMetadata>;

export interface ClassMethod {
  functionName?: string;
  functionId?: string;
  /** Class methods need to hydrate all functions on the class */
  functionHandleMetadata?: FunctionHandleMetadata;
}
export const ClassMethod = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    functionName: S.optional(
      S.String.pipe(T.ProtoField({ n: 1, t: "string" })),
    ),
    functionId: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    functionHandleMetadata: S.optional(
      FunctionHandleMetadata.pipe(T.ProtoField({ n: 3, t: "message" })),
    ),
  }),
).annotate({ identifier: "ClassMethod" }) as any as S.Schema<ClassMethod>;

export type ClassMethodList = Array<ClassMethod>;
export const ClassMethodList = /*@__PURE__*/ S.Array(
  ClassMethod,
) as any as S.Schema<ClassMethodList>;

export interface CreateClassRequest {
  appId?: string;
  existingClassId?: string;
  methods?: ClassMethodList;
  /** removed class_function_id */
  onlyClassFunction?: boolean;
}
export const CreateClassRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    existingClassId: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "string" })),
    ),
    methods: S.optional(
      ClassMethodList.pipe(T.ProtoField({ n: 3, t: "message", rep: true })),
    ),
    onlyClassFunction: S.optional(
      S.Boolean.pipe(T.ProtoField({ n: 5, t: "bool" })),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/ClassCreate",
      code: 200,
    }),
  ),
).annotate({
  identifier: "CreateClassRequest",
}) as any as S.Schema<CreateClassRequest>;

export interface ClassHandleMetadata {
  methods?: ClassMethodList;
  classFunctionId?: string;
  classFunctionMetadata?: FunctionHandleMetadata;
}
export const ClassHandleMetadata = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    methods: S.optional(
      ClassMethodList.pipe(T.ProtoField({ n: 1, t: "message", rep: true })),
    ),
    classFunctionId: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "string" })),
    ),
    classFunctionMetadata: S.optional(
      FunctionHandleMetadata.pipe(T.ProtoField({ n: 3, t: "message" })),
    ),
  }),
).annotate({
  identifier: "ClassHandleMetadata",
}) as any as S.Schema<ClassHandleMetadata>;

export interface CreateClassResponse {
  classId?: string;
  handleMetadata?: ClassHandleMetadata;
}
export const CreateClassResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    classId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    handleMetadata: S.optional(
      ClassHandleMetadata.pipe(T.ProtoField({ n: 2, t: "message" })),
    ),
  }),
).annotate({
  identifier: "CreateClassResponse",
}) as any as S.Schema<CreateClassResponse>;

export interface GetClassRequest {
  appName?: string;
  objectTag?: string;
  /** removed namespace */
  environmentName?: string;
  /** workspace_name */
  onlyClassFunction?: boolean;
  /** True starting with 0.67.x clients, which don't create method placeholder functions */
  appVersion?: number;
}
export const GetClassRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appName: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    objectTag: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    environmentName: S.optional(
      S.String.pipe(T.ProtoField({ n: 4, t: "string" })),
    ),
    onlyClassFunction: S.optional(
      S.Boolean.pipe(T.ProtoField({ n: 10, t: "bool" })),
    ),
    appVersion: S.optional(S.Number.pipe(T.ProtoField({ n: 11, t: "int32" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/ClassGet",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetClassRequest",
}) as any as S.Schema<GetClassRequest>;

export type WarningWarningType =
  | "WARNING_TYPE_UNSPECIFIED"
  | "WARNING_TYPE_CLIENT_DEPRECATION"
  | "WARNING_TYPE_RESOURCE_LIMIT"
  | "WARNING_TYPE_FUNCTION_CONFIGURATION";
export const WarningWarningType = S.String;

export interface Warning {
  type?: WarningWarningType;
  message?: string;
}
export const Warning = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.optional(
      WarningWarningType.pipe(
        T.ProtoField({
          n: 1,
          t: "enum",
          e: {
            WARNING_TYPE_UNSPECIFIED: 0,
            WARNING_TYPE_CLIENT_DEPRECATION: 1,
            WARNING_TYPE_RESOURCE_LIMIT: 2,
            WARNING_TYPE_FUNCTION_CONFIGURATION: 3,
          },
        }),
      ),
    ),
    message: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
  }),
).annotate({ identifier: "Warning" }) as any as S.Schema<Warning>;

export type WarningList = Array<Warning>;
export const WarningList = /*@__PURE__*/ S.Array(
  Warning,
) as any as S.Schema<WarningList>;

export interface GetClassResponse {
  classId?: string;
  handleMetadata?: ClassHandleMetadata;
  serverWarnings?: WarningList;
}
export const GetClassResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    classId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    handleMetadata: S.optional(
      ClassHandleMetadata.pipe(T.ProtoField({ n: 2, t: "message" })),
    ),
    serverWarnings: S.optional(
      WarningList.pipe(T.ProtoField({ n: 3, t: "message", rep: true })),
    ),
  }),
).annotate({
  identifier: "GetClassResponse",
}) as any as S.Schema<GetClassResponse>;

export type CreateClassError = ModalOpError;
/** Classes */
export const createClass: API.OperationMethod<
  CreateClassRequest,
  CreateClassResponse,
  CreateClassError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateClassRequest,
  output: CreateClassResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type GetClassError = ModalOpError;
export const getClass: API.OperationMethod<
  GetClassRequest,
  GetClassResponse,
  GetClassError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetClassRequest,
  output: GetClassResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));
