// AUTO-GENERATED by scripts/generate.ts from .generated-specs (modal_proto → smithy). Do not edit.
import * as S from "@rikalabs/distilled-core/schema";
import * as API from "@rikalabs/distilled-core/api";
import * as T from "../traits.ts";
import {
  ModalProtocol,
  type ModalOpError,
  type ModalOpContext,
} from "../protocol.ts";
import { UnknownModalError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { ModalOpError, ModalOpContext };

export interface ClientHelloRequest {}
export const ClientHelloRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/ClientHello",
      code: 200,
    }),
  ),
).annotate({
  identifier: "ClientHelloRequest",
}) as any as S.Schema<ClientHelloRequest>;

export type WarningWarningType =
  | "WARNING_TYPE_UNSPECIFIED"
  | "WARNING_TYPE_CLIENT_DEPRECATION"
  | "WARNING_TYPE_RESOURCE_LIMIT"
  | "WARNING_TYPE_FUNCTION_CONFIGURATION";
export const WarningWarningType = S.String;

export interface Warning {
  type?: WarningWarningType;
  message?: string;
}
export const Warning = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.optional(
      WarningWarningType.pipe(
        T.ProtoField({
          n: 1,
          t: "enum",
          e: {
            WARNING_TYPE_UNSPECIFIED: 0,
            WARNING_TYPE_CLIENT_DEPRECATION: 1,
            WARNING_TYPE_RESOURCE_LIMIT: 2,
            WARNING_TYPE_FUNCTION_CONFIGURATION: 3,
          },
        }),
      ),
    ),
    message: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
  }),
).annotate({ identifier: "Warning" }) as any as S.Schema<Warning>;

export type WarningList = Array<Warning>;
export const WarningList = /*@__PURE__*/ S.Array(
  Warning,
) as any as S.Schema<WarningList>;

export interface ClientHelloResponse {
  warning?: string;
  imageBuilderVersion?: string;
  /** Deprecated, no longer used in client */
  serverWarnings?: WarningList;
}
export const ClientHelloResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    warning: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    imageBuilderVersion: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "string" })),
    ),
    serverWarnings: S.optional(
      WarningList.pipe(T.ProtoField({ n: 4, t: "message", rep: true })),
    ),
  }),
).annotate({
  identifier: "ClientHelloResponse",
}) as any as S.Schema<ClientHelloResponse>;

export type ClientHelloError = ModalOpError;
/** Clients */
export const clientHello: API.OperationMethod<
  ClientHelloRequest,
  ClientHelloResponse,
  ClientHelloError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ClientHelloRequest,
  output: ClientHelloResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));
