// AUTO-GENERATED by scripts/generate.ts from .generated-specs (modal_proto → smithy). Do not edit.
import * as S from "@rikalabs/distilled-core/schema";
import * as API from "@rikalabs/distilled-core/api";
import * as T from "../traits.ts";
import {
  ModalProtocol,
  type ModalOpError,
  type ModalOpContext,
} from "../protocol.ts";
import { UnknownModalError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { ModalOpError, ModalOpContext };

export interface GetClusterRequest {
  clusterId?: string;
}
export const GetClusterRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    clusterId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/ClusterGet",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetClusterRequest",
}) as any as S.Schema<GetClusterRequest>;

export type StringList = Array<string>;
export const StringList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<StringList>;

export interface ClusterStats {
  appId?: string;
  taskIds?: StringList;
  clusterId?: string;
  startedAt?: number;
}
export const ClusterStats = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    taskIds: S.optional(
      StringList.pipe(T.ProtoField({ n: 2, t: "string", rep: true })),
    ),
    clusterId: S.optional(S.String.pipe(T.ProtoField({ n: 3, t: "string" }))),
    startedAt: S.optional(S.Number.pipe(T.ProtoField({ n: 4, t: "double" }))),
  }),
).annotate({ identifier: "ClusterStats" }) as any as S.Schema<ClusterStats>;

export interface GetClusterResponse {
  cluster?: ClusterStats;
}
export const GetClusterResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    cluster: S.optional(
      ClusterStats.pipe(T.ProtoField({ n: 1, t: "message" })),
    ),
  }),
).annotate({
  identifier: "GetClusterResponse",
}) as any as S.Schema<GetClusterResponse>;

export interface ListClusterRequest {
  environmentName?: string;
}
export const ListClusterRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    environmentName: S.optional(
      S.String.pipe(T.ProtoField({ n: 1, t: "string" })),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/ClusterList",
      code: 200,
    }),
  ),
).annotate({
  identifier: "ListClusterRequest",
}) as any as S.Schema<ListClusterRequest>;

export type ClusterStatsList = Array<ClusterStats>;
export const ClusterStatsList = /*@__PURE__*/ S.Array(
  ClusterStats,
) as any as S.Schema<ClusterStatsList>;

export interface ListClusterResponse {
  clusters?: ClusterStatsList;
}
export const ListClusterResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    clusters: S.optional(
      ClusterStatsList.pipe(T.ProtoField({ n: 1, t: "message", rep: true })),
    ),
  }),
).annotate({
  identifier: "ListClusterResponse",
}) as any as S.Schema<ListClusterResponse>;

export type GetClusterError = ModalOpError;
/** Clusters */
export const getCluster: API.OperationMethod<
  GetClusterRequest,
  GetClusterResponse,
  GetClusterError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetClusterRequest,
  output: GetClusterResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type ListClusterError = ModalOpError;
export const listCluster: API.OperationMethod<
  ListClusterRequest,
  ListClusterResponse,
  ListClusterError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListClusterRequest,
  output: ListClusterResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));
