// AUTO-GENERATED by scripts/generate.ts from .generated-specs (modal_proto → smithy). Do not edit.
import * as S from "@rikalabs/distilled-core/schema";
import * as API from "@rikalabs/distilled-core/api";
import * as T from "../traits.ts";
import {
  ModalProtocol,
  type ModalOpError,
  type ModalOpContext,
} from "../protocol.ts";
import { UnknownModalError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { ModalOpError, ModalOpContext };

export interface CreateDomainRequest {
  domainName?: string;
}
export const CreateDomainRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    domainName: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/DomainCreate",
      code: 200,
    }),
  ),
).annotate({
  identifier: "CreateDomainRequest",
}) as any as S.Schema<CreateDomainRequest>;

/** now unused internal experimental values */
export type DNSRecordType =
  | "DNS_RECORD_TYPE_A"
  | "DNS_RECORD_TYPE_TXT"
  | "DNS_RECORD_TYPE_CNAME";
export const DNSRecordType = S.String;

export interface DNSRecord {
  type?: DNSRecordType;
  name?: string;
  value?: string;
}
export const DNSRecord = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.optional(
      DNSRecordType.pipe(
        T.ProtoField({
          n: 1,
          t: "enum",
          e: {
            DNS_RECORD_TYPE_A: 0,
            DNS_RECORD_TYPE_TXT: 1,
            DNS_RECORD_TYPE_CNAME: 2,
          },
        }),
      ),
    ),
    name: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    value: S.optional(S.String.pipe(T.ProtoField({ n: 3, t: "string" }))),
  }),
).annotate({ identifier: "DNSRecord" }) as any as S.Schema<DNSRecord>;

export type DNSRecordList = Array<DNSRecord>;
export const DNSRecordList = /*@__PURE__*/ S.Array(
  DNSRecord,
) as any as S.Schema<DNSRecordList>;

export interface CreateDomainResponse {
  domainId?: string;
  dnsRecords?: DNSRecordList;
}
export const CreateDomainResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    domainId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    dnsRecords: S.optional(
      DNSRecordList.pipe(T.ProtoField({ n: 2, t: "message", rep: true })),
    ),
  }),
).annotate({
  identifier: "CreateDomainResponse",
}) as any as S.Schema<CreateDomainResponse>;

export interface ListDomainRequest {}
export const ListDomainRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/DomainList",
      code: 200,
    }),
  ),
).annotate({
  identifier: "ListDomainRequest",
}) as any as S.Schema<ListDomainRequest>;

export type CertificateStatus =
  | "CERTIFICATE_STATUS_PENDING"
  | "CERTIFICATE_STATUS_ISSUED"
  | "CERTIFICATE_STATUS_FAILED"
  | "CERTIFICATE_STATUS_REVOKED";
export const CertificateStatus = S.String;

export interface Domain {
  domainId?: string;
  domainName?: string;
  createdAt?: number;
  certificateStatus?: CertificateStatus;
  dnsRecords?: DNSRecordList;
}
export const Domain = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    domainId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    domainName: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    createdAt: S.optional(S.Number.pipe(T.ProtoField({ n: 3, t: "double" }))),
    certificateStatus: S.optional(
      CertificateStatus.pipe(
        T.ProtoField({
          n: 4,
          t: "enum",
          e: {
            CERTIFICATE_STATUS_PENDING: 0,
            CERTIFICATE_STATUS_ISSUED: 1,
            CERTIFICATE_STATUS_FAILED: 2,
            CERTIFICATE_STATUS_REVOKED: 3,
          },
        }),
      ),
    ),
    dnsRecords: S.optional(
      DNSRecordList.pipe(T.ProtoField({ n: 5, t: "message", rep: true })),
    ),
  }),
).annotate({ identifier: "Domain" }) as any as S.Schema<Domain>;

export type DomainList2 = Array<Domain>;
export const DomainList2 = /*@__PURE__*/ S.Array(
  Domain,
) as any as S.Schema<DomainList2>;

export interface ListDomainResponse {
  domains?: DomainList2;
}
export const ListDomainResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    domains: S.optional(
      DomainList2.pipe(T.ProtoField({ n: 1, t: "message", rep: true })),
    ),
  }),
).annotate({
  identifier: "ListDomainResponse",
}) as any as S.Schema<ListDomainResponse>;

export interface VerifyDomainCertificateRequest {
  domainId?: string;
}
export const VerifyDomainCertificateRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    domainId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/DomainCertificateVerify",
      code: 200,
    }),
  ),
).annotate({
  identifier: "VerifyDomainCertificateRequest",
}) as any as S.Schema<VerifyDomainCertificateRequest>;

export interface VerifyDomainCertificateResponse {
  domain?: Domain;
}
export const VerifyDomainCertificateResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    domain: S.optional(Domain.pipe(T.ProtoField({ n: 1, t: "message" }))),
  }),
).annotate({
  identifier: "VerifyDomainCertificateResponse",
}) as any as S.Schema<VerifyDomainCertificateResponse>;

export type CreateDomainError = ModalOpError;
export const createDomain: API.OperationMethod<
  CreateDomainRequest,
  CreateDomainResponse,
  CreateDomainError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateDomainRequest,
  output: CreateDomainResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type ListDomainError = ModalOpError;
export const listDomain: API.OperationMethod<
  ListDomainRequest,
  ListDomainResponse,
  ListDomainError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListDomainRequest,
  output: ListDomainResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type VerifyDomainCertificateError = ModalOpError;
/** Domains */
export const verifyDomainCertificate: API.OperationMethod<
  VerifyDomainCertificateRequest,
  VerifyDomainCertificateResponse,
  VerifyDomainCertificateError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: VerifyDomainCertificateRequest,
  output: VerifyDomainCertificateResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));
