// AUTO-GENERATED by scripts/generate.ts from .generated-specs (modal_proto → smithy). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as T from "../traits.ts";
import {
  ModalProtocol,
  type ModalOpError,
  type ModalOpContext,
} from "../protocol.ts";
import { UnknownModalError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { ModalOpError, ModalOpContext };

export type StringList = Array<string>;
export const StringList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<StringList>;

/** google.protobuf.Empty as a nested field. */
export interface GoogleProtobufEmpty {}
export const GoogleProtobufEmpty = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "GoogleProtobufEmpty",
}) as any as S.Schema<GoogleProtobufEmpty>;

export interface EndpointComputeRegionSpecExplicitRegions {
  regions?: StringList;
}
export const EndpointComputeRegionSpecExplicitRegions = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      regions: S.optional(
        StringList.pipe(T.ProtoField({ n: 1, t: "string", rep: true })),
      ),
    }),
).annotate({
  identifier: "EndpointComputeRegionSpecExplicitRegions",
}) as any as S.Schema<EndpointComputeRegionSpecExplicitRegions>;

export interface EndpointComputeRegionSpec {
  auto?: GoogleProtobufEmpty;
  colocated?: GoogleProtobufEmpty;
  explicit?: EndpointComputeRegionSpecExplicitRegions;
}
export const EndpointComputeRegionSpec = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    auto: S.optional(
      GoogleProtobufEmpty.pipe(T.ProtoField({ n: 1, t: "wkt", w: "Empty" })),
    ),
    colocated: S.optional(
      GoogleProtobufEmpty.pipe(T.ProtoField({ n: 2, t: "wkt", w: "Empty" })),
    ),
    explicit: S.optional(
      EndpointComputeRegionSpecExplicitRegions.pipe(
        T.ProtoField({ n: 3, t: "message" }),
      ),
    ),
  }),
).annotate({
  identifier: "EndpointComputeRegionSpec",
}) as any as S.Schema<EndpointComputeRegionSpec>;

export interface EndpointHuggingFaceModelSource {
  repoId?: string;
  revision?: string;
  huggingfaceToken?: string;
}
export const EndpointHuggingFaceModelSource = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    repoId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    revision: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    huggingfaceToken: S.optional(
      S.String.pipe(T.ProtoField({ n: 3, t: "string" })),
    ),
  }),
).annotate({
  identifier: "EndpointHuggingFaceModelSource",
}) as any as S.Schema<EndpointHuggingFaceModelSource>;

export interface EndpointModalVolumeModelSource {
  volumeId?: string;
  modelPath?: string;
}
export const EndpointModalVolumeModelSource = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    volumeId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    modelPath: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
  }),
).annotate({
  identifier: "EndpointModalVolumeModelSource",
}) as any as S.Schema<EndpointModalVolumeModelSource>;

export interface EndpointCustomModelSource {
  baseModelRepoId?: string;
  huggingface?: EndpointHuggingFaceModelSource;
  modalVolume?: EndpointModalVolumeModelSource;
}
export const EndpointCustomModelSource = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    baseModelRepoId: S.optional(
      S.String.pipe(T.ProtoField({ n: 1, t: "string" })),
    ),
    huggingface: S.optional(
      EndpointHuggingFaceModelSource.pipe(T.ProtoField({ n: 2, t: "message" })),
    ),
    modalVolume: S.optional(
      EndpointModalVolumeModelSource.pipe(T.ProtoField({ n: 3, t: "message" })),
    ),
  }),
).annotate({
  identifier: "EndpointCustomModelSource",
}) as any as S.Schema<EndpointCustomModelSource>;

export interface EndpointModelSource {
  baseModelRepoId?: string;
  custom?: EndpointCustomModelSource;
}
export const EndpointModelSource = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    baseModelRepoId: S.optional(
      S.String.pipe(T.ProtoField({ n: 1, t: "string" })),
    ),
    custom: S.optional(
      EndpointCustomModelSource.pipe(T.ProtoField({ n: 2, t: "message" })),
    ),
  }),
).annotate({
  identifier: "EndpointModelSource",
}) as any as S.Schema<EndpointModelSource>;

export type EndpointApiSurface =
  | "ENDPOINT_API_SURFACE_UNSPECIFIED"
  | "ENDPOINT_API_SURFACE_OPENAI_CHAT_COMPLETIONS"
  | "ENDPOINT_API_SURFACE_OPENAI_RESPONSES"
  | "ENDPOINT_API_SURFACE_ANTHROPIC_MESSAGES";
export const EndpointApiSurface = S.String;

export type EndpointApiSurfaceList = Array<EndpointApiSurface | (string & {})>;
export const EndpointApiSurfaceList = /*@__PURE__*/ S.Array(
  EndpointApiSurface,
) as any as S.Schema<EndpointApiSurfaceList>;

export type EndpointInputModality =
  | "ENDPOINT_INPUT_MODALITY_UNSPECIFIED"
  | "ENDPOINT_INPUT_MODALITY_TEXT"
  | "ENDPOINT_INPUT_MODALITY_IMAGE"
  | "ENDPOINT_INPUT_MODALITY_AUDIO";
export const EndpointInputModality = S.String;

export type EndpointInputModalityList = Array<
  EndpointInputModality | (string & {})
>;
export const EndpointInputModalityList = /*@__PURE__*/ S.Array(
  EndpointInputModality,
) as any as S.Schema<EndpointInputModalityList>;

export type EndpointServingMode =
  | "ENDPOINT_SERVING_MODE_UNSPECIFIED"
  | "ENDPOINT_SERVING_MODE_DEDICATED"
  | "ENDPOINT_SERVING_MODE_SHARED";
export const EndpointServingMode = S.String;

export interface CreateEndpointRequest {
  name?: string;
  description?: string;
  proxyRegions?: StringList;
  computeRegion?: EndpointComputeRegionSpec;
  model?: EndpointModelSource;
  apiSurfaces?: EndpointApiSurfaceList;
  inputModalities?: EndpointInputModalityList;
  environmentName?: string;
  unauthenticated?: boolean;
  servingMode?: EndpointServingMode | (string & {});
}
export const CreateEndpointRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    description: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    proxyRegions: S.optional(
      StringList.pipe(T.ProtoField({ n: 3, t: "string", rep: true })),
    ),
    computeRegion: S.optional(
      EndpointComputeRegionSpec.pipe(T.ProtoField({ n: 4, t: "message" })),
    ),
    model: S.optional(
      EndpointModelSource.pipe(T.ProtoField({ n: 5, t: "message" })),
    ),
    apiSurfaces: S.optional(
      EndpointApiSurfaceList.pipe(
        T.ProtoField({
          n: 6,
          t: "enum",
          e: {
            ENDPOINT_API_SURFACE_UNSPECIFIED: 0,
            ENDPOINT_API_SURFACE_OPENAI_CHAT_COMPLETIONS: 1,
            ENDPOINT_API_SURFACE_OPENAI_RESPONSES: 2,
            ENDPOINT_API_SURFACE_ANTHROPIC_MESSAGES: 3,
          },
          rep: true,
        }),
      ),
    ),
    inputModalities: S.optional(
      EndpointInputModalityList.pipe(
        T.ProtoField({
          n: 7,
          t: "enum",
          e: {
            ENDPOINT_INPUT_MODALITY_UNSPECIFIED: 0,
            ENDPOINT_INPUT_MODALITY_TEXT: 1,
            ENDPOINT_INPUT_MODALITY_IMAGE: 2,
            ENDPOINT_INPUT_MODALITY_AUDIO: 3,
          },
          rep: true,
        }),
      ),
    ),
    environmentName: S.optional(
      S.String.pipe(T.ProtoField({ n: 8, t: "string" })),
    ),
    unauthenticated: S.optional(
      S.Boolean.pipe(T.ProtoField({ n: 9, t: "bool" })),
    ),
    servingMode: S.optional(
      EndpointServingMode.pipe(
        T.ProtoField({
          n: 10,
          t: "enum",
          e: {
            ENDPOINT_SERVING_MODE_UNSPECIFIED: 0,
            ENDPOINT_SERVING_MODE_DEDICATED: 1,
            ENDPOINT_SERVING_MODE_SHARED: 2,
          },
        }),
      ),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/EndpointCreate",
      code: 200,
    }),
  ),
).annotate({
  identifier: "CreateEndpointRequest",
}) as any as S.Schema<CreateEndpointRequest>;

export interface CreateEndpointResponse {
  endpointId?: string;
  endpointPageUrl?: string;
  name?: string;
}
export const CreateEndpointResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    endpointId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    endpointPageUrl: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "string" })),
    ),
    name: S.optional(S.String.pipe(T.ProtoField({ n: 3, t: "string" }))),
  }),
).annotate({
  identifier: "CreateEndpointResponse",
}) as any as S.Schema<CreateEndpointResponse>;

export interface EndpointGetByNameRequest {
  name?: string;
  environmentName?: string;
}
export const EndpointGetByNameRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    environmentName: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "string" })),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/EndpointGetByName",
      code: 200,
    }),
  ),
).annotate({
  identifier: "EndpointGetByNameRequest",
}) as any as S.Schema<EndpointGetByNameRequest>;

export interface EndpointGetByNameResponse {
  endpointId?: string;
  environmentName?: string;
}
export const EndpointGetByNameResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    endpointId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    environmentName: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "string" })),
    ),
  }),
).annotate({
  identifier: "EndpointGetByNameResponse",
}) as any as S.Schema<EndpointGetByNameResponse>;

export interface EndpointGetLifecycleRequest {
  endpointId?: string;
}
export const EndpointGetLifecycleRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    endpointId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/EndpointGetLifecycle",
      code: 200,
    }),
  ),
).annotate({
  identifier: "EndpointGetLifecycleRequest",
}) as any as S.Schema<EndpointGetLifecycleRequest>;

export type EndpointLifecycleStatus =
  | "ENDPOINT_LIFECYCLE_STATUS_UNSPECIFIED"
  | "ENDPOINT_LIFECYCLE_STATUS_ACTIVE"
  | "ENDPOINT_LIFECYCLE_STATUS_STOPPED";
export const EndpointLifecycleStatus = S.String;

export interface EndpointLifecycle {
  status?: EndpointLifecycleStatus;
  createdAt?: number;
  createdBy?: string;
  /** User or service user name */
  stoppedAt?: number;
  /** Unset when Endpoint is active */
  stoppedBy?: string;
  /** User or service user name */
  environmentName?: string;
}
export const EndpointLifecycle = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    status: S.optional(
      EndpointLifecycleStatus.pipe(
        T.ProtoField({
          n: 1,
          t: "enum",
          e: {
            ENDPOINT_LIFECYCLE_STATUS_UNSPECIFIED: 0,
            ENDPOINT_LIFECYCLE_STATUS_ACTIVE: 1,
            ENDPOINT_LIFECYCLE_STATUS_STOPPED: 2,
          },
        }),
      ),
    ),
    createdAt: S.optional(S.Number.pipe(T.ProtoField({ n: 2, t: "double" }))),
    createdBy: S.optional(S.String.pipe(T.ProtoField({ n: 3, t: "string" }))),
    stoppedAt: S.optional(S.Number.pipe(T.ProtoField({ n: 4, t: "double" }))),
    stoppedBy: S.optional(S.String.pipe(T.ProtoField({ n: 5, t: "string" }))),
    environmentName: S.optional(
      S.String.pipe(T.ProtoField({ n: 6, t: "string" })),
    ),
  }),
).annotate({
  identifier: "EndpointLifecycle",
}) as any as S.Schema<EndpointLifecycle>;

export interface EndpointGetLifecycleResponse {
  lifecycle?: EndpointLifecycle;
}
export const EndpointGetLifecycleResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    lifecycle: S.optional(
      EndpointLifecycle.pipe(T.ProtoField({ n: 1, t: "message" })),
    ),
  }),
).annotate({
  identifier: "EndpointGetLifecycleResponse",
}) as any as S.Schema<EndpointGetLifecycleResponse>;

export interface ListPagination {
  maxObjects?: number;
  createdBefore?: number;
}
export const ListPagination = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    maxObjects: S.optional(S.Number.pipe(T.ProtoField({ n: 1, t: "int32" }))),
    createdBefore: S.optional(
      S.Number.pipe(T.ProtoField({ n: 2, t: "double" })),
    ),
  }),
).annotate({ identifier: "ListPagination" }) as any as S.Schema<ListPagination>;

export interface ListEndpointRequest {
  environmentName?: string;
  pagination?: ListPagination;
}
export const ListEndpointRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    environmentName: S.optional(
      S.String.pipe(T.ProtoField({ n: 1, t: "string" })),
    ),
    pagination: S.optional(
      ListPagination.pipe(T.ProtoField({ n: 2, t: "message" })),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/EndpointList",
      code: 200,
    }),
  ),
).annotate({
  identifier: "ListEndpointRequest",
}) as any as S.Schema<ListEndpointRequest>;

export interface CreationInfo {
  /** This message is used in metadata for resource objects like Dict, Queue, Volume, etc. */
  createdAt?: number;
  /** Timestamp of resource creation */
  createdBy?: string;
}
export const CreationInfo = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    createdAt: S.optional(S.Number.pipe(T.ProtoField({ n: 1, t: "double" }))),
    createdBy: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
  }),
).annotate({ identifier: "CreationInfo" }) as any as S.Schema<CreationInfo>;

export interface EndpointMetadata {
  name?: string;
  creationInfo?: CreationInfo;
}
export const EndpointMetadata = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    creationInfo: S.optional(
      CreationInfo.pipe(T.ProtoField({ n: 2, t: "message" })),
    ),
  }),
).annotate({
  identifier: "EndpointMetadata",
}) as any as S.Schema<EndpointMetadata>;

/** NOTE: make sure to update the frontend if we add a new state here https://github.com/modal-labs/modal/blob/main/frontend/src/routes/(dashboard)/%5B%5Bworkspace%5D%5D/apps/+page.svelte#L95 */
export type AppState =
  | "APP_STATE_UNSPECIFIED"
  | "APP_STATE_EPHEMERAL"
  | "APP_STATE_DETACHED"
  | "APP_STATE_DEPLOYED"
  | "APP_STATE_STOPPING"
  | "APP_STATE_STOPPED"
  | "APP_STATE_INITIALIZING"
  | "APP_STATE_DISABLED"
  | "APP_STATE_DETACHED_DISCONNECTED"
  | "APP_STATE_DERIVED";
export const AppState = S.String;

export type EndpointProvisioningStatus =
  | "ENDPOINT_PROVISIONING_STATUS_UNSPECIFIED"
  | "ENDPOINT_PROVISIONING_STATUS_PENDING"
  | "ENDPOINT_PROVISIONING_STATUS_RUNNING"
  | "ENDPOINT_PROVISIONING_STATUS_SUCCEEDED"
  | "ENDPOINT_PROVISIONING_STATUS_FAILED"
  | "ENDPOINT_PROVISIONING_STATUS_CANCELLING"
  | "ENDPOINT_PROVISIONING_STATUS_CANCELLED";
export const EndpointProvisioningStatus = S.String;

export interface EndpointListItem {
  endpointId?: string;
  name?: string;
  description?: string;
  activeDeploymentId?: string;
  updatedAt?: number;
  metadata?: EndpointMetadata;
  appState?: AppState;
  functionId?: string;
  createdByAvatarUrl?: string;
  provisioningStatus?: EndpointProvisioningStatus;
  status?: string;
  servingMode?: EndpointServingMode;
  unauthenticated?: boolean;
}
export const EndpointListItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    endpointId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    name: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    description: S.optional(S.String.pipe(T.ProtoField({ n: 3, t: "string" }))),
    activeDeploymentId: S.optional(
      S.String.pipe(T.ProtoField({ n: 4, t: "string" })),
    ),
    updatedAt: S.optional(S.Number.pipe(T.ProtoField({ n: 5, t: "double" }))),
    metadata: S.optional(
      EndpointMetadata.pipe(T.ProtoField({ n: 6, t: "message" })),
    ),
    appState: S.optional(
      AppState.pipe(
        T.ProtoField({
          n: 7,
          t: "enum",
          e: {
            APP_STATE_UNSPECIFIED: 0,
            APP_STATE_EPHEMERAL: 1,
            APP_STATE_DETACHED: 2,
            APP_STATE_DEPLOYED: 3,
            APP_STATE_STOPPING: 4,
            APP_STATE_STOPPED: 5,
            APP_STATE_INITIALIZING: 6,
            APP_STATE_DISABLED: 7,
            APP_STATE_DETACHED_DISCONNECTED: 8,
            APP_STATE_DERIVED: 9,
          },
        }),
      ),
    ),
    functionId: S.optional(S.String.pipe(T.ProtoField({ n: 8, t: "string" }))),
    createdByAvatarUrl: S.optional(
      S.String.pipe(T.ProtoField({ n: 9, t: "string" })),
    ),
    provisioningStatus: S.optional(
      EndpointProvisioningStatus.pipe(
        T.ProtoField({
          n: 10,
          t: "enum",
          e: {
            ENDPOINT_PROVISIONING_STATUS_UNSPECIFIED: 0,
            ENDPOINT_PROVISIONING_STATUS_PENDING: 1,
            ENDPOINT_PROVISIONING_STATUS_RUNNING: 2,
            ENDPOINT_PROVISIONING_STATUS_SUCCEEDED: 3,
            ENDPOINT_PROVISIONING_STATUS_FAILED: 4,
            ENDPOINT_PROVISIONING_STATUS_CANCELLING: 5,
            ENDPOINT_PROVISIONING_STATUS_CANCELLED: 6,
          },
        }),
      ),
    ),
    status: S.optional(S.String.pipe(T.ProtoField({ n: 11, t: "string" }))),
    servingMode: S.optional(
      EndpointServingMode.pipe(
        T.ProtoField({
          n: 12,
          t: "enum",
          e: {
            ENDPOINT_SERVING_MODE_UNSPECIFIED: 0,
            ENDPOINT_SERVING_MODE_DEDICATED: 1,
            ENDPOINT_SERVING_MODE_SHARED: 2,
          },
        }),
      ),
    ),
    unauthenticated: S.optional(
      S.Boolean.pipe(T.ProtoField({ n: 13, t: "bool" })),
    ),
  }),
).annotate({
  identifier: "EndpointListItem",
}) as any as S.Schema<EndpointListItem>;

export type EndpointListItemList = Array<EndpointListItem>;
export const EndpointListItemList = /*@__PURE__*/ S.Array(
  EndpointListItem,
) as any as S.Schema<EndpointListItemList>;

export interface ListEndpointResponse {
  items?: EndpointListItemList;
  environmentName?: string;
}
export const ListEndpointResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    items: S.optional(
      EndpointListItemList.pipe(
        T.ProtoField({ n: 1, t: "message", rep: true }),
      ),
    ),
    environmentName: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "string" })),
    ),
  }),
).annotate({
  identifier: "ListEndpointResponse",
}) as any as S.Schema<ListEndpointResponse>;

export type EndpointStopSource =
  | "ENDPOINT_STOP_SOURCE_UNSPECIFIED"
  | "ENDPOINT_STOP_SOURCE_CLI"
  | "ENDPOINT_STOP_SOURCE_WEB";
export const EndpointStopSource = S.String;

export interface StopEndpointRequest {
  endpointId?: string;
  source?: EndpointStopSource | (string & {});
}
export const StopEndpointRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    endpointId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    source: S.optional(
      EndpointStopSource.pipe(
        T.ProtoField({
          n: 2,
          t: "enum",
          e: {
            ENDPOINT_STOP_SOURCE_UNSPECIFIED: 0,
            ENDPOINT_STOP_SOURCE_CLI: 1,
            ENDPOINT_STOP_SOURCE_WEB: 2,
          },
        }),
      ),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/EndpointStop",
      code: 200,
    }),
  ),
).annotate({
  identifier: "StopEndpointRequest",
}) as any as S.Schema<StopEndpointRequest>;

export interface StopEndpointResponse {}
export const StopEndpointResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "StopEndpointResponse",
}) as any as S.Schema<StopEndpointResponse>;

export type CreateEndpointError = ModalOpError;
/** Endpoints */
export const createEndpoint: API.OperationMethod<
  CreateEndpointRequest,
  CreateEndpointResponse,
  CreateEndpointError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateEndpointRequest,
  output: CreateEndpointResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type EndpointGetByNameError = ModalOpError;
export const endpointGetByName: API.OperationMethod<
  EndpointGetByNameRequest,
  EndpointGetByNameResponse,
  EndpointGetByNameError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: EndpointGetByNameRequest,
  output: EndpointGetByNameResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type EndpointGetLifecycleError = ModalOpError;
export const endpointGetLifecycle: API.OperationMethod<
  EndpointGetLifecycleRequest,
  EndpointGetLifecycleResponse,
  EndpointGetLifecycleError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: EndpointGetLifecycleRequest,
  output: EndpointGetLifecycleResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type ListEndpointError = ModalOpError;
export const listEndpoint: API.OperationMethod<
  ListEndpointRequest,
  ListEndpointResponse,
  ListEndpointError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListEndpointRequest,
  output: ListEndpointResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type StopEndpointError = ModalOpError;
export const stopEndpoint: API.OperationMethod<
  StopEndpointRequest,
  StopEndpointResponse,
  StopEndpointError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: StopEndpointRequest,
  output: StopEndpointResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));
