// AUTO-GENERATED by scripts/generate.ts from .generated-specs (modal_proto → smithy). Do not edit.
import * as S from "@rikalabs/distilled-core/schema";
import * as API from "@rikalabs/distilled-core/api";
import * as T from "../traits.ts";
import {
  ModalProtocol,
  type ModalOpError,
  type ModalOpContext,
} from "../protocol.ts";
import { UnknownModalError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { ModalOpError, ModalOpContext };

export interface DeleteImageRequest {
  imageId?: string;
}
export const DeleteImageRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    imageId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/ImageDelete",
      code: 200,
    }),
  ),
).annotate({
  identifier: "DeleteImageRequest",
}) as any as S.Schema<DeleteImageRequest>;

export interface DeleteImageResponse {}
export const DeleteImageResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "DeleteImageResponse",
}) as any as S.Schema<DeleteImageResponse>;

export interface GetImageBuildChainRequest {
  imageId?: string;
}
export const GetImageBuildChainRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    imageId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/ImageBuildChainGet",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetImageBuildChainRequest",
}) as any as S.Schema<GetImageBuildChainRequest>;

export interface ImageBuildStep {
  imageId?: string;
  startedAt?: string;
  finishedAt?: string;
  builderAppId?: string;
  builderTaskId?: string;
}
export const ImageBuildStep = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    imageId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    startedAt: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "wkt", w: "Timestamp" })),
    ),
    finishedAt: S.optional(
      S.String.pipe(T.ProtoField({ n: 3, t: "wkt", w: "Timestamp" })),
    ),
    builderAppId: S.optional(
      S.String.pipe(T.ProtoField({ n: 4, t: "string" })),
    ),
    builderTaskId: S.optional(
      S.String.pipe(T.ProtoField({ n: 5, t: "string" })),
    ),
  }),
).annotate({ identifier: "ImageBuildStep" }) as any as S.Schema<ImageBuildStep>;

export type ImageBuildStepList = Array<ImageBuildStep>;
export const ImageBuildStepList = /*@__PURE__*/ S.Array(
  ImageBuildStep,
) as any as S.Schema<ImageBuildStepList>;

export interface GetImageBuildChainResponse {
  buildSteps?: ImageBuildStepList;
}
export const GetImageBuildChainResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    buildSteps: S.optional(
      ImageBuildStepList.pipe(T.ProtoField({ n: 1, t: "message", rep: true })),
    ),
  }),
).annotate({
  identifier: "GetImageBuildChainResponse",
}) as any as S.Schema<GetImageBuildChainResponse>;

export interface ImageFromIdRequest {
  imageId?: string;
}
export const ImageFromIdRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    imageId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/ImageFromId",
      code: 200,
    }),
  ),
).annotate({
  identifier: "ImageFromIdRequest",
}) as any as S.Schema<ImageFromIdRequest>;

export type StringMap = { [key: string]: string | undefined };
export const StringMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<StringMap>;

export interface ImageMetadata {
  /** The output of `python -VV. Not set if missing */
  pythonVersionInfo?: string;
  /** Installed python packages, as listed by by `pip list`. package name -> version. Empty if missing */
  pythonPackages?: StringMap;
  /** The working directory of the image, as an absolute file path. For most images, this is not set, which means to use the default workdir: - On function runners, the default is `/root` (home directory). - For image builds and sandbox environments, it is `/`. */
  workdir?: string;
  /** The version of glibc in this image, if any. */
  libcVersionInfo?: string;
  /** The builder version for/with which the image was created. */
  imageBuilderVersion?: string;
}
export const ImageMetadata = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    pythonVersionInfo: S.optional(
      S.String.pipe(T.ProtoField({ n: 1, t: "string" })),
    ),
    pythonPackages: S.optional(
      StringMap.pipe(
        T.ProtoField({ n: 2, t: "map", k: "string", v: { t: "string" } }),
      ),
    ),
    workdir: S.optional(S.String.pipe(T.ProtoField({ n: 3, t: "string" }))),
    libcVersionInfo: S.optional(
      S.String.pipe(T.ProtoField({ n: 4, t: "string" })),
    ),
    imageBuilderVersion: S.optional(
      S.String.pipe(T.ProtoField({ n: 5, t: "string" })),
    ),
  }),
).annotate({ identifier: "ImageMetadata" }) as any as S.Schema<ImageMetadata>;

export interface ImageFromIdResponse {
  imageId?: string;
  metadata?: ImageMetadata;
}
export const ImageFromIdResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    imageId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    metadata: S.optional(
      ImageMetadata.pipe(T.ProtoField({ n: 2, t: "message" })),
    ),
  }),
).annotate({
  identifier: "ImageFromIdResponse",
}) as any as S.Schema<ImageFromIdResponse>;

export interface ImageGetByTagRequest {
  /** Named image reference: "[[workspace/]environment/]name[:tag]". The tag suffix defaults to "latest" when omitted. */
  tag?: string;
  /** New clients should send environment name as a /-separated prefix of the `tag` field. environment_name only accepted when tag has no environment or workspace prefix. */
  environmentName?: string;
}
export const ImageGetByTagRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    tag: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    environmentName: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "string" })),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/ImageGetByTag",
      code: 200,
    }),
  ),
).annotate({
  identifier: "ImageGetByTagRequest",
}) as any as S.Schema<ImageGetByTagRequest>;

export interface ImageGetByTagResponse {
  imageId?: string;
}
export const ImageGetByTagResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    imageId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
  }),
).annotate({
  identifier: "ImageGetByTagResponse",
}) as any as S.Schema<ImageGetByTagResponse>;

export interface BaseImage {
  imageId?: string;
  dockerTag?: string;
}
export const BaseImage = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    imageId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    dockerTag: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
  }),
).annotate({ identifier: "BaseImage" }) as any as S.Schema<BaseImage>;

export type BaseImageList = Array<BaseImage>;
export const BaseImageList = /*@__PURE__*/ S.Array(
  BaseImage,
) as any as S.Schema<BaseImageList>;

export type StringList = Array<string>;
export const StringList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<StringList>;

export interface ImageContextFile {
  filename?: string;
  data?: string;
}
export const ImageContextFile = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    filename: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    data: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "bytes" }))),
  }),
).annotate({
  identifier: "ImageContextFile",
}) as any as S.Schema<ImageContextFile>;

export type ImageContextFileList = Array<ImageContextFile>;
export const ImageContextFileList = /*@__PURE__*/ S.Array(
  ImageContextFile,
) as any as S.Schema<ImageContextFileList>;

export type GPUType =
  | "GPU_TYPE_UNSPECIFIED"
  | "GPU_TYPE_T4"
  | "GPU_TYPE_A100"
  | "GPU_TYPE_A10G"
  | "GPU_TYPE_ANY"
  | "GPU_TYPE_A100_80GB"
  | "GPU_TYPE_L4"
  | "GPU_TYPE_H100"
  | "GPU_TYPE_L40S"
  | "GPU_TYPE_H200";
export const GPUType = S.String;

export interface GPUConfig {
  type?: GPUType | (string & {});
  /** Deprecated, at some point */
  count?: number;
  gpuType?: string;
}
export const GPUConfig = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    type: S.optional(
      GPUType.pipe(
        T.ProtoField({
          n: 1,
          t: "enum",
          e: {
            GPU_TYPE_UNSPECIFIED: 0,
            GPU_TYPE_T4: 1,
            GPU_TYPE_A100: 2,
            GPU_TYPE_A10G: 3,
            GPU_TYPE_ANY: 4,
            GPU_TYPE_A100_80GB: 8,
            GPU_TYPE_L4: 9,
            GPU_TYPE_H100: 10,
            GPU_TYPE_L40S: 11,
            GPU_TYPE_H200: 12,
          },
        }),
      ),
    ),
    count: S.optional(S.Number.pipe(T.ProtoField({ n: 2, t: "uint32" }))),
    gpuType: S.optional(S.String.pipe(T.ProtoField({ n: 4, t: "string" }))),
  }),
).annotate({ identifier: "GPUConfig" }) as any as S.Schema<GPUConfig>;

export type RegistryAuthType =
  | "REGISTRY_AUTH_TYPE_UNSPECIFIED"
  | "REGISTRY_AUTH_TYPE_AWS"
  | "REGISTRY_AUTH_TYPE_GCP"
  | "REGISTRY_AUTH_TYPE_PUBLIC"
  | "REGISTRY_AUTH_TYPE_STATIC_CREDS";
export const RegistryAuthType = S.String;

export interface ImageRegistryConfig {
  registryAuthType?: RegistryAuthType | (string & {});
  secretId?: string;
}
export const ImageRegistryConfig = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    registryAuthType: S.optional(
      RegistryAuthType.pipe(
        T.ProtoField({
          n: 1,
          t: "enum",
          e: {
            REGISTRY_AUTH_TYPE_UNSPECIFIED: 0,
            REGISTRY_AUTH_TYPE_AWS: 1,
            REGISTRY_AUTH_TYPE_GCP: 2,
            REGISTRY_AUTH_TYPE_PUBLIC: 3,
            REGISTRY_AUTH_TYPE_STATIC_CREDS: 4,
          },
        }),
      ),
    ),
    secretId: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
  }),
).annotate({
  identifier: "ImageRegistryConfig",
}) as any as S.Schema<ImageRegistryConfig>;

/** Which data format a binary message is encoded with. */
export type DataFormat =
  | "DATA_FORMAT_UNSPECIFIED"
  | "DATA_FORMAT_PICKLE"
  | "DATA_FORMAT_ASGI"
  | "DATA_FORMAT_GENERATOR_DONE"
  | "DATA_FORMAT_CBOR";
export const DataFormat = S.String;

export interface FunctionInput {
  /** serialized (args, kwargs). */
  args?: string;
  argsBlobId?: string;
  finalInput?: boolean;
  dataFormat?: DataFormat | (string & {});
  /** For args_oneof. */
  methodName?: string;
}
export const FunctionInput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    args: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "bytes" }))),
    argsBlobId: S.optional(S.String.pipe(T.ProtoField({ n: 7, t: "string" }))),
    finalInput: S.optional(S.Boolean.pipe(T.ProtoField({ n: 9, t: "bool" }))),
    dataFormat: S.optional(
      DataFormat.pipe(
        T.ProtoField({
          n: 10,
          t: "enum",
          e: {
            DATA_FORMAT_UNSPECIFIED: 0,
            DATA_FORMAT_PICKLE: 1,
            DATA_FORMAT_ASGI: 2,
            DATA_FORMAT_GENERATOR_DONE: 3,
            DATA_FORMAT_CBOR: 4,
          },
        }),
      ),
    ),
    methodName: S.optional(S.String.pipe(T.ProtoField({ n: 11, t: "string" }))),
  }),
).annotate({ identifier: "FunctionInput" }) as any as S.Schema<FunctionInput>;

export interface BuildFunction {
  definition?: string;
  globals?: string;
  input?: FunctionInput;
}
export const BuildFunction = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    definition: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    globals: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "bytes" }))),
    input: S.optional(FunctionInput.pipe(T.ProtoField({ n: 3, t: "message" }))),
  }),
).annotate({ identifier: "BuildFunction" }) as any as S.Schema<BuildFunction>;

export interface VolumeMount {
  volumeId?: string;
  mountPath?: string;
  allowBackgroundCommits?: boolean;
  readOnly?: boolean;
  subPath?: string;
}
export const VolumeMount = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    volumeId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    mountPath: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    allowBackgroundCommits: S.optional(
      S.Boolean.pipe(T.ProtoField({ n: 3, t: "bool" })),
    ),
    readOnly: S.optional(S.Boolean.pipe(T.ProtoField({ n: 4, t: "bool" }))),
    subPath: S.optional(S.String.pipe(T.ProtoField({ n: 5, t: "string" }))),
  }),
).annotate({ identifier: "VolumeMount" }) as any as S.Schema<VolumeMount>;

export type VolumeMountList = Array<VolumeMount>;
export const VolumeMountList = /*@__PURE__*/ S.Array(
  VolumeMount,
) as any as S.Schema<VolumeMountList>;

/** CPU architecture an image is built for and must run on. */
export type Arch = "ARCH_UNSPECIFIED" | "ARCH_X86_64" | "ARCH_AARCH64";
export const Arch = S.String;

export interface Image {
  baseImages?: BaseImageList;
  dockerfileCommands?: StringList;
  contextFiles?: ImageContextFileList;
  version?: string;
  secretIds?: StringList;
  /** Part of Image definition, because presence of GPU drivers affects the image that's built. */
  contextMountId?: string;
  gpuConfig?: GPUConfig;
  imageRegistryConfig?: ImageRegistryConfig;
  buildFunctionDef?: string;
  /** deprecated after 0.58.96 */
  buildFunctionGlobals?: string;
  /** deprecated after 0.58.96 If set, overrides the runtime used by the function. Specify either "runc" or "gvisor". */
  runtime?: string;
  /** Not included in image definition checksum as debug features do not affect built image. */
  runtimeDebug?: boolean;
  buildFunction?: BuildFunction;
  /** Build arguments for the image (--build-arg) for ARG substitution in Dockerfile. */
  buildArgs?: StringMap;
  /** Volume mount for RUN commands */
  volumeMounts?: VolumeMountList;
  /** CPU architecture the image is built for. Images with an unspecified arch predate this field and are treated as x86_64. */
  arch?: Arch | (string & {});
}
export const Image = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    baseImages: S.optional(
      BaseImageList.pipe(T.ProtoField({ n: 5, t: "message", rep: true })),
    ),
    dockerfileCommands: S.optional(
      StringList.pipe(T.ProtoField({ n: 6, t: "string", rep: true })),
    ),
    contextFiles: S.optional(
      ImageContextFileList.pipe(
        T.ProtoField({ n: 7, t: "message", rep: true }),
      ),
    ),
    version: S.optional(S.String.pipe(T.ProtoField({ n: 11, t: "string" }))),
    secretIds: S.optional(
      StringList.pipe(T.ProtoField({ n: 12, t: "string", rep: true })),
    ),
    contextMountId: S.optional(
      S.String.pipe(T.ProtoField({ n: 15, t: "string" })),
    ),
    gpuConfig: S.optional(
      GPUConfig.pipe(T.ProtoField({ n: 16, t: "message" })),
    ),
    imageRegistryConfig: S.optional(
      ImageRegistryConfig.pipe(T.ProtoField({ n: 17, t: "message" })),
    ),
    buildFunctionDef: S.optional(
      S.String.pipe(T.ProtoField({ n: 14, t: "string" })),
    ),
    buildFunctionGlobals: S.optional(
      S.String.pipe(T.ProtoField({ n: 18, t: "bytes" })),
    ),
    runtime: S.optional(S.String.pipe(T.ProtoField({ n: 19, t: "string" }))),
    runtimeDebug: S.optional(
      S.Boolean.pipe(T.ProtoField({ n: 20, t: "bool" })),
    ),
    buildFunction: S.optional(
      BuildFunction.pipe(T.ProtoField({ n: 21, t: "message" })),
    ),
    buildArgs: S.optional(
      StringMap.pipe(
        T.ProtoField({ n: 22, t: "map", k: "string", v: { t: "string" } }),
      ),
    ),
    volumeMounts: S.optional(
      VolumeMountList.pipe(T.ProtoField({ n: 23, t: "message", rep: true })),
    ),
    arch: S.optional(
      Arch.pipe(
        T.ProtoField({
          n: 24,
          t: "enum",
          e: { ARCH_UNSPECIFIED: 0, ARCH_X86_64: 1, ARCH_AARCH64: 2 },
        }),
      ),
    ),
  }),
).annotate({ identifier: "Image" }) as any as S.Schema<Image>;

export type DeploymentNamespace =
  | "DEPLOYMENT_NAMESPACE_UNSPECIFIED"
  | "DEPLOYMENT_NAMESPACE_WORKSPACE"
  | "DEPLOYMENT_NAMESPACE_GLOBAL";
export const DeploymentNamespace = S.String;

export interface ImageGetOrCreateRequest {
  image?: Image;
  appId?: string;
  existingImageId?: string;
  /** ignored */
  buildFunctionId?: string;
  forceBuild?: boolean;
  namespace?: DeploymentNamespace | (string & {});
  builderVersion?: string;
  /** Only admins can publish global images, but this provides an extra failsafe */
  allowGlobalDeployment?: boolean;
  /** Force the Image to build but don't clobber any Images with the same recipe in the cache */
  ignoreCache?: boolean;
}
export const ImageGetOrCreateRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    image: S.optional(Image.pipe(T.ProtoField({ n: 2, t: "message" }))),
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 4, t: "string" }))),
    existingImageId: S.optional(
      S.String.pipe(T.ProtoField({ n: 5, t: "string" })),
    ),
    buildFunctionId: S.optional(
      S.String.pipe(T.ProtoField({ n: 6, t: "string" })),
    ),
    forceBuild: S.optional(S.Boolean.pipe(T.ProtoField({ n: 7, t: "bool" }))),
    namespace: S.optional(
      DeploymentNamespace.pipe(
        T.ProtoField({
          n: 8,
          t: "enum",
          e: {
            DEPLOYMENT_NAMESPACE_UNSPECIFIED: 0,
            DEPLOYMENT_NAMESPACE_WORKSPACE: 1,
            DEPLOYMENT_NAMESPACE_GLOBAL: 3,
          },
        }),
      ),
    ),
    builderVersion: S.optional(
      S.String.pipe(T.ProtoField({ n: 9, t: "string" })),
    ),
    allowGlobalDeployment: S.optional(
      S.Boolean.pipe(T.ProtoField({ n: 10, t: "bool" })),
    ),
    ignoreCache: S.optional(S.Boolean.pipe(T.ProtoField({ n: 11, t: "bool" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/ImageGetOrCreate",
      code: 200,
    }),
  ),
).annotate({
  identifier: "ImageGetOrCreateRequest",
}) as any as S.Schema<ImageGetOrCreateRequest>;

/** Used for both tasks and function outputs */
export type GenericResultGenericStatus =
  | "GENERIC_STATUS_UNSPECIFIED"
  | "GENERIC_STATUS_SUCCESS"
  | "GENERIC_STATUS_FAILURE"
  | "GENERIC_STATUS_TERMINATED"
  | "GENERIC_STATUS_TIMEOUT"
  | "GENERIC_STATUS_INIT_FAILURE"
  | "GENERIC_STATUS_INTERNAL_FAILURE"
  | "GENERIC_STATUS_IDLE_TIMEOUT"
  | "GENERIC_STATUS_MEMORY_MANAGER_EVICTION";
export const GenericResultGenericStatus = S.String;

/** sub-type for generic types like lists */
export interface GenericResult {
  status?: GenericResultGenericStatus;
  /** Status of the task or function output. */
  exception?: string;
  /** Exception message for failures, if available. */
  exitcode?: number;
  /** Status code of the container entrypoint or builder process if it terminates unexpectedly. */
  traceback?: string;
  /** String value of the Python traceback. */
  serializedTb?: string;
  /** Pickled traceback object. */
  tbLineCache?: string;
  /** Pickled line cache for traceback object. */
  data?: string;
  /** Inline data of the result. */
  dataBlobId?: string;
  /** Blob ID for large data. */
  propagationReason?: string;
}
export const GenericResult = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    status: S.optional(
      GenericResultGenericStatus.pipe(
        T.ProtoField({
          n: 1,
          t: "enum",
          e: {
            GENERIC_STATUS_UNSPECIFIED: 0,
            GENERIC_STATUS_SUCCESS: 1,
            GENERIC_STATUS_FAILURE: 2,
            GENERIC_STATUS_TERMINATED: 3,
            GENERIC_STATUS_TIMEOUT: 4,
            GENERIC_STATUS_INIT_FAILURE: 5,
            GENERIC_STATUS_INTERNAL_FAILURE: 6,
            GENERIC_STATUS_IDLE_TIMEOUT: 7,
            GENERIC_STATUS_MEMORY_MANAGER_EVICTION: 8,
          },
        }),
      ),
    ),
    exception: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    exitcode: S.optional(S.Number.pipe(T.ProtoField({ n: 3, t: "int32" }))),
    traceback: S.optional(S.String.pipe(T.ProtoField({ n: 4, t: "string" }))),
    serializedTb: S.optional(
      S.String.pipe(T.ProtoField({ n: 11, t: "bytes" })),
    ),
    tbLineCache: S.optional(S.String.pipe(T.ProtoField({ n: 12, t: "bytes" }))),
    data: S.optional(S.String.pipe(T.ProtoField({ n: 5, t: "bytes" }))),
    dataBlobId: S.optional(S.String.pipe(T.ProtoField({ n: 10, t: "string" }))),
    propagationReason: S.optional(
      S.String.pipe(T.ProtoField({ n: 13, t: "string" })),
    ),
  }),
).annotate({ identifier: "GenericResult" }) as any as S.Schema<GenericResult>;

export interface ImageGetOrCreateResponse {
  /** image_id is set regardless if the image is built (use ImageJoinStreaming to wait for build) */
  imageId?: string;
  /** result of build - only set if the image has finished building (regardless if success or not) */
  result?: GenericResult;
  /** image metadata - only set if the image has built successfully */
  metadata?: ImageMetadata;
}
export const ImageGetOrCreateResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    imageId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    result: S.optional(
      GenericResult.pipe(T.ProtoField({ n: 2, t: "message" })),
    ),
    metadata: S.optional(
      ImageMetadata.pipe(T.ProtoField({ n: 3, t: "message" })),
    ),
  }),
).annotate({
  identifier: "ImageGetOrCreateResponse",
}) as any as S.Schema<ImageGetOrCreateResponse>;

export interface ImageListTagsRequest {
  environmentName?: string;
  /** Prefix search over full "name:tag" strings. */
  tagPrefix?: string;
  /** Defaults to 100. Values above 100 are rejected by the server. */
  maxObjects?: number;
  pageToken?: string;
}
export const ImageListTagsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    environmentName: S.optional(
      S.String.pipe(T.ProtoField({ n: 1, t: "string" })),
    ),
    tagPrefix: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    maxObjects: S.optional(S.Number.pipe(T.ProtoField({ n: 3, t: "uint32" }))),
    pageToken: S.optional(S.String.pipe(T.ProtoField({ n: 4, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/ImageListTags",
      code: 200,
    }),
  ),
).annotate({
  identifier: "ImageListTagsRequest",
}) as any as S.Schema<ImageListTagsRequest>;

/** set on success */
export interface ImageListTagsItem {
  tag?: string;
  imageId?: string;
  revisionId?: string;
  createdAt?: number;
  updatedAt?: number;
}
export const ImageListTagsItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    tag: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    imageId: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    revisionId: S.optional(S.String.pipe(T.ProtoField({ n: 3, t: "string" }))),
    createdAt: S.optional(S.Number.pipe(T.ProtoField({ n: 4, t: "double" }))),
    updatedAt: S.optional(S.Number.pipe(T.ProtoField({ n: 5, t: "double" }))),
  }),
).annotate({
  identifier: "ImageListTagsItem",
}) as any as S.Schema<ImageListTagsItem>;

export type ImageListTagsItemList = Array<ImageListTagsItem>;
export const ImageListTagsItemList = /*@__PURE__*/ S.Array(
  ImageListTagsItem,
) as any as S.Schema<ImageListTagsItemList>;

export interface ImageListTagsResponse {
  items?: ImageListTagsItemList;
  nextPageToken?: string;
  environmentName?: string;
}
export const ImageListTagsResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    items: S.optional(
      ImageListTagsItemList.pipe(
        T.ProtoField({ n: 1, t: "message", rep: true }),
      ),
    ),
    nextPageToken: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "string" })),
    ),
    environmentName: S.optional(
      S.String.pipe(T.ProtoField({ n: 3, t: "string" })),
    ),
  }),
).annotate({
  identifier: "ImageListTagsResponse",
}) as any as S.Schema<ImageListTagsResponse>;

export interface ImageTagRevisionsRequest {
  /** Named image reference: "[[workspace/]environment/]name[:tag]". The tag suffix defaults to "latest" when omitted. */
  tag?: string;
  /** New clients should send environment name as a /-separated prefix of the `tag` field. environment_name only accepted when tag has no environment or workspace prefix. */
  environmentName?: string;
  /** Defaults to 100. Values above 100 are rejected by the server. */
  maxObjects?: number;
  pageToken?: string;
}
export const ImageTagRevisionsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    tag: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    environmentName: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "string" })),
    ),
    maxObjects: S.optional(S.Number.pipe(T.ProtoField({ n: 3, t: "uint32" }))),
    pageToken: S.optional(S.String.pipe(T.ProtoField({ n: 4, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/ImageTagRevisions",
      code: 200,
    }),
  ),
).annotate({
  identifier: "ImageTagRevisionsRequest",
}) as any as S.Schema<ImageTagRevisionsRequest>;

export interface ImageTagRevisionsItem {
  imageId?: string;
  revisionId?: string;
  createdAt?: number;
  publishedBy?: string;
}
export const ImageTagRevisionsItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    imageId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    revisionId: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    createdAt: S.optional(S.Number.pipe(T.ProtoField({ n: 3, t: "double" }))),
    publishedBy: S.optional(S.String.pipe(T.ProtoField({ n: 4, t: "string" }))),
  }),
).annotate({
  identifier: "ImageTagRevisionsItem",
}) as any as S.Schema<ImageTagRevisionsItem>;

export type ImageTagRevisionsItemList = Array<ImageTagRevisionsItem>;
export const ImageTagRevisionsItemList = /*@__PURE__*/ S.Array(
  ImageTagRevisionsItem,
) as any as S.Schema<ImageTagRevisionsItemList>;

export interface ImageTagRevisionsResponse {
  items?: ImageTagRevisionsItemList;
  nextPageToken?: string;
  tag?: string;
  environmentName?: string;
}
export const ImageTagRevisionsResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    items: S.optional(
      ImageTagRevisionsItemList.pipe(
        T.ProtoField({ n: 1, t: "message", rep: true }),
      ),
    ),
    nextPageToken: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "string" })),
    ),
    tag: S.optional(S.String.pipe(T.ProtoField({ n: 3, t: "string" }))),
    environmentName: S.optional(
      S.String.pipe(T.ProtoField({ n: 4, t: "string" })),
    ),
  }),
).annotate({
  identifier: "ImageTagRevisionsResponse",
}) as any as S.Schema<ImageTagRevisionsResponse>;

export interface PublishImageRequest {
  imageId?: string;
  /** Named image reference: "[[workspace/]environment/]name[:tag]". The tag suffix defaults to "latest" when omitted. */
  tag?: string;
  /** New clients should send environment name as a /-separated prefix of the `tag` field. environment_name only accepted when tag has no environment or workspace prefix. */
  environmentName?: string;
  /** Explicit opt-in required when publishing to a public environment. */
  allowPublic?: boolean;
}
export const PublishImageRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    imageId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    tag: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    environmentName: S.optional(
      S.String.pipe(T.ProtoField({ n: 3, t: "string" })),
    ),
    allowPublic: S.optional(S.Boolean.pipe(T.ProtoField({ n: 4, t: "bool" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/ImagePublish",
      code: 200,
    }),
  ),
).annotate({
  identifier: "PublishImageRequest",
}) as any as S.Schema<PublishImageRequest>;

export interface PublishImageResponse {
  imageId?: string;
  revisionId?: string;
}
export const PublishImageResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    imageId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    revisionId: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
  }),
).annotate({
  identifier: "PublishImageResponse",
}) as any as S.Schema<PublishImageResponse>;

export type DeleteImageError = ModalOpError;
export const deleteImage: API.OperationMethod<
  DeleteImageRequest,
  DeleteImageResponse,
  DeleteImageError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteImageRequest,
  output: DeleteImageResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type GetImageBuildChainError = ModalOpError;
/** Images */
export const getImageBuildChain: API.OperationMethod<
  GetImageBuildChainRequest,
  GetImageBuildChainResponse,
  GetImageBuildChainError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetImageBuildChainRequest,
  output: GetImageBuildChainResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type ImageFromIdError = ModalOpError;
export const imageFromId: API.OperationMethod<
  ImageFromIdRequest,
  ImageFromIdResponse,
  ImageFromIdError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ImageFromIdRequest,
  output: ImageFromIdResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type ImageGetByTagError = ModalOpError;
export const imageGetByTag: API.OperationMethod<
  ImageGetByTagRequest,
  ImageGetByTagResponse,
  ImageGetByTagError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ImageGetByTagRequest,
  output: ImageGetByTagResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type ImageGetOrCreateError = ModalOpError;
export const imageGetOrCreate: API.OperationMethod<
  ImageGetOrCreateRequest,
  ImageGetOrCreateResponse,
  ImageGetOrCreateError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ImageGetOrCreateRequest,
  output: ImageGetOrCreateResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type ImageListTagsError = ModalOpError;
export const imageListTags: API.OperationMethod<
  ImageListTagsRequest,
  ImageListTagsResponse,
  ImageListTagsError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ImageListTagsRequest,
  output: ImageListTagsResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type ImageTagRevisionsError = ModalOpError;
export const imageTagRevisions: API.OperationMethod<
  ImageTagRevisionsRequest,
  ImageTagRevisionsResponse,
  ImageTagRevisionsError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ImageTagRevisionsRequest,
  output: ImageTagRevisionsResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type PublishImageError = ModalOpError;
export const publishImage: API.OperationMethod<
  PublishImageRequest,
  PublishImageResponse,
  PublishImageError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PublishImageRequest,
  output: PublishImageResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));
