// AUTO-GENERATED by scripts/generate.ts from .generated-specs (modal_proto → smithy). Do not edit.
import * as S from "@rikalabs/distilled-core/schema";
import * as API from "@rikalabs/distilled-core/api";
import * as T from "../traits.ts";
import {
  ModalProtocol,
  type ModalOpError,
  type ModalOpContext,
} from "../protocol.ts";
import { UnknownModalError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { ModalOpError, ModalOpContext };

/** Result of executing a code cell. */
export interface NotebookOutputExecuteResult {
  executionCount?: number;
  data?: unknown;
  /** mimebundle */
  metadata?: unknown;
}
export const NotebookOutputExecuteResult = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    executionCount: S.optional(
      S.Number.pipe(T.ProtoField({ n: 1, t: "uint32" })),
    ),
    data: S.optional(
      S.Unknown.pipe(T.ProtoField({ n: 2, t: "wkt", w: "Struct" })),
    ),
    metadata: S.optional(
      S.Unknown.pipe(T.ProtoField({ n: 3, t: "wkt", w: "Struct" })),
    ),
  }),
).annotate({
  identifier: "NotebookOutputExecuteResult",
}) as any as S.Schema<NotebookOutputExecuteResult>;

/** Data displayed as a result of code cell execution. */
export interface NotebookOutputDisplayData {
  data?: unknown;
  /** mimebundle */
  metadata?: unknown;
  /** This should not be included in saved notebook. */
  transientDisplayId?: string;
}
export const NotebookOutputDisplayData = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    data: S.optional(
      S.Unknown.pipe(T.ProtoField({ n: 1, t: "wkt", w: "Struct" })),
    ),
    metadata: S.optional(
      S.Unknown.pipe(T.ProtoField({ n: 2, t: "wkt", w: "Struct" })),
    ),
    transientDisplayId: S.optional(
      S.String.pipe(T.ProtoField({ n: 3, t: "string" })),
    ),
  }),
).annotate({
  identifier: "NotebookOutputDisplayData",
}) as any as S.Schema<NotebookOutputDisplayData>;

/** Stream output from a code cell (stdout / stderr). */
export interface NotebookOutputStream {
  name?: string;
  /** stdout | stderr */
  text?: string;
}
export const NotebookOutputStream = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    text: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
  }),
).annotate({
  identifier: "NotebookOutputStream",
}) as any as S.Schema<NotebookOutputStream>;

export type StringList = Array<string>;
export const StringList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<StringList>;

/** Output of an error that occurred during code cell execution. */
export interface NotebookOutputError {
  ename?: string;
  evalue?: string;
  traceback?: StringList;
}
export const NotebookOutputError = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    ename: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    evalue: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    traceback: S.optional(
      StringList.pipe(T.ProtoField({ n: 3, t: "string", rep: true })),
    ),
  }),
).annotate({
  identifier: "NotebookOutputError",
}) as any as S.Schema<NotebookOutputError>;

/** A single output from a notebook. When you execute a cell, it produces an array of these outputs as the code runs. https://github.com/jupyter/nbformat/blob/v5.10.4/nbformat/v4/nbformat.v4.schema.json#L301-L309 */
export interface NotebookOutput {
  executeResult?: NotebookOutputExecuteResult;
  displayData?: NotebookOutputDisplayData;
  stream?: NotebookOutputStream;
  error?: NotebookOutputError;
}
export const NotebookOutput = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    executeResult: S.optional(
      NotebookOutputExecuteResult.pipe(T.ProtoField({ n: 1, t: "message" })),
    ),
    displayData: S.optional(
      NotebookOutputDisplayData.pipe(T.ProtoField({ n: 2, t: "message" })),
    ),
    stream: S.optional(
      NotebookOutputStream.pipe(T.ProtoField({ n: 3, t: "message" })),
    ),
    error: S.optional(
      NotebookOutputError.pipe(T.ProtoField({ n: 4, t: "message" })),
    ),
  }),
).annotate({ identifier: "NotebookOutput" }) as any as S.Schema<NotebookOutput>;

/** See kernelshim.py for the differences between this and `ExecuteResult`. https://jupyter-client.readthedocs.io/en/stable/messaging.html#execution-results */
export interface NotebookKernelPublishResultsRequestExecuteReply {
  status?: string;
  executionCount?: number;
  duration?: number;
}
export const NotebookKernelPublishResultsRequestExecuteReply =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      status: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
      executionCount: S.optional(
        S.Number.pipe(T.ProtoField({ n: 2, t: "uint32" })),
      ),
      duration: S.optional(S.Number.pipe(T.ProtoField({ n: 3, t: "double" }))),
    }),
  ).annotate({
    identifier: "NotebookKernelPublishResultsRequestExecuteReply",
  }) as any as S.Schema<NotebookKernelPublishResultsRequestExecuteReply>;

/** IOPub message or reply received from the kernel for a cell. */
export interface NotebookKernelPublishResultsRequestCellResult {
  cellId?: string;
  /** Persistent output that is saved in the notebook. */
  output?: NotebookOutput;
  /** Clear all previous outputs of the cell. */
  clearOutput?: boolean;
  /** Cell has finished executing, return the kernel's execute_reply. */
  executeReply?: NotebookKernelPublishResultsRequestExecuteReply;
}
export const NotebookKernelPublishResultsRequestCellResult =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      cellId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
      output: S.optional(
        NotebookOutput.pipe(T.ProtoField({ n: 2, t: "message" })),
      ),
      clearOutput: S.optional(
        S.Boolean.pipe(T.ProtoField({ n: 3, t: "bool" })),
      ),
      executeReply: S.optional(
        NotebookKernelPublishResultsRequestExecuteReply.pipe(
          T.ProtoField({ n: 4, t: "message" }),
        ),
      ),
    }),
  ).annotate({
    identifier: "NotebookKernelPublishResultsRequestCellResult",
  }) as any as S.Schema<NotebookKernelPublishResultsRequestCellResult>;

export type NotebookKernelPublishResultsRequestCellResultList =
  Array<NotebookKernelPublishResultsRequestCellResult>;
export const NotebookKernelPublishResultsRequestCellResultList =
  /*@__PURE__*/ S.Array(
    NotebookKernelPublishResultsRequestCellResult,
  ) as any as S.Schema<NotebookKernelPublishResultsRequestCellResultList>;

export interface NotebookKernelPublishResultsRequest {
  notebookId?: string;
  results?: NotebookKernelPublishResultsRequestCellResultList;
}
export const NotebookKernelPublishResultsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    notebookId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    results: S.optional(
      NotebookKernelPublishResultsRequestCellResultList.pipe(
        T.ProtoField({ n: 2, t: "message", rep: true }),
      ),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/NotebookKernelPublishResults",
      code: 200,
    }),
  ),
).annotate({
  identifier: "NotebookKernelPublishResultsRequest",
}) as any as S.Schema<NotebookKernelPublishResultsRequest>;

export interface NotebookKernelPublishResultsResponse {}
export const NotebookKernelPublishResultsResponse = /*@__PURE__*/ S.suspend(
  () => S.Struct({}),
).annotate({
  identifier: "NotebookKernelPublishResultsResponse",
}) as any as S.Schema<NotebookKernelPublishResultsResponse>;

export type NotebookKernelPublishResultsError = ModalOpError;
/** Notebooks */
export const notebookKernelPublishResults: API.OperationMethod<
  NotebookKernelPublishResultsRequest,
  NotebookKernelPublishResultsResponse,
  NotebookKernelPublishResultsError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: NotebookKernelPublishResultsRequest,
  output: NotebookKernelPublishResultsResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));
