// AUTO-GENERATED by scripts/generate.ts from .generated-specs (modal_proto → smithy). Do not edit.
import * as S from "@rikalabs/distilled-core/schema";
import * as API from "@rikalabs/distilled-core/api";
import * as T from "../traits.ts";
import {
  ModalProtocol,
  type ModalOpError,
  type ModalOpContext,
} from "../protocol.ts";
import { UnknownModalError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { ModalOpError, ModalOpContext };

export interface DeleteSecretRequest {
  secretId?: string;
}
export const DeleteSecretRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    secretId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/SecretDelete",
      code: 200,
    }),
  ),
).annotate({
  identifier: "DeleteSecretRequest",
}) as any as S.Schema<DeleteSecretRequest>;

export interface DeleteSecretResponse {}
export const DeleteSecretResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "DeleteSecretResponse",
}) as any as S.Schema<DeleteSecretResponse>;

export interface ListPagination {
  maxObjects?: number;
  createdBefore?: number;
}
export const ListPagination = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    maxObjects: S.optional(S.Number.pipe(T.ProtoField({ n: 1, t: "int32" }))),
    createdBefore: S.optional(
      S.Number.pipe(T.ProtoField({ n: 2, t: "double" })),
    ),
  }),
).annotate({ identifier: "ListPagination" }) as any as S.Schema<ListPagination>;

export interface ListSecretRequest {
  environmentName?: string;
  pagination?: ListPagination;
}
export const ListSecretRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    environmentName: S.optional(
      S.String.pipe(T.ProtoField({ n: 1, t: "string" })),
    ),
    pagination: S.optional(
      ListPagination.pipe(T.ProtoField({ n: 2, t: "message" })),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/SecretList",
      code: 200,
    }),
  ),
).annotate({
  identifier: "ListSecretRequest",
}) as any as S.Schema<ListSecretRequest>;

export interface CreationInfo {
  /** This message is used in metadata for resource objects like Dict, Queue, Volume, etc. */
  createdAt?: number;
  /** Timestamp of resource creation */
  createdBy?: string;
}
export const CreationInfo = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    createdAt: S.optional(S.Number.pipe(T.ProtoField({ n: 1, t: "double" }))),
    createdBy: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
  }),
).annotate({ identifier: "CreationInfo" }) as any as S.Schema<CreationInfo>;

export interface SecretMetadata {
  name?: string;
  creationInfo?: CreationInfo;
}
export const SecretMetadata = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    creationInfo: S.optional(
      CreationInfo.pipe(T.ProtoField({ n: 2, t: "message" })),
    ),
  }),
).annotate({ identifier: "SecretMetadata" }) as any as S.Schema<SecretMetadata>;

export interface SecretListItem {
  label?: string;
  createdAt?: number;
  /** Superseded by metadata, used by clients up to 1.1.2 */
  lastUsedAt?: number;
  environmentName?: string;
  /** Unused by client */
  secretId?: string;
  metadata?: SecretMetadata;
}
export const SecretListItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    label: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    createdAt: S.optional(S.Number.pipe(T.ProtoField({ n: 2, t: "double" }))),
    lastUsedAt: S.optional(S.Number.pipe(T.ProtoField({ n: 3, t: "double" }))),
    environmentName: S.optional(
      S.String.pipe(T.ProtoField({ n: 4, t: "string" })),
    ),
    secretId: S.optional(S.String.pipe(T.ProtoField({ n: 5, t: "string" }))),
    metadata: S.optional(
      SecretMetadata.pipe(T.ProtoField({ n: 6, t: "message" })),
    ),
  }),
).annotate({ identifier: "SecretListItem" }) as any as S.Schema<SecretListItem>;

export type SecretListItemList = Array<SecretListItem>;
export const SecretListItemList = /*@__PURE__*/ S.Array(
  SecretListItem,
) as any as S.Schema<SecretListItemList>;

export interface ListSecretResponse {
  items?: SecretListItemList;
  environmentName?: string;
}
export const ListSecretResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    items: S.optional(
      SecretListItemList.pipe(T.ProtoField({ n: 1, t: "message", rep: true })),
    ),
    environmentName: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "string" })),
    ),
  }),
).annotate({
  identifier: "ListSecretResponse",
}) as any as S.Schema<ListSecretResponse>;

export type ObjectCreationType =
  | "OBJECT_CREATION_TYPE_UNSPECIFIED"
  | "OBJECT_CREATION_TYPE_CREATE_IF_MISSING"
  | "OBJECT_CREATION_TYPE_CREATE_FAIL_IF_EXISTS"
  | "OBJECT_CREATION_TYPE_CREATE_OVERWRITE_IF_EXISTS"
  | "OBJECT_CREATION_TYPE_ANONYMOUS_OWNED_BY_APP"
  | "OBJECT_CREATION_TYPE_EPHEMERAL";
export const ObjectCreationType = S.String;

export type StringMap = { [key: string]: string | undefined };
export const StringMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<StringMap>;

export type StringList = Array<string>;
export const StringList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<StringList>;

export interface SecretGetOrCreateRequest {
  deploymentName?: string;
  /** removed namespace */
  environmentName?: string;
  objectCreationType?: ObjectCreationType | (string & {});
  /** Not used atm */
  envDict?: StringMap;
  appId?: string;
  /** only used with OBJECT_CREATION_TYPE_ANONYMOUS_OWNED_BY_APP */
  requiredKeys?: StringList;
}
export const SecretGetOrCreateRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    deploymentName: S.optional(
      S.String.pipe(T.ProtoField({ n: 1, t: "string" })),
    ),
    environmentName: S.optional(
      S.String.pipe(T.ProtoField({ n: 3, t: "string" })),
    ),
    objectCreationType: S.optional(
      ObjectCreationType.pipe(
        T.ProtoField({
          n: 4,
          t: "enum",
          e: {
            OBJECT_CREATION_TYPE_UNSPECIFIED: 0,
            OBJECT_CREATION_TYPE_CREATE_IF_MISSING: 1,
            OBJECT_CREATION_TYPE_CREATE_FAIL_IF_EXISTS: 2,
            OBJECT_CREATION_TYPE_CREATE_OVERWRITE_IF_EXISTS: 3,
            OBJECT_CREATION_TYPE_ANONYMOUS_OWNED_BY_APP: 4,
            OBJECT_CREATION_TYPE_EPHEMERAL: 5,
          },
        }),
      ),
    ),
    envDict: S.optional(
      StringMap.pipe(
        T.ProtoField({ n: 5, t: "map", k: "string", v: { t: "string" } }),
      ),
    ),
    appId: S.optional(S.String.pipe(T.ProtoField({ n: 6, t: "string" }))),
    requiredKeys: S.optional(
      StringList.pipe(T.ProtoField({ n: 7, t: "string", rep: true })),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/SecretGetOrCreate",
      code: 200,
    }),
  ),
).annotate({
  identifier: "SecretGetOrCreateRequest",
}) as any as S.Schema<SecretGetOrCreateRequest>;

export interface SecretGetOrCreateResponse {
  secretId?: string;
  metadata?: SecretMetadata;
}
export const SecretGetOrCreateResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    secretId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    metadata: S.optional(
      SecretMetadata.pipe(T.ProtoField({ n: 2, t: "message" })),
    ),
  }),
).annotate({
  identifier: "SecretGetOrCreateResponse",
}) as any as S.Schema<SecretGetOrCreateResponse>;

export interface UpdateSecretRequestUpdate {
  key?: string;
  value?: string;
}
export const UpdateSecretRequestUpdate = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    key: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    value: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
  }),
).annotate({
  identifier: "UpdateSecretRequestUpdate",
}) as any as S.Schema<UpdateSecretRequestUpdate>;

export type UpdateSecretRequestUpdateList = Array<UpdateSecretRequestUpdate>;
export const UpdateSecretRequestUpdateList = /*@__PURE__*/ S.Array(
  UpdateSecretRequestUpdate,
) as any as S.Schema<UpdateSecretRequestUpdateList>;

export interface UpdateSecretRequest {
  /** If not set, the key is removed. */
  secretId?: string;
  updates?: UpdateSecretRequestUpdateList;
}
export const UpdateSecretRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    secretId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    updates: S.optional(
      UpdateSecretRequestUpdateList.pipe(
        T.ProtoField({ n: 2, t: "message", rep: true }),
      ),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/SecretUpdate",
      code: 200,
    }),
  ),
).annotate({
  identifier: "UpdateSecretRequest",
}) as any as S.Schema<UpdateSecretRequest>;

export interface UpdateSecretResponse {}
export const UpdateSecretResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "UpdateSecretResponse",
}) as any as S.Schema<UpdateSecretResponse>;

export type DeleteSecretError = ModalOpError;
/** Secrets */
export const deleteSecret: API.OperationMethod<
  DeleteSecretRequest,
  DeleteSecretResponse,
  DeleteSecretError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteSecretRequest,
  output: DeleteSecretResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type ListSecretError = ModalOpError;
export const listSecret: API.OperationMethod<
  ListSecretRequest,
  ListSecretResponse,
  ListSecretError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListSecretRequest,
  output: ListSecretResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type SecretGetOrCreateError = ModalOpError;
export const secretGetOrCreate: API.OperationMethod<
  SecretGetOrCreateRequest,
  SecretGetOrCreateResponse,
  SecretGetOrCreateError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: SecretGetOrCreateRequest,
  output: SecretGetOrCreateResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type UpdateSecretError = ModalOpError;
export const updateSecret: API.OperationMethod<
  UpdateSecretRequest,
  UpdateSecretResponse,
  UpdateSecretError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateSecretRequest,
  output: UpdateSecretResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));
