// AUTO-GENERATED by scripts/generate.ts from .generated-specs (modal_proto → smithy). Do not edit.
import * as S from "@rikalabs/distilled-core/schema";
import * as API from "@rikalabs/distilled-core/api";
import * as T from "../traits.ts";
import {
  ModalProtocol,
  type ModalOpError,
  type ModalOpContext,
} from "../protocol.ts";
import { UnknownModalError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { ModalOpError, ModalOpContext };

export interface ServerGetTimeRangeStatsRequest {
  functionId?: string;
  since?: string;
  /** Inclusive. */
  until?: string;
  /** Exclusive. Filter stats for a specific container */
  containerId?: string;
}
export const ServerGetTimeRangeStatsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    functionId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    since: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "wkt", w: "Timestamp" })),
    ),
    until: S.optional(
      S.String.pipe(T.ProtoField({ n: 3, t: "wkt", w: "Timestamp" })),
    ),
    containerId: S.optional(S.String.pipe(T.ProtoField({ n: 4, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/ServerGetTimeRangeStats",
      code: 200,
    }),
  ),
).annotate({
  identifier: "ServerGetTimeRangeStatsRequest",
}) as any as S.Schema<ServerGetTimeRangeStatsRequest>;

export interface ServerGetTimeRangeStatsResponseServerStatusCodeCount {
  statusCode?: number;
  count?: string;
}
export const ServerGetTimeRangeStatsResponseServerStatusCodeCount =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      statusCode: S.optional(
        S.Number.pipe(T.ProtoField({ n: 1, t: "uint32" })),
      ),
      count: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "uint64" }))),
    }),
  ).annotate({
    identifier: "ServerGetTimeRangeStatsResponseServerStatusCodeCount",
  }) as any as S.Schema<ServerGetTimeRangeStatsResponseServerStatusCodeCount>;

export type ServerGetTimeRangeStatsResponseServerStatusCodeCountList =
  Array<ServerGetTimeRangeStatsResponseServerStatusCodeCount>;
export const ServerGetTimeRangeStatsResponseServerStatusCodeCountList =
  /*@__PURE__*/ S.Array(
    ServerGetTimeRangeStatsResponseServerStatusCodeCount,
  ) as any as S.Schema<ServerGetTimeRangeStatsResponseServerStatusCodeCountList>;

export interface StatsPercentile {
  /** The percentile expressed in basis points: 5000 is p50 and 9990 is p99.9. */
  percentileBasisPoints?: number;
  value?: number;
}
export const StatsPercentile = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    percentileBasisPoints: S.optional(
      S.Number.pipe(T.ProtoField({ n: 1, t: "uint32" })),
    ),
    value: S.optional(S.Number.pipe(T.ProtoField({ n: 2, t: "double" }))),
  }),
).annotate({
  identifier: "StatsPercentile",
}) as any as S.Schema<StatsPercentile>;

export type StatsPercentileList = Array<StatsPercentile>;
export const StatsPercentileList = /*@__PURE__*/ S.Array(
  StatsPercentile,
) as any as S.Schema<StatsPercentileList>;

export interface StatsPercentileDistribution {
  /** Unit identifier such as "seconds", "cores", "gibibytes", or "fraction". */
  unit?: string;
  percentiles?: StatsPercentileList;
}
export const StatsPercentileDistribution = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    unit: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    percentiles: S.optional(
      StatsPercentileList.pipe(T.ProtoField({ n: 2, t: "message", rep: true })),
    ),
  }),
).annotate({
  identifier: "StatsPercentileDistribution",
}) as any as S.Schema<StatsPercentileDistribution>;

export type StatsPercentileDistributionMap = {
  [key: string]: StatsPercentileDistribution | undefined;
};
export const StatsPercentileDistributionMap = /*@__PURE__*/ S.Record(
  S.String,
  StatsPercentileDistribution,
) as any as S.Schema<StatsPercentileDistributionMap>;

export type LLMEngine =
  | "LLM_ENGINE_UNSPECIFIED"
  | "LLM_ENGINE_SGLANG"
  | "LLM_ENGINE_VLLM";
export const LLMEngine = S.String;

export type ServerInferenceStatsStatus =
  | "SERVER_INFERENCE_STATS_STATUS_UNSPECIFIED"
  | "SERVER_INFERENCE_STATS_STATUS_AVAILABLE"
  | "SERVER_INFERENCE_STATS_STATUS_NO_DATA"
  | "SERVER_INFERENCE_STATS_STATUS_UNAVAILABLE";
export const ServerInferenceStatsStatus = S.String;

export type DoubleMap = { [key: string]: number | undefined };
export const DoubleMap = /*@__PURE__*/ S.Record(
  S.String,
  S.Number,
) as any as S.Schema<DoubleMap>;

export interface ServerGetTimeRangeStatsResponseServerInferenceStats {
  engine?: LLMEngine;
  status?: ServerInferenceStatsStatus;
  /** Metrics include time_to_first_token, inter_token_latency, and end_to_end_latency, subject to change as requirements evolve. */
  percentileStats?: StatsPercentileDistributionMap;
  /** Metrics include input_tokens_per_second, cached_input_tokens_per_second, and output_tokens_per_second, subject to change as requirements evolve. */
  scalarStats?: DoubleMap;
}
export const ServerGetTimeRangeStatsResponseServerInferenceStats =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      engine: S.optional(
        LLMEngine.pipe(
          T.ProtoField({
            n: 1,
            t: "enum",
            e: {
              LLM_ENGINE_UNSPECIFIED: 0,
              LLM_ENGINE_SGLANG: 1,
              LLM_ENGINE_VLLM: 2,
            },
          }),
        ),
      ),
      status: S.optional(
        ServerInferenceStatsStatus.pipe(
          T.ProtoField({
            n: 2,
            t: "enum",
            e: {
              SERVER_INFERENCE_STATS_STATUS_UNSPECIFIED: 0,
              SERVER_INFERENCE_STATS_STATUS_AVAILABLE: 1,
              SERVER_INFERENCE_STATS_STATUS_NO_DATA: 2,
              SERVER_INFERENCE_STATS_STATUS_UNAVAILABLE: 3,
            },
          }),
        ),
      ),
      percentileStats: S.optional(
        StatsPercentileDistributionMap.pipe(
          T.ProtoField({ n: 3, t: "map", k: "string", v: { t: "message" } }),
        ),
      ),
      scalarStats: S.optional(
        DoubleMap.pipe(
          T.ProtoField({ n: 4, t: "map", k: "string", v: { t: "double" } }),
        ),
      ),
    }),
  ).annotate({
    identifier: "ServerGetTimeRangeStatsResponseServerInferenceStats",
  }) as any as S.Schema<ServerGetTimeRangeStatsResponseServerInferenceStats>;

export interface ServerGetTimeRangeStatsResponse {
  since?: string;
  /** Inclusive. */
  until?: string;
  /** Exclusive. */
  requestCount?: string;
  requestCountByStatusCode?: ServerGetTimeRangeStatsResponseServerStatusCodeCountList;
  requestRatePerSecond?: number;
  /** Metrics include request_latency, subject to change as requirements evolve. */
  requestPercentileStats?: StatsPercentileDistributionMap;
  /** Metrics include startup_time, cpu_usage, memory_usage, and gpu_utilization, subject to change as requirements evolve. */
  containerPercentileStats?: StatsPercentileDistributionMap;
  /** Absent when the image does not contain a supported inference engine. */
  inference?: ServerGetTimeRangeStatsResponseServerInferenceStats;
  /** Container lifecycle counts. Started and errored containers are counted when the corresponding event occurs in the requested time range. Creating containers were enqueued but had not started or finished at the exclusive end of the range. */
  containerStartedCount?: string;
  containerErrorCount?: string;
  containerCreatingAtEndCount?: string;
}
export const ServerGetTimeRangeStatsResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    since: S.optional(
      S.String.pipe(T.ProtoField({ n: 1, t: "wkt", w: "Timestamp" })),
    ),
    until: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "wkt", w: "Timestamp" })),
    ),
    requestCount: S.optional(
      S.String.pipe(T.ProtoField({ n: 3, t: "uint64" })),
    ),
    requestCountByStatusCode: S.optional(
      ServerGetTimeRangeStatsResponseServerStatusCodeCountList.pipe(
        T.ProtoField({ n: 4, t: "message", rep: true }),
      ),
    ),
    requestRatePerSecond: S.optional(
      S.Number.pipe(T.ProtoField({ n: 5, t: "double" })),
    ),
    requestPercentileStats: S.optional(
      StatsPercentileDistributionMap.pipe(
        T.ProtoField({ n: 6, t: "map", k: "string", v: { t: "message" } }),
      ),
    ),
    containerPercentileStats: S.optional(
      StatsPercentileDistributionMap.pipe(
        T.ProtoField({ n: 7, t: "map", k: "string", v: { t: "message" } }),
      ),
    ),
    inference: S.optional(
      ServerGetTimeRangeStatsResponseServerInferenceStats.pipe(
        T.ProtoField({ n: 8, t: "message" }),
      ),
    ),
    containerStartedCount: S.optional(
      S.String.pipe(T.ProtoField({ n: 9, t: "uint64" })),
    ),
    containerErrorCount: S.optional(
      S.String.pipe(T.ProtoField({ n: 10, t: "uint64" })),
    ),
    containerCreatingAtEndCount: S.optional(
      S.String.pipe(T.ProtoField({ n: 11, t: "uint64" })),
    ),
  }),
).annotate({
  identifier: "ServerGetTimeRangeStatsResponse",
}) as any as S.Schema<ServerGetTimeRangeStatsResponse>;

export type ServerGetTimeRangeStatsError = ModalOpError;
/** Servers */
export const serverGetTimeRangeStats: API.OperationMethod<
  ServerGetTimeRangeStatsRequest,
  ServerGetTimeRangeStatsResponse,
  ServerGetTimeRangeStatsError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ServerGetTimeRangeStatsRequest,
  output: ServerGetTimeRangeStatsResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));
