// AUTO-GENERATED by scripts/generate.ts from .generated-specs (modal_proto → smithy). Do not edit.
import * as S from "@distilled.cloud/core/schema";
import * as API from "@distilled.cloud/core/api";
import * as T from "../traits.ts";
import {
  ModalProtocol,
  type ModalOpError,
  type ModalOpContext,
} from "../protocol.ts";
import { UnknownModalError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { ModalOpError, ModalOpContext };

export type StringList = Array<string>;
export const StringList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<StringList>;

export type StringMap = { [key: string]: string | undefined };
export const StringMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<StringMap>;

export interface VolumeMount {
  volumeId?: string;
  mountPath?: string;
  allowBackgroundCommits?: boolean;
  readOnly?: boolean;
  subPath?: string;
}
export const VolumeMount = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    volumeId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    mountPath: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    allowBackgroundCommits: S.optional(
      S.Boolean.pipe(T.ProtoField({ n: 3, t: "bool" })),
    ),
    readOnly: S.optional(S.Boolean.pipe(T.ProtoField({ n: 4, t: "bool" }))),
    subPath: S.optional(S.String.pipe(T.ProtoField({ n: 5, t: "string" }))),
  }),
).annotate({ identifier: "VolumeMount" }) as any as S.Schema<VolumeMount>;

export type VolumeMountList = Array<VolumeMount>;
export const VolumeMountList = /*@__PURE__*/ S.Array(
  VolumeMount,
) as any as S.Schema<VolumeMountList>;

export type NetworkAccessNetworkAccessType =
  | "UNSPECIFIED"
  | "OPEN"
  | "BLOCKED"
  | "ALLOWLIST";
export const NetworkAccessNetworkAccessType = S.String;

export interface NetworkAccess {
  networkAccessType?: NetworkAccessNetworkAccessType | (string & {});
  allowedCidrs?: StringList;
  allowedDomains?: StringList;
}
export const NetworkAccess = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    networkAccessType: S.optional(
      NetworkAccessNetworkAccessType.pipe(
        T.ProtoField({
          n: 1,
          t: "enum",
          e: { UNSPECIFIED: 0, OPEN: 1, BLOCKED: 2, ALLOWLIST: 3 },
        }),
      ),
    ),
    allowedCidrs: S.optional(
      StringList.pipe(T.ProtoField({ n: 2, t: "string", rep: true })),
    ),
    allowedDomains: S.optional(
      StringList.pipe(T.ProtoField({ n: 3, t: "string", rep: true })),
    ),
  }),
).annotate({ identifier: "NetworkAccess" }) as any as S.Schema<NetworkAccess>;

export type PTYInfoPTYType =
  | "PTY_TYPE_UNSPECIFIED"
  | "PTY_TYPE_FUNCTION"
  | "PTY_TYPE_SHELL";
export const PTYInfoPTYType = S.String;

export interface PTYInfo {
  enabled?: boolean;
  /** Soon deprecated */
  winszRows?: number;
  winszCols?: number;
  envTerm?: string;
  envColorterm?: string;
  envTermProgram?: string;
  /** Replace function with shell */
  ptyType?: PTYInfoPTYType | (string & {});
  noTerminateOnIdleStdin?: boolean;
}
export const PTYInfo = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    enabled: S.optional(S.Boolean.pipe(T.ProtoField({ n: 1, t: "bool" }))),
    winszRows: S.optional(S.Number.pipe(T.ProtoField({ n: 2, t: "uint32" }))),
    winszCols: S.optional(S.Number.pipe(T.ProtoField({ n: 3, t: "uint32" }))),
    envTerm: S.optional(S.String.pipe(T.ProtoField({ n: 4, t: "string" }))),
    envColorterm: S.optional(
      S.String.pipe(T.ProtoField({ n: 5, t: "string" })),
    ),
    envTermProgram: S.optional(
      S.String.pipe(T.ProtoField({ n: 6, t: "string" })),
    ),
    ptyType: S.optional(
      PTYInfoPTYType.pipe(
        T.ProtoField({
          n: 7,
          t: "enum",
          e: {
            PTY_TYPE_UNSPECIFIED: 0,
            PTY_TYPE_FUNCTION: 1,
            PTY_TYPE_SHELL: 2,
          },
        }),
      ),
    ),
    noTerminateOnIdleStdin: S.optional(
      S.Boolean.pipe(T.ProtoField({ n: 8, t: "bool" })),
    ),
  }),
).annotate({ identifier: "PTYInfo" }) as any as S.Schema<PTYInfo>;

export interface CreateTaskContainerRequest {
  taskId?: string;
  /** Logical container name. */
  containerName?: string;
  imageId?: string;
  args?: StringList;
  env?: StringMap;
  workdir?: string;
  /** Secret IDs to inject into the container as environment variables. */
  secretIds?: StringList;
  /** Volumes to mount into the container. */
  volumeMounts?: VolumeMountList;
  /** Outbound network policy for the sidecar, independent of the main container. When unset, defaults to open network access. BLOCKED is not accepted: a blocked sidecar has no IP and cannot reach the main container. */
  networkAccess?: NetworkAccess;
  /** Optional PTY info for sidecar. */
  ptyInfo?: PTYInfo;
}
export const CreateTaskContainerRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    taskId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    containerName: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "string" })),
    ),
    imageId: S.optional(S.String.pipe(T.ProtoField({ n: 3, t: "string" }))),
    args: S.optional(
      StringList.pipe(T.ProtoField({ n: 5, t: "string", rep: true })),
    ),
    env: S.optional(
      StringMap.pipe(
        T.ProtoField({ n: 6, t: "map", k: "string", v: { t: "string" } }),
      ),
    ),
    workdir: S.optional(S.String.pipe(T.ProtoField({ n: 7, t: "string" }))),
    secretIds: S.optional(
      StringList.pipe(T.ProtoField({ n: 8, t: "string", rep: true })),
    ),
    volumeMounts: S.optional(
      VolumeMountList.pipe(T.ProtoField({ n: 9, t: "message", rep: true })),
    ),
    networkAccess: S.optional(
      NetworkAccess.pipe(T.ProtoField({ n: 10, t: "message" })),
    ),
    ptyInfo: S.optional(PTYInfo.pipe(T.ProtoField({ n: 11, t: "message" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.task_command_router.TaskCommandRouter/TaskContainerCreate",
      code: 200,
    }),
  ),
).annotate({
  identifier: "CreateTaskContainerRequest",
}) as any as S.Schema<CreateTaskContainerRequest>;

export interface CreateTaskContainerResponse {
  /** Fully qualified container ID (for example, ctr-<ulid>). */
  containerId?: string;
  /** Logical container name associated with this container. */
  containerName?: string;
}
export const CreateTaskContainerResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    containerId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    containerName: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "string" })),
    ),
  }),
).annotate({
  identifier: "CreateTaskContainerResponse",
}) as any as S.Schema<CreateTaskContainerResponse>;

export interface GetTaskContainerRequest {
  taskId?: string;
  containerName?: string;
  /** Include the latest terminated container if the name is no longer active. */
  includeTerminated?: boolean;
}
export const GetTaskContainerRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    taskId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    containerName: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "string" })),
    ),
    includeTerminated: S.optional(
      S.Boolean.pipe(T.ProtoField({ n: 3, t: "bool" })),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.task_command_router.TaskCommandRouter/TaskContainerGet",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetTaskContainerRequest",
}) as any as S.Schema<GetTaskContainerRequest>;

/** Used for both tasks and function outputs */
export type GenericResultGenericStatus =
  | "GENERIC_STATUS_UNSPECIFIED"
  | "GENERIC_STATUS_SUCCESS"
  | "GENERIC_STATUS_FAILURE"
  | "GENERIC_STATUS_TERMINATED"
  | "GENERIC_STATUS_TIMEOUT"
  | "GENERIC_STATUS_INIT_FAILURE"
  | "GENERIC_STATUS_INTERNAL_FAILURE"
  | "GENERIC_STATUS_IDLE_TIMEOUT"
  | "GENERIC_STATUS_MEMORY_MANAGER_EVICTION";
export const GenericResultGenericStatus = S.String;

/** sub-type for generic types like lists */
export interface GenericResult {
  status?: GenericResultGenericStatus;
  /** Status of the task or function output. */
  exception?: string;
  /** Exception message for failures, if available. */
  exitcode?: number;
  /** Status code of the container entrypoint or builder process if it terminates unexpectedly. */
  traceback?: string;
  /** String value of the Python traceback. */
  serializedTb?: string;
  /** Pickled traceback object. */
  tbLineCache?: string;
  /** Pickled line cache for traceback object. */
  data?: string;
  /** Inline data of the result. */
  dataBlobId?: string;
  /** Blob ID for large data. */
  propagationReason?: string;
}
export const GenericResult = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    status: S.optional(
      GenericResultGenericStatus.pipe(
        T.ProtoField({
          n: 1,
          t: "enum",
          e: {
            GENERIC_STATUS_UNSPECIFIED: 0,
            GENERIC_STATUS_SUCCESS: 1,
            GENERIC_STATUS_FAILURE: 2,
            GENERIC_STATUS_TERMINATED: 3,
            GENERIC_STATUS_TIMEOUT: 4,
            GENERIC_STATUS_INIT_FAILURE: 5,
            GENERIC_STATUS_INTERNAL_FAILURE: 6,
            GENERIC_STATUS_IDLE_TIMEOUT: 7,
            GENERIC_STATUS_MEMORY_MANAGER_EVICTION: 8,
          },
        }),
      ),
    ),
    exception: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    exitcode: S.optional(S.Number.pipe(T.ProtoField({ n: 3, t: "int32" }))),
    traceback: S.optional(S.String.pipe(T.ProtoField({ n: 4, t: "string" }))),
    serializedTb: S.optional(
      S.String.pipe(T.ProtoField({ n: 11, t: "bytes" })),
    ),
    tbLineCache: S.optional(S.String.pipe(T.ProtoField({ n: 12, t: "bytes" }))),
    data: S.optional(S.String.pipe(T.ProtoField({ n: 5, t: "bytes" }))),
    dataBlobId: S.optional(S.String.pipe(T.ProtoField({ n: 10, t: "string" }))),
    propagationReason: S.optional(
      S.String.pipe(T.ProtoField({ n: 13, t: "string" })),
    ),
  }),
).annotate({ identifier: "GenericResult" }) as any as S.Schema<GenericResult>;

export interface TaskContainerInfo {
  containerId?: string;
  containerName?: string;
  status?: string;
  result?: GenericResult;
}
export const TaskContainerInfo = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    containerId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    containerName: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "string" })),
    ),
    status: S.optional(S.String.pipe(T.ProtoField({ n: 3, t: "string" }))),
    result: S.optional(
      GenericResult.pipe(T.ProtoField({ n: 4, t: "message" })),
    ),
  }),
).annotate({
  identifier: "TaskContainerInfo",
}) as any as S.Schema<TaskContainerInfo>;

export interface GetTaskContainerResponse {
  container?: TaskContainerInfo;
}
export const GetTaskContainerResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    container: S.optional(
      TaskContainerInfo.pipe(T.ProtoField({ n: 1, t: "message" })),
    ),
  }),
).annotate({
  identifier: "GetTaskContainerResponse",
}) as any as S.Schema<GetTaskContainerResponse>;

export interface ListTaskContainerRequest {
  taskId?: string;
  /** Include all tracked terminated containers in addition to active ones. */
  includeTerminated?: boolean;
}
export const ListTaskContainerRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    taskId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    includeTerminated: S.optional(
      S.Boolean.pipe(T.ProtoField({ n: 2, t: "bool" })),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.task_command_router.TaskCommandRouter/TaskContainerList",
      code: 200,
    }),
  ),
).annotate({
  identifier: "ListTaskContainerRequest",
}) as any as S.Schema<ListTaskContainerRequest>;

export type TaskContainerInfoList = Array<TaskContainerInfo>;
export const TaskContainerInfoList = /*@__PURE__*/ S.Array(
  TaskContainerInfo,
) as any as S.Schema<TaskContainerInfoList>;

export interface ListTaskContainerResponse {
  containers?: TaskContainerInfoList;
}
export const ListTaskContainerResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    containers: S.optional(
      TaskContainerInfoList.pipe(
        T.ProtoField({ n: 1, t: "message", rep: true }),
      ),
    ),
  }),
).annotate({
  identifier: "ListTaskContainerResponse",
}) as any as S.Schema<ListTaskContainerResponse>;

export interface SandboxStdinWriteV2Request {
  taskId?: string;
  offset?: string;
  data?: string;
  eof?: boolean;
}
export const SandboxStdinWriteV2Request = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    taskId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    offset: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "uint64" }))),
    data: S.optional(S.String.pipe(T.ProtoField({ n: 3, t: "bytes" }))),
    eof: S.optional(S.Boolean.pipe(T.ProtoField({ n: 4, t: "bool" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.task_command_router.TaskCommandRouter/SandboxStdinWriteV2",
      code: 200,
    }),
  ),
).annotate({
  identifier: "SandboxStdinWriteV2Request",
}) as any as S.Schema<SandboxStdinWriteV2Request>;

export interface SandboxStdinWriteV2Response {}
export const SandboxStdinWriteV2Response = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "SandboxStdinWriteV2Response",
}) as any as S.Schema<SandboxStdinWriteV2Response>;

export interface SandboxWaitUntilReadyRequest {
  taskId?: string;
  timeout?: number;
}
export const SandboxWaitUntilReadyRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    taskId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    timeout: S.optional(S.Number.pipe(T.ProtoField({ n: 2, t: "float" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.task_command_router.TaskCommandRouter/SandboxWaitUntilReady",
      code: 200,
    }),
  ),
).annotate({
  identifier: "SandboxWaitUntilReadyRequest",
}) as any as S.Schema<SandboxWaitUntilReadyRequest>;

export interface SandboxWaitUntilReadyResponse {
  readyAt?: number;
}
export const SandboxWaitUntilReadyResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    readyAt: S.optional(S.Number.pipe(T.ProtoField({ n: 1, t: "double" }))),
  }),
).annotate({
  identifier: "SandboxWaitUntilReadyResponse",
}) as any as S.Schema<SandboxWaitUntilReadyResponse>;

export interface TaskExecPollRequest {
  /** The ID of the task running the exec'd command. */
  taskId?: string;
  /** The execution ID of the command to wait on. */
  execId?: string;
}
export const TaskExecPollRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    taskId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    execId: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.task_command_router.TaskCommandRouter/TaskExecPoll",
      code: 200,
    }),
  ),
).annotate({
  identifier: "TaskExecPollRequest",
}) as any as S.Schema<TaskExecPollRequest>;

export interface TaskExecPollResponse {
  /** The exit code of the command. */
  code?: number;
  /** The signal that terminated the command. */
  signal?: number;
}
export const TaskExecPollResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    code: S.optional(S.Number.pipe(T.ProtoField({ n: 1, t: "int32" }))),
    signal: S.optional(S.Number.pipe(T.ProtoField({ n: 2, t: "int32" }))),
  }),
).annotate({
  identifier: "TaskExecPollResponse",
}) as any as S.Schema<TaskExecPollResponse>;

export type TaskExecStdoutConfig =
  | "TASK_EXEC_STDOUT_CONFIG_DEVNULL"
  | "TASK_EXEC_STDOUT_CONFIG_PIPE";
export const TaskExecStdoutConfig = S.String;

export type TaskExecStderrConfig =
  | "TASK_EXEC_STDERR_CONFIG_DEVNULL"
  | "TASK_EXEC_STDERR_CONFIG_PIPE"
  | "TASK_EXEC_STDERR_CONFIG_STDOUT";
export const TaskExecStderrConfig = S.String;

export interface TaskExecStartRequest {
  /** The ID of the task to execute the command in. */
  taskId?: string;
  /** Execution ID. This ID will be used to identify the execution for other requests and ensure exec commands are idempotent. */
  execId?: string;
  /** Command arguments to execute. */
  commandArgs?: StringList;
  /** Configures how the stdout of the command will be handled. */
  stdoutConfig?: TaskExecStdoutConfig | (string & {});
  /** Configures how the stderr of the command will be handled. */
  stderrConfig?: TaskExecStderrConfig | (string & {});
  /** Timeout in seconds for the exec'd command to exit. If the command does not exit within this duration, the command will be killed. This is NOT the timeout for the ExecStartRequest RPC to complete. */
  timeoutSecs?: number;
  /** Working directory for the command. */
  workdir?: string;
  /** Secret IDs to mount into the task. */
  secretIds?: StringList;
  /** PTY info for the command. */
  ptyInfo?: PTYInfo;
  /** Enable debugging capabilities on the container runtime. Used only for internal debugging. */
  runtimeDebug?: boolean;
  /** Fully qualified target container ID. Empty targets the main container. */
  containerId?: string;
  /** Environment variables to set directly for the exec'd command. */
  env?: StringMap;
}
export const TaskExecStartRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    taskId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    execId: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    commandArgs: S.optional(
      StringList.pipe(T.ProtoField({ n: 3, t: "string", rep: true })),
    ),
    stdoutConfig: S.optional(
      TaskExecStdoutConfig.pipe(
        T.ProtoField({
          n: 4,
          t: "enum",
          e: {
            TASK_EXEC_STDOUT_CONFIG_DEVNULL: 0,
            TASK_EXEC_STDOUT_CONFIG_PIPE: 1,
          },
        }),
      ),
    ),
    stderrConfig: S.optional(
      TaskExecStderrConfig.pipe(
        T.ProtoField({
          n: 5,
          t: "enum",
          e: {
            TASK_EXEC_STDERR_CONFIG_DEVNULL: 0,
            TASK_EXEC_STDERR_CONFIG_PIPE: 1,
            TASK_EXEC_STDERR_CONFIG_STDOUT: 2,
          },
        }),
      ),
    ),
    timeoutSecs: S.optional(S.Number.pipe(T.ProtoField({ n: 6, t: "uint32" }))),
    workdir: S.optional(S.String.pipe(T.ProtoField({ n: 7, t: "string" }))),
    secretIds: S.optional(
      StringList.pipe(T.ProtoField({ n: 8, t: "string", rep: true })),
    ),
    ptyInfo: S.optional(PTYInfo.pipe(T.ProtoField({ n: 9, t: "message" }))),
    runtimeDebug: S.optional(
      S.Boolean.pipe(T.ProtoField({ n: 10, t: "bool" })),
    ),
    containerId: S.optional(
      S.String.pipe(T.ProtoField({ n: 11, t: "string" })),
    ),
    env: S.optional(
      StringMap.pipe(
        T.ProtoField({ n: 12, t: "map", k: "string", v: { t: "string" } }),
      ),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.task_command_router.TaskCommandRouter/TaskExecStart",
      code: 200,
    }),
  ),
).annotate({
  identifier: "TaskExecStartRequest",
}) as any as S.Schema<TaskExecStartRequest>;

export interface TaskExecStartResponse {}
export const TaskExecStartResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "TaskExecStartResponse",
}) as any as S.Schema<TaskExecStartResponse>;

export interface TaskExecStdinStatusRequest {
  /** The ID of the task running the exec'd command. */
  taskId?: string;
  /** The execution ID of the command to query. */
  execId?: string;
}
export const TaskExecStdinStatusRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    taskId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    execId: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.task_command_router.TaskCommandRouter/TaskExecStdinStatus",
      code: 200,
    }),
  ),
).annotate({
  identifier: "TaskExecStdinStatusRequest",
}) as any as S.Schema<TaskExecStdinStatusRequest>;

export interface TaskExecStdinStatusResponse {
  /** Number of bytes the server has accepted for this exec so far. A streaming client that lost its connection should resume sending at this offset. */
  numBytesWritten?: string;
  /** True if stdin has already been closed (EOF sent) for this exec. */
  closed?: boolean;
}
export const TaskExecStdinStatusResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    numBytesWritten: S.optional(
      S.String.pipe(T.ProtoField({ n: 1, t: "uint64" })),
    ),
    closed: S.optional(S.Boolean.pipe(T.ProtoField({ n: 2, t: "bool" }))),
  }),
).annotate({
  identifier: "TaskExecStdinStatusResponse",
}) as any as S.Schema<TaskExecStdinStatusResponse>;

export interface TaskExecStdinWriteRequest {
  /** The ID of the task running the exec'd command. */
  taskId?: string;
  /** The execution ID of the command to write to. */
  execId?: string;
  /** The offset to start writing to. This is used to resume writing from the last write position if the connection is closed and reopened. */
  offset?: string;
  data?: string;
  /** If true, close the stdin stream after writing any provided data. This signals EOF to the exec'd process. */
  eof?: boolean;
}
export const TaskExecStdinWriteRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    taskId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    execId: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    offset: S.optional(S.String.pipe(T.ProtoField({ n: 3, t: "uint64" }))),
    data: S.optional(S.String.pipe(T.ProtoField({ n: 4, t: "bytes" }))),
    eof: S.optional(S.Boolean.pipe(T.ProtoField({ n: 5, t: "bool" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.task_command_router.TaskCommandRouter/TaskExecStdinWrite",
      code: 200,
    }),
  ),
).annotate({
  identifier: "TaskExecStdinWriteRequest",
}) as any as S.Schema<TaskExecStdinWriteRequest>;

export interface TaskExecStdinWriteResponse {}
export const TaskExecStdinWriteResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "TaskExecStdinWriteResponse",
}) as any as S.Schema<TaskExecStdinWriteResponse>;

export interface TaskExecWaitRequest {
  /** The ID of the task running the exec'd command. */
  taskId?: string;
  /** The execution ID of the command to wait on. */
  execId?: string;
}
export const TaskExecWaitRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    taskId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    execId: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.task_command_router.TaskCommandRouter/TaskExecWait",
      code: 200,
    }),
  ),
).annotate({
  identifier: "TaskExecWaitRequest",
}) as any as S.Schema<TaskExecWaitRequest>;

export interface TaskExecWaitResponse {
  /** The exit code of the command. */
  code?: number;
  /** The signal that terminated the command. */
  signal?: number;
}
export const TaskExecWaitResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    code: S.optional(S.Number.pipe(T.ProtoField({ n: 1, t: "int32" }))),
    signal: S.optional(S.Number.pipe(T.ProtoField({ n: 2, t: "int32" }))),
  }),
).annotate({
  identifier: "TaskExecWaitResponse",
}) as any as S.Schema<TaskExecWaitResponse>;

export interface TaskMountDirectoryRequest {
  taskId?: string;
  path?: string;
  imageId?: string;
  /** Customer-supplied encryption key used to decrypt CSEK-encrypted image metadata keys. This key is not persisted by Modal. */
  customerSuppliedEncryptionKey?: string;
  /** Fully qualified target container ID. Empty targets the main container. */
  containerId?: string;
}
export const TaskMountDirectoryRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    taskId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    path: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "bytes" }))),
    imageId: S.optional(S.String.pipe(T.ProtoField({ n: 3, t: "string" }))),
    customerSuppliedEncryptionKey: S.optional(
      S.String.pipe(T.ProtoField({ n: 4, t: "bytes" })),
    ),
    containerId: S.optional(S.String.pipe(T.ProtoField({ n: 5, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.task_command_router.TaskCommandRouter/TaskMountDirectory",
      code: 200,
    }),
  ),
).annotate({
  identifier: "TaskMountDirectoryRequest",
}) as any as S.Schema<TaskMountDirectoryRequest>;

export interface TaskMountDirectoryResponse {}
export const TaskMountDirectoryResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "TaskMountDirectoryResponse",
}) as any as S.Schema<TaskMountDirectoryResponse>;

export interface TaskReloadVolumesRequest {
  taskId?: string;
  /** Fully qualified target container ID. Empty targets the main container. */
  containerId?: string;
}
export const TaskReloadVolumesRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    taskId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    containerId: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.task_command_router.TaskCommandRouter/TaskReloadVolumes",
      code: 200,
    }),
  ),
).annotate({
  identifier: "TaskReloadVolumesRequest",
}) as any as S.Schema<TaskReloadVolumesRequest>;

export interface TaskReloadVolumesResponse {}
export const TaskReloadVolumesResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "TaskReloadVolumesResponse",
}) as any as S.Schema<TaskReloadVolumesResponse>;

export interface TaskSetNetworkAccessRequest {
  taskId?: string;
  /** Replaces the task's network access policy. Only ALLOWLIST is currently supported; open access is expressed as an allow-all allowlist. */
  networkAccess?: NetworkAccess;
}
export const TaskSetNetworkAccessRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    taskId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    networkAccess: S.optional(
      NetworkAccess.pipe(T.ProtoField({ n: 2, t: "message" })),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.task_command_router.TaskCommandRouter/TaskSetNetworkAccess",
      code: 200,
    }),
  ),
).annotate({
  identifier: "TaskSetNetworkAccessRequest",
}) as any as S.Schema<TaskSetNetworkAccessRequest>;

export interface TaskSetNetworkAccessResponse {}
export const TaskSetNetworkAccessResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "TaskSetNetworkAccessResponse",
}) as any as S.Schema<TaskSetNetworkAccessResponse>;

export interface OutboundPolicyHeaderReplacement {
  /** Domain that the header replacements are scoped to. Supports wildcards in subdomain positions. */
  domain?: string;
  /** Reference to a secret usable in the header value templates. Can be empty if no secret value is used. */
  secretId?: string;
  /** Header name -> header value. Values support templating with keys in the stanza's secret_id: a $-prefixed key name in the secret will be replaced with the secret value. Literal $ characters can be represented by two dollars: `$$`. */
  headers?: StringMap;
}
export const OutboundPolicyHeaderReplacement = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    domain: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    secretId: S.optional(S.String.pipe(T.ProtoField({ n: 4, t: "string" }))),
    headers: S.optional(
      StringMap.pipe(
        T.ProtoField({ n: 5, t: "map", k: "string", v: { t: "string" } }),
      ),
    ),
  }),
).annotate({
  identifier: "OutboundPolicyHeaderReplacement",
}) as any as S.Schema<OutboundPolicyHeaderReplacement>;

export type OutboundPolicyHeaderReplacementList =
  Array<OutboundPolicyHeaderReplacement>;
export const OutboundPolicyHeaderReplacementList = /*@__PURE__*/ S.Array(
  OutboundPolicyHeaderReplacement,
) as any as S.Schema<OutboundPolicyHeaderReplacementList>;

/** Policy for outbound traffic from a sandbox. */
export interface OutboundPolicy {
  /** Replace headers in outbound HTTPS requests, potentially with secret values. */
  headerReplacements?: OutboundPolicyHeaderReplacementList;
}
export const OutboundPolicy = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    headerReplacements: S.optional(
      OutboundPolicyHeaderReplacementList.pipe(
        T.ProtoField({ n: 1, t: "message", rep: true }),
      ),
    ),
  }),
).annotate({ identifier: "OutboundPolicy" }) as any as S.Schema<OutboundPolicy>;

export interface TaskSetOutboundPolicyRequest {
  taskId?: string;
  /** Replaces the task's outbound policy. */
  outboundPolicy?: OutboundPolicy;
}
export const TaskSetOutboundPolicyRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    taskId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    outboundPolicy: S.optional(
      OutboundPolicy.pipe(T.ProtoField({ n: 2, t: "message" })),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.task_command_router.TaskCommandRouter/TaskSetOutboundPolicy",
      code: 200,
    }),
  ),
).annotate({
  identifier: "TaskSetOutboundPolicyRequest",
}) as any as S.Schema<TaskSetOutboundPolicyRequest>;

export interface TaskSetOutboundPolicyResponse {}
export const TaskSetOutboundPolicyResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "TaskSetOutboundPolicyResponse",
}) as any as S.Schema<TaskSetOutboundPolicyResponse>;

export interface TaskSnapshotDirectoryRequest {
  taskId?: string;
  path?: string;
  /** A unique ID to ensure idempotency of directory snapshot requests. */
  snapshotId?: string;
  /** Lifetime for the resulting image, in seconds. When set, the image's expires_at is a hard cutoff: it is fixed at creation time and is not extended on use. When unset, the resulting image gets the legacy retention policy: a 30-day TTL that is bumped forward by 30 days on every use, so active images effectively never expire. Sentinel: -1 means "no expiry" (the image never expires). 0 and other negative values are invalid and rejected by the server. */
  ttlSeconds?: string;
  /** Customer-supplied encryption key used to encrypt the resulting image's data and tree metadata keys. This key is not persisted by Modal. */
  customerSuppliedEncryptionKey?: string;
  /** Fully qualified target container ID. Empty targets the main container. */
  containerId?: string;
}
export const TaskSnapshotDirectoryRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    taskId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    path: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "bytes" }))),
    snapshotId: S.optional(S.String.pipe(T.ProtoField({ n: 3, t: "string" }))),
    ttlSeconds: S.optional(S.String.pipe(T.ProtoField({ n: 4, t: "int64" }))),
    customerSuppliedEncryptionKey: S.optional(
      S.String.pipe(T.ProtoField({ n: 5, t: "bytes" })),
    ),
    containerId: S.optional(S.String.pipe(T.ProtoField({ n: 6, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.task_command_router.TaskCommandRouter/TaskSnapshotDirectory",
      code: 200,
    }),
  ),
).annotate({
  identifier: "TaskSnapshotDirectoryRequest",
}) as any as S.Schema<TaskSnapshotDirectoryRequest>;

export interface TaskSnapshotDirectoryResponse {
  imageId?: string;
}
export const TaskSnapshotDirectoryResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    imageId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
  }),
).annotate({
  identifier: "TaskSnapshotDirectoryResponse",
}) as any as S.Schema<TaskSnapshotDirectoryResponse>;

export interface TaskSnapshotFilesystemRequest {
  taskId?: string;
  /** A unique ID to ensure idempotency of filesystem snapshot requests. */
  snapshotId?: string;
  /** Lifetime for the resulting image, in seconds. Must be set. When positive, the image expiry is a hard cutoff: it is fixed at creation time and is not extended on use. Sentinel: -1 means "no expiry" (the image never expires). 0 and other negative values are invalid and rejected by the server. */
  ttlSeconds?: string;
  /** Customer-supplied encryption key used to encrypt the resulting image's data and tree metadata keys. This key is not persisted by Modal. */
  customerSuppliedEncryptionKey?: string;
  /** Fully qualified target container ID. Empty targets the main container. */
  containerId?: string;
}
export const TaskSnapshotFilesystemRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    taskId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    snapshotId: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    ttlSeconds: S.optional(S.String.pipe(T.ProtoField({ n: 3, t: "int64" }))),
    customerSuppliedEncryptionKey: S.optional(
      S.String.pipe(T.ProtoField({ n: 4, t: "bytes" })),
    ),
    containerId: S.optional(S.String.pipe(T.ProtoField({ n: 5, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.task_command_router.TaskCommandRouter/TaskSnapshotFilesystem",
      code: 200,
    }),
  ),
).annotate({
  identifier: "TaskSnapshotFilesystemRequest",
}) as any as S.Schema<TaskSnapshotFilesystemRequest>;

export interface TaskSnapshotFilesystemResponse {
  imageId?: string;
}
export const TaskSnapshotFilesystemResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    imageId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
  }),
).annotate({
  identifier: "TaskSnapshotFilesystemResponse",
}) as any as S.Schema<TaskSnapshotFilesystemResponse>;

export interface TaskSnapshotMemoryRequest {
  taskId?: string;
  idempotencyKey?: string;
}
export const TaskSnapshotMemoryRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    taskId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    idempotencyKey: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "string" })),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.task_command_router.TaskCommandRouter/TaskSnapshotMemory",
      code: 200,
    }),
  ),
).annotate({
  identifier: "TaskSnapshotMemoryRequest",
}) as any as S.Schema<TaskSnapshotMemoryRequest>;

export interface TaskSnapshotMemoryResponse {
  snapshotId?: string;
}
export const TaskSnapshotMemoryResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    snapshotId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
  }),
).annotate({
  identifier: "TaskSnapshotMemoryResponse",
}) as any as S.Schema<TaskSnapshotMemoryResponse>;

export interface TaskUnmountDirectoryRequest {
  taskId?: string;
  path?: string;
  /** Fully qualified target container ID. Empty targets the main container. */
  containerId?: string;
}
export const TaskUnmountDirectoryRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    taskId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    path: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "bytes" }))),
    containerId: S.optional(S.String.pipe(T.ProtoField({ n: 3, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.task_command_router.TaskCommandRouter/TaskUnmountDirectory",
      code: 200,
    }),
  ),
).annotate({
  identifier: "TaskUnmountDirectoryRequest",
}) as any as S.Schema<TaskUnmountDirectoryRequest>;

export interface TaskUnmountDirectoryResponse {}
export const TaskUnmountDirectoryResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "TaskUnmountDirectoryResponse",
}) as any as S.Schema<TaskUnmountDirectoryResponse>;

export interface TerminateTaskContainerRequest {
  taskId?: string;
  containerId?: string;
}
export const TerminateTaskContainerRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    taskId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    containerId: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.task_command_router.TaskCommandRouter/TaskContainerTerminate",
      code: 200,
    }),
  ),
).annotate({
  identifier: "TerminateTaskContainerRequest",
}) as any as S.Schema<TerminateTaskContainerRequest>;

export interface TerminateTaskContainerResponse {}
export const TerminateTaskContainerResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "TerminateTaskContainerResponse",
}) as any as S.Schema<TerminateTaskContainerResponse>;

export interface WaitTaskContainerRequest {
  taskId?: string;
  containerId?: string;
  timeout?: number;
}
export const WaitTaskContainerRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    taskId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    containerId: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
    timeout: S.optional(S.Number.pipe(T.ProtoField({ n: 3, t: "float" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.task_command_router.TaskCommandRouter/TaskContainerWait",
      code: 200,
    }),
  ),
).annotate({
  identifier: "WaitTaskContainerRequest",
}) as any as S.Schema<WaitTaskContainerRequest>;

export interface WaitTaskContainerResponse {
  result?: GenericResult;
}
export const WaitTaskContainerResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    result: S.optional(
      GenericResult.pipe(T.ProtoField({ n: 1, t: "message" })),
    ),
  }),
).annotate({
  identifier: "WaitTaskContainerResponse",
}) as any as S.Schema<WaitTaskContainerResponse>;

export type CreateTaskContainerError = ModalOpError;
/** Create an additional container for a task. */
export const createTaskContainer: API.OperationMethod<
  CreateTaskContainerRequest,
  CreateTaskContainerResponse,
  CreateTaskContainerError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateTaskContainerRequest,
  output: CreateTaskContainerResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type GetTaskContainerError = ModalOpError;
/** Get the latest container associated with a logical name. */
export const getTaskContainer: API.OperationMethod<
  GetTaskContainerRequest,
  GetTaskContainerResponse,
  GetTaskContainerError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetTaskContainerRequest,
  output: GetTaskContainerResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type ListTaskContainerError = ModalOpError;
/** List containers associated with the task. */
export const listTaskContainer: API.OperationMethod<
  ListTaskContainerRequest,
  ListTaskContainerResponse,
  ListTaskContainerError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListTaskContainerRequest,
  output: ListTaskContainerResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type SandboxStdinWriteV2Error = ModalOpError;
export const sandboxStdinWriteV2: API.OperationMethod<
  SandboxStdinWriteV2Request,
  SandboxStdinWriteV2Response,
  SandboxStdinWriteV2Error,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: SandboxStdinWriteV2Request,
  output: SandboxStdinWriteV2Response,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type SandboxWaitUntilReadyError = ModalOpError;
export const sandboxWaitUntilReady: API.OperationMethod<
  SandboxWaitUntilReadyRequest,
  SandboxWaitUntilReadyResponse,
  SandboxWaitUntilReadyError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: SandboxWaitUntilReadyRequest,
  output: SandboxWaitUntilReadyResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type TaskExecPollError = ModalOpError;
/** Poll for the exit status of an exec'd command. */
export const taskExecPoll: API.OperationMethod<
  TaskExecPollRequest,
  TaskExecPollResponse,
  TaskExecPollError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: TaskExecPollRequest,
  output: TaskExecPollResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type TaskExecStartError = ModalOpError;
/** Execute a command in the task. */
export const taskExecStart: API.OperationMethod<
  TaskExecStartRequest,
  TaskExecStartResponse,
  TaskExecStartError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: TaskExecStartRequest,
  output: TaskExecStartResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type TaskExecStdinStatusError = ModalOpError;
/** Get the current stdin write status for an exec'd command. Used to resume a TaskExecStdinWriteStream after a stream failure. Evicts any in-flight TaskExecStdinWriteStream for this exec, so it is not safe to call for read-only observability. */
export const taskExecStdinStatus: API.OperationMethod<
  TaskExecStdinStatusRequest,
  TaskExecStdinStatusResponse,
  TaskExecStdinStatusError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: TaskExecStdinStatusRequest,
  output: TaskExecStdinStatusResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type TaskExecStdinWriteError = ModalOpError;
/** Write to the stdin stream of an exec'd command. */
export const taskExecStdinWrite: API.OperationMethod<
  TaskExecStdinWriteRequest,
  TaskExecStdinWriteResponse,
  TaskExecStdinWriteError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: TaskExecStdinWriteRequest,
  output: TaskExecStdinWriteResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type TaskExecWaitError = ModalOpError;
/** Wait for an exec'd command to exit and return the exit code. */
export const taskExecWait: API.OperationMethod<
  TaskExecWaitRequest,
  TaskExecWaitResponse,
  TaskExecWaitError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: TaskExecWaitRequest,
  output: TaskExecWaitResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type TaskMountDirectoryError = ModalOpError;
/** Mount an image at a directory in the container. */
export const taskMountDirectory: API.OperationMethod<
  TaskMountDirectoryRequest,
  TaskMountDirectoryResponse,
  TaskMountDirectoryError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: TaskMountDirectoryRequest,
  output: TaskMountDirectoryResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type TaskReloadVolumesError = ModalOpError;
/** Reload all Volumes mounted in the task to reflect their latest committed state. */
export const taskReloadVolumes: API.OperationMethod<
  TaskReloadVolumesRequest,
  TaskReloadVolumesResponse,
  TaskReloadVolumesError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: TaskReloadVolumesRequest,
  output: TaskReloadVolumesResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type TaskSetNetworkAccessError = ModalOpError;
/** Replace the task's outbound network allowlist (domains + CIDRs). */
export const taskSetNetworkAccess: API.OperationMethod<
  TaskSetNetworkAccessRequest,
  TaskSetNetworkAccessResponse,
  TaskSetNetworkAccessError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: TaskSetNetworkAccessRequest,
  output: TaskSetNetworkAccessResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type TaskSetOutboundPolicyError = ModalOpError;
/** Replace the task's outbound policy. */
export const taskSetOutboundPolicy: API.OperationMethod<
  TaskSetOutboundPolicyRequest,
  TaskSetOutboundPolicyResponse,
  TaskSetOutboundPolicyError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: TaskSetOutboundPolicyRequest,
  output: TaskSetOutboundPolicyResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type TaskSnapshotDirectoryError = ModalOpError;
/** Snapshot a directory with a mounted image, including any local changes, into a new image. */
export const taskSnapshotDirectory: API.OperationMethod<
  TaskSnapshotDirectoryRequest,
  TaskSnapshotDirectoryResponse,
  TaskSnapshotDirectoryError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: TaskSnapshotDirectoryRequest,
  output: TaskSnapshotDirectoryResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type TaskSnapshotFilesystemError = ModalOpError;
/** Snapshot the full task filesystem into a new image. */
export const taskSnapshotFilesystem: API.OperationMethod<
  TaskSnapshotFilesystemRequest,
  TaskSnapshotFilesystemResponse,
  TaskSnapshotFilesystemError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: TaskSnapshotFilesystemRequest,
  output: TaskSnapshotFilesystemResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type TaskSnapshotMemoryError = ModalOpError;
/** Take a memory snapshot of the task's sandbox container. Idempotency is keyed on the request idempotency_key: concurrent and repeated calls with the same key share one snapshot attempt. A successful snapshot currently terminates the container. */
export const taskSnapshotMemory: API.OperationMethod<
  TaskSnapshotMemoryRequest,
  TaskSnapshotMemoryResponse,
  TaskSnapshotMemoryError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: TaskSnapshotMemoryRequest,
  output: TaskSnapshotMemoryResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type TaskUnmountDirectoryError = ModalOpError;
/** Unmount an image previously mounted at a directory in the container. */
export const taskUnmountDirectory: API.OperationMethod<
  TaskUnmountDirectoryRequest,
  TaskUnmountDirectoryResponse,
  TaskUnmountDirectoryError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: TaskUnmountDirectoryRequest,
  output: TaskUnmountDirectoryResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type TerminateTaskContainerError = ModalOpError;
/** Terminate or release a tracked container. */
export const terminateTaskContainer: API.OperationMethod<
  TerminateTaskContainerRequest,
  TerminateTaskContainerResponse,
  TerminateTaskContainerError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: TerminateTaskContainerRequest,
  output: TerminateTaskContainerResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type WaitTaskContainerError = ModalOpError;
/** Wait for a tracked container to reach a terminal result. */
export const waitTaskContainer: API.OperationMethod<
  WaitTaskContainerRequest,
  WaitTaskContainerResponse,
  WaitTaskContainerError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: WaitTaskContainerRequest,
  output: WaitTaskContainerResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));
