// AUTO-GENERATED by scripts/generate.ts from .generated-specs (modal_proto → smithy). Do not edit.
import * as S from "@rikalabs/distilled-core/schema";
import * as API from "@rikalabs/distilled-core/api";
import * as T from "../traits.ts";
import {
  ModalProtocol,
  type ModalOpError,
  type ModalOpContext,
} from "../protocol.ts";
import { UnknownModalError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { ModalOpError, ModalOpContext };

export interface GetWorkspaceDashboardUrlRequest {
  environmentName?: string;
}
export const GetWorkspaceDashboardUrlRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    environmentName: S.optional(
      S.String.pipe(T.ProtoField({ n: 1, t: "string" })),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/WorkspaceDashboardUrlGet",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetWorkspaceDashboardUrlRequest",
}) as any as S.Schema<GetWorkspaceDashboardUrlRequest>;

export interface GetWorkspaceDashboardUrlResponse {
  url?: string;
}
export const GetWorkspaceDashboardUrlResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    url: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
  }),
).annotate({
  identifier: "GetWorkspaceDashboardUrlResponse",
}) as any as S.Schema<GetWorkspaceDashboardUrlResponse>;

export interface ListWorkspaceMembersRequest {}
export const ListWorkspaceMembersRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/WorkspaceMembersList",
      code: 200,
    }),
  ),
).annotate({
  identifier: "ListWorkspaceMembersRequest",
}) as any as S.Schema<ListWorkspaceMembersRequest>;

export type MemberRole =
  | "MEMBER_ROLE_UNSPECIFIED"
  | "MEMBER_ROLE_USER"
  | "MEMBER_ROLE_MANAGER"
  | "MEMBER_ROLE_OWNER";
export const MemberRole = S.String;

export type IdentityProviderType =
  | "IDENTITY_PROVIDER_TYPE_UNSPECIFIED"
  | "IDENTITY_PROVIDER_TYPE_GITHUB"
  | "IDENTITY_PROVIDER_TYPE_SAML"
  | "IDENTITY_PROVIDER_TYPE_OKTA"
  | "IDENTITY_PROVIDER_TYPE_GOOGLE_OAUTH";
export const IdentityProviderType = S.String;

export interface WorkspaceMembersListItem {
  memberId?: string;
  memberDisplayname?: string;
  memberRole?: MemberRole;
  joinedAt?: number;
  lastActiveAt?: number;
  deletedAt?: number;
  userId?: string;
  identityProviderType?: IdentityProviderType;
  email?: string;
  avatarUrl?: string;
  idpExternalId?: string;
}
export const WorkspaceMembersListItem = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    memberId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    memberDisplayname: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "string" })),
    ),
    memberRole: S.optional(
      MemberRole.pipe(
        T.ProtoField({
          n: 3,
          t: "enum",
          e: {
            MEMBER_ROLE_UNSPECIFIED: 0,
            MEMBER_ROLE_USER: 1,
            MEMBER_ROLE_MANAGER: 2,
            MEMBER_ROLE_OWNER: 3,
          },
        }),
      ),
    ),
    joinedAt: S.optional(S.Number.pipe(T.ProtoField({ n: 4, t: "double" }))),
    lastActiveAt: S.optional(
      S.Number.pipe(T.ProtoField({ n: 5, t: "double" })),
    ),
    deletedAt: S.optional(S.Number.pipe(T.ProtoField({ n: 7, t: "double" }))),
    userId: S.optional(S.String.pipe(T.ProtoField({ n: 8, t: "string" }))),
    identityProviderType: S.optional(
      IdentityProviderType.pipe(
        T.ProtoField({
          n: 9,
          t: "enum",
          e: {
            IDENTITY_PROVIDER_TYPE_UNSPECIFIED: 0,
            IDENTITY_PROVIDER_TYPE_GITHUB: 1,
            IDENTITY_PROVIDER_TYPE_SAML: 2,
            IDENTITY_PROVIDER_TYPE_OKTA: 2,
            IDENTITY_PROVIDER_TYPE_GOOGLE_OAUTH: 3,
          },
        }),
      ),
    ),
    email: S.optional(S.String.pipe(T.ProtoField({ n: 10, t: "string" }))),
    avatarUrl: S.optional(S.String.pipe(T.ProtoField({ n: 11, t: "string" }))),
    idpExternalId: S.optional(
      S.String.pipe(T.ProtoField({ n: 12, t: "string" })),
    ),
  }),
).annotate({
  identifier: "WorkspaceMembersListItem",
}) as any as S.Schema<WorkspaceMembersListItem>;

export type WorkspaceMembersListItemList = Array<WorkspaceMembersListItem>;
export const WorkspaceMembersListItemList = /*@__PURE__*/ S.Array(
  WorkspaceMembersListItem,
) as any as S.Schema<WorkspaceMembersListItemList>;

export interface ListWorkspaceMembersResponse {
  members?: WorkspaceMembersListItemList;
}
export const ListWorkspaceMembersResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    members: S.optional(
      WorkspaceMembersListItemList.pipe(
        T.ProtoField({ n: 1, t: "message", rep: true }),
      ),
    ),
  }),
).annotate({
  identifier: "ListWorkspaceMembersResponse",
}) as any as S.Schema<ListWorkspaceMembersResponse>;

export interface LookupWorkspaceNameRequest {}
export const LookupWorkspaceNameRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/WorkspaceNameLookup",
      code: 200,
    }),
  ),
).annotate({
  identifier: "LookupWorkspaceNameRequest",
}) as any as S.Schema<LookupWorkspaceNameRequest>;

export interface LookupWorkspaceNameResponse {
  workspaceName?: string;
  username?: string;
}
export const LookupWorkspaceNameResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    workspaceName: S.optional(
      S.String.pipe(T.ProtoField({ n: 1, t: "string" })),
    ),
    username: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
  }),
).annotate({
  identifier: "LookupWorkspaceNameResponse",
}) as any as S.Schema<LookupWorkspaceNameResponse>;

export interface WorkspaceBillingRatesRequest {}
export const WorkspaceBillingRatesRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/WorkspaceBillingRates",
      code: 200,
    }),
  ),
).annotate({
  identifier: "WorkspaceBillingRatesRequest",
}) as any as S.Schema<WorkspaceBillingRatesRequest>;

export type StringMap = { [key: string]: string | undefined };
export const StringMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<StringMap>;

export interface WorkspaceBillingRatesResponse {
  /** compute rates are per unit per hour, storage rate is per GiB-month */
  rates?: StringMap;
  deprecationWarnings?: StringMap;
  deprecationErrors?: StringMap;
  formatted?: string;
}
export const WorkspaceBillingRatesResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    rates: S.optional(
      StringMap.pipe(
        T.ProtoField({ n: 1, t: "map", k: "string", v: { t: "string" } }),
      ),
    ),
    deprecationWarnings: S.optional(
      StringMap.pipe(
        T.ProtoField({ n: 2, t: "map", k: "string", v: { t: "string" } }),
      ),
    ),
    deprecationErrors: S.optional(
      StringMap.pipe(
        T.ProtoField({ n: 3, t: "map", k: "string", v: { t: "string" } }),
      ),
    ),
    formatted: S.optional(S.String.pipe(T.ProtoField({ n: 4, t: "string" }))),
  }),
).annotate({
  identifier: "WorkspaceBillingRatesResponse",
}) as any as S.Schema<WorkspaceBillingRatesResponse>;

export interface WorkspaceBillingSummaryRequest {
  /** all query intervals are implicitly one month long (to line up with billing cycles) */
  startTimestamp?: string;
}
export const WorkspaceBillingSummaryRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    startTimestamp: S.optional(
      S.String.pipe(T.ProtoField({ n: 1, t: "wkt", w: "Timestamp" })),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/WorkspaceBillingSummary",
      code: 200,
    }),
  ),
).annotate({
  identifier: "WorkspaceBillingSummaryRequest",
}) as any as S.Schema<WorkspaceBillingSummaryRequest>;

export interface WorkspaceBillingSummaryResponse {
  startTimestamp?: string;
  endTimestamp?: string;
  meteredCost?: string;
  billedCost?: string;
  /** keyed by deployed, ephemeral, volume, notebook, tokens */
  meteredCostBreakdown?: StringMap;
  /** keyed by plan, credits, reservations, storage */
  adjustments?: StringMap;
}
export const WorkspaceBillingSummaryResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    startTimestamp: S.optional(
      S.String.pipe(T.ProtoField({ n: 1, t: "wkt", w: "Timestamp" })),
    ),
    endTimestamp: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "wkt", w: "Timestamp" })),
    ),
    meteredCost: S.optional(S.String.pipe(T.ProtoField({ n: 3, t: "string" }))),
    billedCost: S.optional(S.String.pipe(T.ProtoField({ n: 4, t: "string" }))),
    meteredCostBreakdown: S.optional(
      StringMap.pipe(
        T.ProtoField({ n: 5, t: "map", k: "string", v: { t: "string" } }),
      ),
    ),
    adjustments: S.optional(
      StringMap.pipe(
        T.ProtoField({ n: 6, t: "map", k: "string", v: { t: "string" } }),
      ),
    ),
  }),
).annotate({
  identifier: "WorkspaceBillingSummaryResponse",
}) as any as S.Schema<WorkspaceBillingSummaryResponse>;

export interface WorkspaceSetDefaultEnvironmentRequest {
  environmentName?: string;
}
export const WorkspaceSetDefaultEnvironmentRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      environmentName: S.optional(
        S.String.pipe(T.ProtoField({ n: 1, t: "string" })),
      ),
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/modal.client.ModalClient/WorkspaceSetDefaultEnvironment",
        code: 200,
      }),
    ),
).annotate({
  identifier: "WorkspaceSetDefaultEnvironmentRequest",
}) as any as S.Schema<WorkspaceSetDefaultEnvironmentRequest>;

export interface WorkspaceSetDefaultEnvironmentResponse {}
export const WorkspaceSetDefaultEnvironmentResponse = /*@__PURE__*/ S.suspend(
  () => S.Struct({}),
).annotate({
  identifier: "WorkspaceSetDefaultEnvironmentResponse",
}) as any as S.Schema<WorkspaceSetDefaultEnvironmentResponse>;

/** Partial-update signal for EnvironmentUpdateRequest. Omitted means no-op. INHERIT clears the environment override so the workspace default applies. */
export type EnvironmentBlockUnauthenticatedResources =
  | "ENVIRONMENT_BLOCK_UNAUTHENTICATED_RESOURCES_UNSPECIFIED"
  | "ENVIRONMENT_BLOCK_UNAUTHENTICATED_RESOURCES_INHERIT"
  | "ENVIRONMENT_BLOCK_UNAUTHENTICATED_RESOURCES_BLOCK"
  | "ENVIRONMENT_BLOCK_UNAUTHENTICATED_RESOURCES_ALLOW";
export const EnvironmentBlockUnauthenticatedResources = S.String;

export interface WorkspaceSetDefaultEnvironmentSettingsRequest {
  /** Omitted = no-op. INHERIT clears the workspace default so environments with no override have no block. Rejects UNSPECIFIED. */
  blockUnauthenticatedResources?:
    | EnvironmentBlockUnauthenticatedResources
    | (string & {});
}
export const WorkspaceSetDefaultEnvironmentSettingsRequest =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      blockUnauthenticatedResources: S.optional(
        EnvironmentBlockUnauthenticatedResources.pipe(
          T.ProtoField({
            n: 1,
            t: "enum",
            e: {
              ENVIRONMENT_BLOCK_UNAUTHENTICATED_RESOURCES_UNSPECIFIED: 0,
              ENVIRONMENT_BLOCK_UNAUTHENTICATED_RESOURCES_INHERIT: 1,
              ENVIRONMENT_BLOCK_UNAUTHENTICATED_RESOURCES_BLOCK: 2,
              ENVIRONMENT_BLOCK_UNAUTHENTICATED_RESOURCES_ALLOW: 3,
            },
          }),
        ),
      ),
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/modal.client.ModalClient/WorkspaceSetDefaultEnvironmentSettings",
        code: 200,
      }),
    ),
  ).annotate({
    identifier: "WorkspaceSetDefaultEnvironmentSettingsRequest",
  }) as any as S.Schema<WorkspaceSetDefaultEnvironmentSettingsRequest>;

/** Environment-scoped settings, with workspace-level defaults. Note that we use MergeFrom to combine workspace / environment settings, which will *append* any `repeated` fields! */
export interface EnvironmentSettings {
  imageBuilderVersion?: string;
  webhookSuffix?: string;
  maxConcurrentGpus?: number;
  maxConcurrentTasks?: number;
  /** When true, new unauthenticated web functions, Servers, tunnels, and Endpoints in this environment are rejected. Unset inherits the workspace default. */
  blockUnauthenticatedResources?: boolean;
}
export const EnvironmentSettings = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    imageBuilderVersion: S.optional(
      S.String.pipe(T.ProtoField({ n: 1, t: "string" })),
    ),
    webhookSuffix: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "string" })),
    ),
    maxConcurrentGpus: S.optional(
      S.Number.pipe(T.ProtoField({ n: 3, t: "int32" })),
    ),
    maxConcurrentTasks: S.optional(
      S.Number.pipe(T.ProtoField({ n: 4, t: "int32" })),
    ),
    blockUnauthenticatedResources: S.optional(
      S.Boolean.pipe(T.ProtoField({ n: 5, t: "bool" })),
    ),
  }),
).annotate({
  identifier: "EnvironmentSettings",
}) as any as S.Schema<EnvironmentSettings>;

export interface WorkspaceSetDefaultEnvironmentSettingsResponse {
  defaultEnvironmentSettings?: EnvironmentSettings;
}
export const WorkspaceSetDefaultEnvironmentSettingsResponse =
  /*@__PURE__*/ S.suspend(() =>
    S.Struct({
      defaultEnvironmentSettings: S.optional(
        EnvironmentSettings.pipe(T.ProtoField({ n: 1, t: "message" })),
      ),
    }),
  ).annotate({
    identifier: "WorkspaceSetDefaultEnvironmentSettingsResponse",
  }) as any as S.Schema<WorkspaceSetDefaultEnvironmentSettingsResponse>;

export interface WorkspaceSetImageBuilderVersionRequest {
  newImageBuilderVersion?: string;
}
export const WorkspaceSetImageBuilderVersionRequest = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      newImageBuilderVersion: S.optional(
        S.String.pipe(T.ProtoField({ n: 1, t: "string" })),
      ),
    }).pipe(
      T.Http({
        method: "POST",
        uri: "/modal.client.ModalClient/WorkspaceSetImageBuilderVersion",
        code: 200,
      }),
    ),
).annotate({
  identifier: "WorkspaceSetImageBuilderVersionRequest",
}) as any as S.Schema<WorkspaceSetImageBuilderVersionRequest>;

export interface WorkspaceSetImageBuilderVersionResponse {
  imageBuilderVersion?: string;
}
export const WorkspaceSetImageBuilderVersionResponse = /*@__PURE__*/ S.suspend(
  () =>
    S.Struct({
      imageBuilderVersion: S.optional(
        S.String.pipe(T.ProtoField({ n: 1, t: "string" })),
      ),
    }),
).annotate({
  identifier: "WorkspaceSetImageBuilderVersionResponse",
}) as any as S.Schema<WorkspaceSetImageBuilderVersionResponse>;

export interface WorkspaceSettingsRequest {}
export const WorkspaceSettingsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(
    T.Http({
      method: "POST",
      uri: "/modal.client.ModalClient/WorkspaceSettings",
      code: 200,
    }),
  ),
).annotate({
  identifier: "WorkspaceSettingsRequest",
}) as any as S.Schema<WorkspaceSettingsRequest>;

export interface WorkspaceSettingsResponse {
  defaultEnvironmentName?: string;
  imageBuilderVersion?: string;
}
export const WorkspaceSettingsResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    defaultEnvironmentName: S.optional(
      S.String.pipe(T.ProtoField({ n: 1, t: "string" })),
    ),
    imageBuilderVersion: S.optional(
      S.String.pipe(T.ProtoField({ n: 2, t: "string" })),
    ),
  }),
).annotate({
  identifier: "WorkspaceSettingsResponse",
}) as any as S.Schema<WorkspaceSettingsResponse>;

export type GetWorkspaceDashboardUrlError = ModalOpError;
export const getWorkspaceDashboardUrl: API.OperationMethod<
  GetWorkspaceDashboardUrlRequest,
  GetWorkspaceDashboardUrlResponse,
  GetWorkspaceDashboardUrlError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetWorkspaceDashboardUrlRequest,
  output: GetWorkspaceDashboardUrlResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type ListWorkspaceMembersError = ModalOpError;
export const listWorkspaceMembers: API.OperationMethod<
  ListWorkspaceMembersRequest,
  ListWorkspaceMembersResponse,
  ListWorkspaceMembersError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListWorkspaceMembersRequest,
  output: ListWorkspaceMembersResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type LookupWorkspaceNameError = ModalOpError;
export const lookupWorkspaceName: API.OperationMethod<
  LookupWorkspaceNameRequest,
  LookupWorkspaceNameResponse,
  LookupWorkspaceNameError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: LookupWorkspaceNameRequest,
  output: LookupWorkspaceNameResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type WorkspaceBillingRatesError = ModalOpError;
/** Workspaces */
export const workspaceBillingRates: API.OperationMethod<
  WorkspaceBillingRatesRequest,
  WorkspaceBillingRatesResponse,
  WorkspaceBillingRatesError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: WorkspaceBillingRatesRequest,
  output: WorkspaceBillingRatesResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type WorkspaceBillingSummaryError = ModalOpError;
export const workspaceBillingSummary: API.OperationMethod<
  WorkspaceBillingSummaryRequest,
  WorkspaceBillingSummaryResponse,
  WorkspaceBillingSummaryError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: WorkspaceBillingSummaryRequest,
  output: WorkspaceBillingSummaryResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type WorkspaceSetDefaultEnvironmentError = ModalOpError;
export const workspaceSetDefaultEnvironment: API.OperationMethod<
  WorkspaceSetDefaultEnvironmentRequest,
  WorkspaceSetDefaultEnvironmentResponse,
  WorkspaceSetDefaultEnvironmentError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: WorkspaceSetDefaultEnvironmentRequest,
  output: WorkspaceSetDefaultEnvironmentResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type WorkspaceSetDefaultEnvironmentSettingsError = ModalOpError;
export const workspaceSetDefaultEnvironmentSettings: API.OperationMethod<
  WorkspaceSetDefaultEnvironmentSettingsRequest,
  WorkspaceSetDefaultEnvironmentSettingsResponse,
  WorkspaceSetDefaultEnvironmentSettingsError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: WorkspaceSetDefaultEnvironmentSettingsRequest,
  output: WorkspaceSetDefaultEnvironmentSettingsResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type WorkspaceSetImageBuilderVersionError = ModalOpError;
export const workspaceSetImageBuilderVersion: API.OperationMethod<
  WorkspaceSetImageBuilderVersionRequest,
  WorkspaceSetImageBuilderVersionResponse,
  WorkspaceSetImageBuilderVersionError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: WorkspaceSetImageBuilderVersionRequest,
  output: WorkspaceSetImageBuilderVersionResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));

export type WorkspaceSettingsError = ModalOpError;
export const workspaceSettings: API.OperationMethod<
  WorkspaceSettingsRequest,
  WorkspaceSettingsResponse,
  WorkspaceSettingsError,
  ModalOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: WorkspaceSettingsRequest,
  output: WorkspaceSettingsResponse,
  errors: [UnknownModalError],
  protocol: ModalProtocol,
  retry: Retry.Retry,
}));
