// AUTO-GENERATED by scripts/generate.ts from .generated-specs (e2b openapi/envd/proto → smithy). Do not edit.
import * as S from "@rikalabs/distilled-core/schema";
import * as API from "@rikalabs/distilled-core/api";
import * as T from "../traits.ts";
import {
  E2BProtocol,
  type E2BOpError,
  type E2BOpContext,
} from "../protocol.ts";
import { UnknownE2BError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { E2BOpError, E2BOpContext };

export interface CancelAdminTeamsBuildRequest {
  /** Team ID */
  teamID: string;
}
export const CancelAdminTeamsBuildRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    teamID: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/admin/teams/{teamID}/builds/cancel",
      code: 200,
    }),
  ),
).annotate({
  identifier: "CancelAdminTeamsBuildRequest",
}) as any as S.Schema<CancelAdminTeamsBuildRequest>;

export interface AdminBuildCancelResult {
  /** Number of builds successfully cancelled */
  cancelledCount: number;
  /** Number of builds that failed to cancel */
  failedCount: number;
}
export const AdminBuildCancelResult = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    cancelledCount: S.Number,
    failedCount: S.Number,
  }),
).annotate({
  identifier: "AdminBuildCancelResult",
}) as any as S.Schema<AdminBuildCancelResult>;

export interface CreateAdminTeamApiKeyRequest {
  /** Team ID */
  teamID: string;
  /** Name of the API key */
  name: string;
}
export const CreateAdminTeamApiKeyRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    teamID: S.String.pipe(T.Label()),
    name: S.String,
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/admin/teams/{teamID}/api-keys",
      code: 200,
    }),
  ),
).annotate({
  identifier: "CreateAdminTeamApiKeyRequest",
}) as any as S.Schema<CreateAdminTeamApiKeyRequest>;

export interface IdentifierMaskingDetails {
  /** Prefix that identifies the token or key type */
  prefix: string;
  /** Length of the token or key */
  valueLength: number;
  /** Prefix used in masked version of the token or key */
  maskedValuePrefix: string;
  /** Suffix used in masked version of the token or key */
  maskedValueSuffix: string;
}
export const IdentifierMaskingDetails = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    prefix: S.String,
    valueLength: S.Number,
    maskedValuePrefix: S.String,
    maskedValueSuffix: S.String,
  }),
).annotate({
  identifier: "IdentifierMaskingDetails",
}) as any as S.Schema<IdentifierMaskingDetails>;

export interface TeamUser {
  /** Identifier of the user */
  id: string;
  /** Email of the user */
  email: string | null;
}
export const TeamUser = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    email: S.NullOr(S.String),
  }),
).annotate({ identifier: "TeamUser" }) as any as S.Schema<TeamUser>;

export interface CreatedTeamAPIKey {
  /** Identifier of the API key */
  id: string;
  /** Raw value of the API key */
  key: string;
  mask: IdentifierMaskingDetails;
  /** Name of the API key */
  name: string;
  /** Timestamp of API key creation */
  createdAt: string;
  createdBy?: TeamUser | null;
  /** Last time this API key was used */
  lastUsed?: string | null;
}
export const CreatedTeamAPIKey = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    key: S.String,
    mask: IdentifierMaskingDetails,
    name: S.String,
    createdAt: S.String,
    createdBy: S.optional(S.NullOr(TeamUser)),
    lastUsed: S.optional(S.NullOr(S.String)),
  }),
).annotate({
  identifier: "CreatedTeamAPIKey",
}) as any as S.Schema<CreatedTeamAPIKey>;

export interface DeleteAdminTeamApiKeyRequest {
  /** Team ID */
  teamID: string;
  apiKeyID: string;
}
export const DeleteAdminTeamApiKeyRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    teamID: S.String.pipe(T.Label()),
    apiKeyID: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "DELETE",
      uri: "/admin/teams/{teamID}/api-keys/{apiKeyID}",
      code: 200,
    }),
  ),
).annotate({
  identifier: "DeleteAdminTeamApiKeyRequest",
}) as any as S.Schema<DeleteAdminTeamApiKeyRequest>;

export interface DeleteAdminTeamApiKeyResponse {}
export const DeleteAdminTeamApiKeyResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "DeleteAdminTeamApiKeyResponse",
}) as any as S.Schema<DeleteAdminTeamApiKeyResponse>;

export interface DeleteClusterRigInstanceRequest {
  /** Identifier of the cluster */
  clusterID: string;
  /** Provider instance ID */
  instanceID: string;
  /** When true, desired capacity is decremented (rig shrinks); when false, the scaling group launches a replacement instance */
  decrementDesired: boolean;
}
export const DeleteClusterRigInstanceRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    clusterID: S.String.pipe(T.Label()),
    instanceID: S.String.pipe(T.Label()),
    decrementDesired: S.Boolean.pipe(T.Query()),
  }).pipe(
    T.Http({
      method: "DELETE",
      uri: "/clusters/{clusterID}/rigs/instances/{instanceID}",
      code: 200,
    }),
  ),
).annotate({
  identifier: "DeleteClusterRigInstanceRequest",
}) as any as S.Schema<DeleteClusterRigInstanceRequest>;

export interface DeleteClusterRigInstanceResponse {}
export const DeleteClusterRigInstanceResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "DeleteClusterRigInstanceResponse",
}) as any as S.Schema<DeleteClusterRigInstanceResponse>;

export interface GetAdminSandboxRunningCountsRequest {}
export const GetAdminSandboxRunningCountsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(
    T.Http({
      method: "GET",
      uri: "/admin/sandboxes/running-counts",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetAdminSandboxRunningCountsRequest",
}) as any as S.Schema<GetAdminSandboxRunningCountsRequest>;

/** Cached live sandbox index count keyed by team ID. Counts may briefly include sandboxes transitioning out of running; teams without indexed sandboxes are omitted. */
export type AdminTeamRunningSandboxCounts = {
  [key: string]: number | undefined;
};
export const AdminTeamRunningSandboxCounts = /*@__PURE__*/ S.Record(
  S.String,
  S.Number,
) as any as S.Schema<AdminTeamRunningSandboxCounts>;

export type GetAdminSandboxRunningCountsResponse =
  AdminTeamRunningSandboxCounts;
export const GetAdminSandboxRunningCountsResponse = /*@__PURE__*/ S.suspend(
  () => AdminTeamRunningSandboxCounts.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "GetAdminSandboxRunningCountsResponse",
}) as any as S.Schema<GetAdminSandboxRunningCountsResponse>;

export interface GetNodeRequest {
  nodeID: string;
  /** Identifier of the cluster */
  clusterID?: string;
}
export const GetNodeRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    nodeID: S.String.pipe(T.Label()),
    clusterID: S.optional(S.String.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/nodes/{nodeID}", code: 200 })),
).annotate({ identifier: "GetNodeRequest" }) as any as S.Schema<GetNodeRequest>;

export interface MachineInfo {
  /** CPU family of the node */
  cpuFamily: string;
  /** CPU model of the node */
  cpuModel: string;
  /** CPU model name of the node */
  cpuModelName: string;
  /** CPU architecture of the node */
  cpuArchitecture: string;
}
export const MachineInfo = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    cpuFamily: S.String,
    cpuModel: S.String,
    cpuModelName: S.String,
    cpuArchitecture: S.String,
  }),
).annotate({ identifier: "MachineInfo" }) as any as S.Schema<MachineInfo>;

/** Status of the node. - standby: the node is not actively used, but it can return to ready and continue serving traffic. */
export type NodeStatus =
  | "ready"
  | "draining"
  | "connecting"
  | "unhealthy"
  | "standby"
  | "shutting_down";
export const NodeStatus = S.String;

export interface DiskMetrics {
  /** Mount point of the disk */
  mountPoint: string;
  /** Device name */
  device: string;
  /** Filesystem type (e.g., ext4, xfs) */
  filesystemType: string;
  /** Used space in bytes */
  usedBytes: number;
  /** Total space in bytes */
  totalBytes: number;
}
export const DiskMetrics = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    mountPoint: S.String,
    device: S.String,
    filesystemType: S.String,
    usedBytes: S.Number,
    totalBytes: S.Number,
  }),
).annotate({ identifier: "DiskMetrics" }) as any as S.Schema<DiskMetrics>;

/** Detailed metrics for each disk/mount point */
export type NodeMetricsDisksList = Array<DiskMetrics>;
export const NodeMetricsDisksList = /*@__PURE__*/ S.Array(
  DiskMetrics,
) as any as S.Schema<NodeMetricsDisksList>;

/** Node metrics */
export interface NodeMetrics {
  /** Number of allocated CPU cores */
  allocatedCPU: number;
  /** Node CPU usage percentage */
  cpuPercent: number;
  /** Total number of CPU cores on the node */
  cpuCount: number;
  /** Amount of allocated memory in bytes */
  allocatedMemoryBytes: number;
  /** Node memory used in bytes */
  memoryUsedBytes: number;
  /** Total node memory in bytes */
  memoryTotalBytes: number;
  /** Total number of preallocated hugepages on the node */
  hugePagesTotal: number;
  /** Number of hugepages in use (total - free) */
  hugePagesUsed: number;
  /** Number of reserved hugepages (committed but not yet faulted) */
  hugePagesReserved: number;
  /** Size of a single hugepage in bytes */
  hugePageSizeBytes: number;
  /** Detailed metrics for each disk/mount point */
  disks: NodeMetricsDisksList;
}
export const NodeMetrics = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    allocatedCPU: S.Number,
    cpuPercent: S.Number,
    cpuCount: S.Number,
    allocatedMemoryBytes: S.Number,
    memoryUsedBytes: S.Number,
    memoryTotalBytes: S.Number,
    hugePagesTotal: S.Number,
    hugePagesUsed: S.Number,
    hugePagesReserved: S.Number,
    hugePageSizeBytes: S.Number,
    disks: NodeMetricsDisksList,
  }),
).annotate({ identifier: "NodeMetrics" }) as any as S.Schema<NodeMetrics>;

export interface NodeDetail {
  /** Identifier of the cluster */
  clusterID: string;
  /** Version of the orchestrator */
  version: string;
  /** Commit of the orchestrator */
  commit: string;
  /** Identifier of the node */
  id: string;
  /** Service instance identifier of the node */
  serviceInstanceID: string;
  machineInfo: MachineInfo;
  status: NodeStatus;
  /** Time when the node status was last changed */
  statusChangedAt: string;
  /** Number of sandboxes running on the node */
  sandboxCount: number;
  /** Node-scoped configured sandbox admission limit. Nonpositive values reject creation. Omitted when unknown or not an orchestrator. */
  maxSandboxes?: number;
  /** Observed work holds on the node. Omitted when unknown; zero does not authorize deletion. */
  outstandingWork?: number;
  metrics: NodeMetrics;
  /** Number of sandbox create successes */
  createSuccesses: number;
  /** Number of sandbox create fails */
  createFails: number;
}
export const NodeDetail = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    clusterID: S.String,
    version: S.String,
    commit: S.String,
    id: S.String,
    serviceInstanceID: S.String,
    machineInfo: MachineInfo,
    status: NodeStatus,
    statusChangedAt: S.String,
    sandboxCount: S.Number,
    maxSandboxes: S.optional(S.Number),
    outstandingWork: S.optional(S.Number),
    metrics: NodeMetrics,
    createSuccesses: S.Number,
    createFails: S.Number,
  }),
).annotate({ identifier: "NodeDetail" }) as any as S.Schema<NodeDetail>;

export interface KillAdminTeamsSandboxRequest {
  /** Team ID */
  teamID: string;
}
export const KillAdminTeamsSandboxRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    teamID: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/admin/teams/{teamID}/sandboxes/kill",
      code: 200,
    }),
  ),
).annotate({
  identifier: "KillAdminTeamsSandboxRequest",
}) as any as S.Schema<KillAdminTeamsSandboxRequest>;

export interface AdminSandboxKillResult {
  /** Number of sandboxes successfully killed */
  killedCount: number;
  /** Number of sandboxes that failed to kill */
  failedCount: number;
}
export const AdminSandboxKillResult = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    killedCount: S.Number,
    failedCount: S.Number,
  }),
).annotate({
  identifier: "AdminSandboxKillResult",
}) as any as S.Schema<AdminSandboxKillResult>;

export interface ListClusterRigErrorsRequest {
  /** Identifier of the cluster */
  clusterID: string;
  /** Rig identifier (e.g. "default") */
  rigID: string;
  /** Maximum number of errors to return */
  limit?: number;
}
export const ListClusterRigErrorsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    clusterID: S.String.pipe(T.Label()),
    rigID: S.String.pipe(T.Label()),
    limit: S.optional(S.Number.pipe(T.Query())),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/clusters/{clusterID}/rigs/{rigID}/errors",
      code: 200,
    }),
  ),
).annotate({
  identifier: "ListClusterRigErrorsRequest",
}) as any as S.Schema<ListClusterRigErrorsRequest>;

/** Scaling error on the rig's scaling group, e.g. a failed instance creation due to resource exhaustion */
export interface RigError {
  /** When the error occurred */
  timestamp: string;
  /** Provider-specific error code (e.g. ZONE_RESOURCE_POOL_EXHAUSTED, Failed) */
  code: string;
  /** Human-readable error message */
  message: string;
  /** Instance the error relates to, if any */
  instance?: string;
  /** Action being performed when the error occurred (e.g. CREATING) */
  action?: string;
}
export const RigError = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    timestamp: S.String,
    code: S.String,
    message: S.String,
    instance: S.optional(S.String),
    action: S.optional(S.String),
  }),
).annotate({ identifier: "RigError" }) as any as S.Schema<RigError>;

export type ListClusterRigErrorsResponseBodyList = Array<RigError>;
export const ListClusterRigErrorsResponseBodyList = /*@__PURE__*/ S.Array(
  RigError,
) as any as S.Schema<ListClusterRigErrorsResponseBodyList>;

export type ListClusterRigErrorsResponse = ListClusterRigErrorsResponseBodyList;
export const ListClusterRigErrorsResponse = /*@__PURE__*/ S.suspend(() =>
  ListClusterRigErrorsResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "ListClusterRigErrorsResponse",
}) as any as S.Schema<ListClusterRigErrorsResponse>;

export interface ListClusterRigInstancesRequest {
  /** Identifier of the cluster */
  clusterID: string;
  /** Rig identifier (e.g. "default") */
  rigID: string;
}
export const ListClusterRigInstancesRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    clusterID: S.String.pipe(T.Label()),
    rigID: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/clusters/{clusterID}/rigs/{rigID}/instances",
      code: 200,
    }),
  ),
).annotate({
  identifier: "ListClusterRigInstancesRequest",
}) as any as S.Schema<ListClusterRigInstancesRequest>;

/** An instance attached to a rig's scaling group */
export interface RigInstance {
  /** Provider instance ID (EC2 instance ID on AWS, instance name on GCP), also the node ID the orchestrator reports */
  id: string;
  /** When the provider created the instance. Omitted while the instance is transitioning. */
  createdAt?: string;
  /** The provider is creating, deleting, recreating or otherwise mutating the instance */
  transitioning: boolean;
  /** The instance is on its way out of the group and can never become healthy again */
  terminating: boolean;
}
export const RigInstance = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    createdAt: S.optional(S.String),
    transitioning: S.Boolean,
    terminating: S.Boolean,
  }),
).annotate({ identifier: "RigInstance" }) as any as S.Schema<RigInstance>;

export type ListClusterRigInstancesResponseBodyList = Array<RigInstance>;
export const ListClusterRigInstancesResponseBodyList = /*@__PURE__*/ S.Array(
  RigInstance,
) as any as S.Schema<ListClusterRigInstancesResponseBodyList>;

export type ListClusterRigInstancesResponse =
  ListClusterRigInstancesResponseBodyList;
export const ListClusterRigInstancesResponse = /*@__PURE__*/ S.suspend(() =>
  ListClusterRigInstancesResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "ListClusterRigInstancesResponse",
}) as any as S.Schema<ListClusterRigInstancesResponse>;

export interface ListClusterRigsRequest {
  /** Identifier of the cluster */
  clusterID: string;
}
export const ListClusterRigsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    clusterID: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({ method: "GET", uri: "/clusters/{clusterID}/rigs", code: 200 }),
  ),
).annotate({
  identifier: "ListClusterRigsRequest",
}) as any as S.Schema<ListClusterRigsRequest>;

/** An orchestrator node pool backed by one cloud scaling group */
export interface Rig {
  /** Rig identifier (e.g. "default") */
  id: string;
  /** Cloud provider backing the rig ("aws" or "gcp") */
  provider: string;
  /** Canonical cloud resource ID of the scaling group backing the rig (ARN on AWS, self-link on GCP) */
  resourceID: string;
  /** Desired number of instances in the rig */
  capacityDesired: number;
  /** Minimum capacity enforced on the rig's scaling group. Omitted when nothing enforces bounds (GCP MIG without an active autoscaler). */
  capacityMin?: number;
  /** Maximum capacity enforced on the rig's scaling group. Omitted when nothing enforces bounds (GCP MIG without an active autoscaler). */
  capacityMax?: number;
  /** Number of instances currently attached to the rig */
  capacityCurrent: number;
}
export const Rig = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    provider: S.String,
    resourceID: S.String,
    capacityDesired: S.Number,
    capacityMin: S.optional(S.Number),
    capacityMax: S.optional(S.Number),
    capacityCurrent: S.Number,
  }),
).annotate({ identifier: "Rig" }) as any as S.Schema<Rig>;

export type ListClusterRigsResponseBodyList = Array<Rig>;
export const ListClusterRigsResponseBodyList = /*@__PURE__*/ S.Array(
  Rig,
) as any as S.Schema<ListClusterRigsResponseBodyList>;

export type ListClusterRigsResponse = ListClusterRigsResponseBodyList;
export const ListClusterRigsResponse = /*@__PURE__*/ S.suspend(() =>
  ListClusterRigsResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "ListClusterRigsResponse",
}) as any as S.Schema<ListClusterRigsResponse>;

export interface ListNodesRequest {
  /** Identifier of the cluster */
  clusterID?: string;
}
export const ListNodesRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    clusterID: S.optional(S.String.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/nodes", code: 200 })),
).annotate({
  identifier: "ListNodesRequest",
}) as any as S.Schema<ListNodesRequest>;

export interface Node {
  /** Version of the orchestrator */
  version: string;
  /** Commit of the orchestrator */
  commit: string;
  /** Identifier of the node */
  id: string;
  /** Service instance identifier of the node */
  serviceInstanceID: string;
  /** Identifier of the cluster */
  clusterID: string;
  machineInfo: MachineInfo;
  status: NodeStatus;
  /** Time when the node status was last changed */
  statusChangedAt: string;
  /** Number of sandboxes running on the node */
  sandboxCount: number;
  /** Node-scoped configured sandbox admission limit. Nonpositive values reject creation. Omitted when unknown or not an orchestrator. */
  maxSandboxes?: number;
  /** Observed work holds on the node. Omitted when unknown; zero does not authorize deletion. */
  outstandingWork?: number;
  metrics: NodeMetrics;
  /** Number of sandbox create successes */
  createSuccesses: number;
  /** Number of sandbox create fails */
  createFails: number;
  /** Number of starting Sandboxes */
  sandboxStartingCount: number;
}
export const Node = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    version: S.String,
    commit: S.String,
    id: S.String,
    serviceInstanceID: S.String,
    clusterID: S.String,
    machineInfo: MachineInfo,
    status: NodeStatus,
    statusChangedAt: S.String,
    sandboxCount: S.Number,
    maxSandboxes: S.optional(S.Number),
    outstandingWork: S.optional(S.Number),
    metrics: NodeMetrics,
    createSuccesses: S.Number,
    createFails: S.Number,
    sandboxStartingCount: S.Number,
  }),
).annotate({ identifier: "Node" }) as any as S.Schema<Node>;

export type ListNodesResponseBodyList = Array<Node>;
export const ListNodesResponseBodyList = /*@__PURE__*/ S.Array(
  Node,
) as any as S.Schema<ListNodesResponseBodyList>;

export type ListNodesResponse = ListNodesResponseBodyList;
export const ListNodesResponse = /*@__PURE__*/ S.suspend(() =>
  ListNodesResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "ListNodesResponse",
}) as any as S.Schema<ListNodesResponse>;

export interface PutClusterRigCapacityRequest {
  /** Identifier of the cluster */
  clusterID: string;
  /** Rig identifier (e.g. "default") */
  rigID: string;
  /** Absolute desired number of instances in the rig */
  desired: number;
}
export const PutClusterRigCapacityRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    clusterID: S.String.pipe(T.Label()),
    rigID: S.String.pipe(T.Label()),
    desired: S.Number,
  }).pipe(
    T.Http({
      method: "PUT",
      uri: "/clusters/{clusterID}/rigs/{rigID}/capacity",
      code: 200,
    }),
  ),
).annotate({
  identifier: "PutClusterRigCapacityRequest",
}) as any as S.Schema<PutClusterRigCapacityRequest>;

export interface PutClusterRigCapacityResponse {}
export const PutClusterRigCapacityResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "PutClusterRigCapacityResponse",
}) as any as S.Schema<PutClusterRigCapacityResponse>;

export interface UpdateNodeRequest {
  nodeID: string;
  /** Identifier of the cluster */
  clusterID?: string;
  status: NodeStatus | (string & {});
}
export const UpdateNodeRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    nodeID: S.String.pipe(T.Label()),
    clusterID: S.optional(S.String),
    status: NodeStatus,
  }).pipe(T.Http({ method: "POST", uri: "/nodes/{nodeID}", code: 200 })),
).annotate({
  identifier: "UpdateNodeRequest",
}) as any as S.Schema<UpdateNodeRequest>;

export interface UpdateNodeResponse {}
export const UpdateNodeResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "UpdateNodeResponse",
}) as any as S.Schema<UpdateNodeResponse>;

export type CancelAdminTeamsBuildError = E2BOpError;
/** Cancel all builds for a team Cancels all in-progress and pending builds for the specified team */
export const cancelAdminTeamsBuild: API.OperationMethod<
  CancelAdminTeamsBuildRequest,
  AdminBuildCancelResult,
  CancelAdminTeamsBuildError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CancelAdminTeamsBuildRequest,
  output: AdminBuildCancelResult,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));

export type CreateAdminTeamApiKeyError = E2BOpError;
/** Create team API key as admin Creates a team API key for internal service workflows. */
export const createAdminTeamApiKey: API.OperationMethod<
  CreateAdminTeamApiKeyRequest,
  CreatedTeamAPIKey,
  CreateAdminTeamApiKeyError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateAdminTeamApiKeyRequest,
  output: CreatedTeamAPIKey,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));

export type DeleteAdminTeamApiKeyError = E2BOpError;
/** Delete team API key as admin Deletes a team API key for internal service workflows. */
export const deleteAdminTeamApiKey: API.OperationMethod<
  DeleteAdminTeamApiKeyRequest,
  DeleteAdminTeamApiKeyResponse,
  DeleteAdminTeamApiKeyError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteAdminTeamApiKeyRequest,
  output: DeleteAdminTeamApiKeyResponse,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));

export type DeleteClusterRigInstanceError = E2BOpError;
/** Terminate an instance of a rig Terminate an instance in whichever rig's scaling group it belongs to. The caller chooses whether the rig shrinks or the instance is replaced. */
export const deleteClusterRigInstance: API.OperationMethod<
  DeleteClusterRigInstanceRequest,
  DeleteClusterRigInstanceResponse,
  DeleteClusterRigInstanceError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteClusterRigInstanceRequest,
  output: DeleteClusterRigInstanceResponse,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));

export type GetAdminSandboxRunningCountsError = E2BOpError;
/** Count running sandboxes by team Returns a shared snapshot normally refreshed after five seconds. A sandbox transitioning out of running can remain counted until removal. */
export const getAdminSandboxRunningCounts: API.OperationMethod<
  GetAdminSandboxRunningCountsRequest,
  GetAdminSandboxRunningCountsResponse,
  GetAdminSandboxRunningCountsError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetAdminSandboxRunningCountsRequest,
  output: GetAdminSandboxRunningCountsResponse,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));

export type GetNodeError = E2BOpError;
/** Node info Get node info */
export const getNode: API.OperationMethod<
  GetNodeRequest,
  NodeDetail,
  GetNodeError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetNodeRequest,
  output: NodeDetail,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));

export type KillAdminTeamsSandboxError = E2BOpError;
/** Kill all sandboxes for a team Kills all sandboxes for the specified team */
export const killAdminTeamsSandbox: API.OperationMethod<
  KillAdminTeamsSandboxRequest,
  AdminSandboxKillResult,
  KillAdminTeamsSandboxError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: KillAdminTeamsSandboxRequest,
  output: AdminSandboxKillResult,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));

export type ListClusterRigErrorsError = E2BOpError;
/** List recent scaling errors of a rig List recent scaling errors on the rig's scaling group (e.g. failed instance creations due to resource exhaustion), newest first. */
export const listClusterRigErrors: API.OperationMethod<
  ListClusterRigErrorsRequest,
  ListClusterRigErrorsResponse,
  ListClusterRigErrorsError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListClusterRigErrorsRequest,
  output: ListClusterRigErrorsResponse,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));

export type ListClusterRigInstancesError = E2BOpError;
/** List the instances attached to a rig List the instances attached to the rig's scaling group with their creation time and transition state, sorted by instance ID. */
export const listClusterRigInstances: API.OperationMethod<
  ListClusterRigInstancesRequest,
  ListClusterRigInstancesResponse,
  ListClusterRigInstancesError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListClusterRigInstancesRequest,
  output: ListClusterRigInstancesResponse,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));

export type ListClusterRigsError = E2BOpError;
/** List rigs of a cluster List the orchestrator node pools ("rigs") of a cluster with a snapshot of their scaling groups. Forwarded to the cluster's edge service; a cluster with no rig management configured returns an empty list, and the local cluster answers 501. */
export const listClusterRigs: API.OperationMethod<
  ListClusterRigsRequest,
  ListClusterRigsResponse,
  ListClusterRigsError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListClusterRigsRequest,
  output: ListClusterRigsResponse,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));

export type ListNodesError = E2BOpError;
/** List nodes List all nodes */
export const listNodes: API.OperationMethod<
  ListNodesRequest,
  ListNodesResponse,
  ListNodesError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListNodesRequest,
  output: ListNodesResponse,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));

export type PutClusterRigCapacityError = E2BOpError;
/** Set the capacity of a rig Set the desired instance count on the rig's scaling group. The value is passed to the cloud provider unchanged; violations of the group's bounds or conflicting concurrent operations surface as errors. */
export const putClusterRigCapacity: API.OperationMethod<
  PutClusterRigCapacityRequest,
  PutClusterRigCapacityResponse,
  PutClusterRigCapacityError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PutClusterRigCapacityRequest,
  output: PutClusterRigCapacityResponse,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));

export type UpdateNodeError = E2BOpError;
/** Change node status Change status of a node */
export const updateNode: API.OperationMethod<
  UpdateNodeRequest,
  UpdateNodeResponse,
  UpdateNodeError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateNodeRequest,
  output: UpdateNodeResponse,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));
