// AUTO-GENERATED by scripts/generate.ts from .generated-specs (e2b openapi/envd/proto → smithy). Do not edit.
import * as S from "@rikalabs/distilled-core/schema";
import * as API from "@rikalabs/distilled-core/api";
import * as T from "../traits.ts";
import {
  E2BProtocol,
  type E2BOpError,
  type E2BOpContext,
} from "../protocol.ts";
import { UnknownE2BError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { E2BOpError, E2BOpContext };

export interface CreateApiKeyRequest {
  /** Name of the API key */
  name: string;
}
export const CreateApiKeyRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.String,
  }).pipe(T.Http({ method: "POST", uri: "/api-keys", code: 200 })),
).annotate({
  identifier: "CreateApiKeyRequest",
}) as any as S.Schema<CreateApiKeyRequest>;

export interface IdentifierMaskingDetails {
  /** Prefix that identifies the token or key type */
  prefix: string;
  /** Length of the token or key */
  valueLength: number;
  /** Prefix used in masked version of the token or key */
  maskedValuePrefix: string;
  /** Suffix used in masked version of the token or key */
  maskedValueSuffix: string;
}
export const IdentifierMaskingDetails = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    prefix: S.String,
    valueLength: S.Number,
    maskedValuePrefix: S.String,
    maskedValueSuffix: S.String,
  }),
).annotate({
  identifier: "IdentifierMaskingDetails",
}) as any as S.Schema<IdentifierMaskingDetails>;

export interface TeamUser {
  /** Identifier of the user */
  id: string;
  /** Email of the user */
  email: string | null;
}
export const TeamUser = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    email: S.NullOr(S.String),
  }),
).annotate({ identifier: "TeamUser" }) as any as S.Schema<TeamUser>;

export interface CreatedTeamAPIKey {
  /** Identifier of the API key */
  id: string;
  /** Raw value of the API key */
  key: string;
  mask: IdentifierMaskingDetails;
  /** Name of the API key */
  name: string;
  /** Timestamp of API key creation */
  createdAt: string;
  createdBy?: TeamUser | null;
  /** Last time this API key was used */
  lastUsed?: string | null;
}
export const CreatedTeamAPIKey = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    key: S.String,
    mask: IdentifierMaskingDetails,
    name: S.String,
    createdAt: S.String,
    createdBy: S.optional(S.NullOr(TeamUser)),
    lastUsed: S.optional(S.NullOr(S.String)),
  }),
).annotate({
  identifier: "CreatedTeamAPIKey",
}) as any as S.Schema<CreatedTeamAPIKey>;

export interface DeleteApiKeyRequest {
  apiKeyID: string;
}
export const DeleteApiKeyRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    apiKeyID: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "DELETE", uri: "/api-keys/{apiKeyID}", code: 200 })),
).annotate({
  identifier: "DeleteApiKeyRequest",
}) as any as S.Schema<DeleteApiKeyRequest>;

export interface DeleteApiKeyResponse {}
export const DeleteApiKeyResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "DeleteApiKeyResponse",
}) as any as S.Schema<DeleteApiKeyResponse>;

export interface ListApiKeysRequest {}
export const ListApiKeysRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(T.Http({ method: "GET", uri: "/api-keys", code: 200 })),
).annotate({
  identifier: "ListApiKeysRequest",
}) as any as S.Schema<ListApiKeysRequest>;

export interface TeamAPIKey {
  /** Identifier of the API key */
  id: string;
  /** Name of the API key */
  name: string;
  mask: IdentifierMaskingDetails;
  /** Timestamp of API key creation */
  createdAt: string;
  createdBy?: TeamUser | null;
  /** Last time this API key was used */
  lastUsed?: string | null;
}
export const TeamAPIKey = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    name: S.String,
    mask: IdentifierMaskingDetails,
    createdAt: S.String,
    createdBy: S.optional(S.NullOr(TeamUser)),
    lastUsed: S.optional(S.NullOr(S.String)),
  }),
).annotate({ identifier: "TeamAPIKey" }) as any as S.Schema<TeamAPIKey>;

export type ListApiKeysResponseBodyList = Array<TeamAPIKey>;
export const ListApiKeysResponseBodyList = /*@__PURE__*/ S.Array(
  TeamAPIKey,
) as any as S.Schema<ListApiKeysResponseBodyList>;

export type ListApiKeysResponse = ListApiKeysResponseBodyList;
export const ListApiKeysResponse = /*@__PURE__*/ S.suspend(() =>
  ListApiKeysResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "ListApiKeysResponse",
}) as any as S.Schema<ListApiKeysResponse>;

export interface UpdateApiKeyRequest {
  apiKeyID: string;
  /** New name for the API key */
  name: string;
}
export const UpdateApiKeyRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    apiKeyID: S.String.pipe(T.Label()),
    name: S.String,
  }).pipe(T.Http({ method: "PATCH", uri: "/api-keys/{apiKeyID}", code: 200 })),
).annotate({
  identifier: "UpdateApiKeyRequest",
}) as any as S.Schema<UpdateApiKeyRequest>;

export interface UpdateApiKeyResponse {}
export const UpdateApiKeyResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "UpdateApiKeyResponse",
}) as any as S.Schema<UpdateApiKeyResponse>;

export type CreateApiKeyError = E2BOpError;
/** Create team API key Create a new team API key */
export const createApiKey: API.OperationMethod<
  CreateApiKeyRequest,
  CreatedTeamAPIKey,
  CreateApiKeyError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateApiKeyRequest,
  output: CreatedTeamAPIKey,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));

export type DeleteApiKeyError = E2BOpError;
/** Delete team API key Delete a team API key */
export const deleteApiKey: API.OperationMethod<
  DeleteApiKeyRequest,
  DeleteApiKeyResponse,
  DeleteApiKeyError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteApiKeyRequest,
  output: DeleteApiKeyResponse,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));

export type ListApiKeysError = E2BOpError;
/** List team API keys List all team API keys */
export const listApiKeys: API.OperationMethod<
  ListApiKeysRequest,
  ListApiKeysResponse,
  ListApiKeysError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListApiKeysRequest,
  output: ListApiKeysResponse,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));

export type UpdateApiKeyError = E2BOpError;
/** Update team API key Update a team API key */
export const updateApiKey: API.OperationMethod<
  UpdateApiKeyRequest,
  UpdateApiKeyResponse,
  UpdateApiKeyError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateApiKeyRequest,
  output: UpdateApiKeyResponse,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));
