// AUTO-GENERATED by scripts/generate.ts from .generated-specs (e2b openapi/envd/proto → smithy). Do not edit.
import * as S from "@rikalabs/distilled-core/schema";
import * as Redacted from "effect/Redacted";
import * as API from "@rikalabs/distilled-core/api";
import * as T from "../traits.ts";
import {
  E2BProtocol,
  type E2BOpError,
  type E2BOpContext,
} from "../protocol.ts";
import { UnknownE2BError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { E2BOpError, E2BOpContext };

export type GetTeamMetricsMaxRequestMetric =
  | "concurrent_sandboxes"
  | "sandbox_start_rate";
export const GetTeamMetricsMaxRequestMetric = S.String;

export interface GetTeamMetricsMaxRequest {
  teamID: string;
  /** Unix timestamp for the start of the interval, in seconds, for which the metrics */
  start?: number;
  end?: number;
  /** Metric to retrieve the maximum value for */
  metric: GetTeamMetricsMaxRequestMetric | (string & {});
}
export const GetTeamMetricsMaxRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    teamID: S.String.pipe(T.Label()),
    start: S.optional(S.Number.pipe(T.Query())),
    end: S.optional(S.Number.pipe(T.Query())),
    metric: GetTeamMetricsMaxRequestMetric.pipe(T.Query()),
  }).pipe(
    T.Http({ method: "GET", uri: "/teams/{teamID}/metrics/max", code: 200 }),
  ),
).annotate({
  identifier: "GetTeamMetricsMaxRequest",
}) as any as S.Schema<GetTeamMetricsMaxRequest>;

/** Team metric with timestamp */
export interface MaxTeamMetric {
  /** Timestamp of the metric entry */
  timestamp: string;
  /** Timestamp of the metric entry in Unix time (seconds since epoch) */
  timestampUnix: number;
  /** The maximum value of the requested metric in the given interval */
  value: number;
}
export const MaxTeamMetric = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    timestamp: S.String,
    timestampUnix: S.Number,
    value: S.Number,
  }),
).annotate({ identifier: "MaxTeamMetric" }) as any as S.Schema<MaxTeamMetric>;

export interface ListTeamMetricsRequest {
  teamID: string;
  /** Unix timestamp for the start of the interval, in seconds, for which the metrics */
  start?: number;
  end?: number;
}
export const ListTeamMetricsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    teamID: S.String.pipe(T.Label()),
    start: S.optional(S.Number.pipe(T.Query())),
    end: S.optional(S.Number.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/teams/{teamID}/metrics", code: 200 })),
).annotate({
  identifier: "ListTeamMetricsRequest",
}) as any as S.Schema<ListTeamMetricsRequest>;

/** Team metric with timestamp */
export interface TeamMetric {
  /** Timestamp of the metric entry */
  timestamp: string;
  /** Timestamp of the metric entry in Unix time (seconds since epoch) */
  timestampUnix: number;
  /** The number of concurrent sandboxes for the team */
  concurrentSandboxes: number;
  /** Number of sandboxes started per second */
  sandboxStartRate: number;
}
export const TeamMetric = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    timestamp: S.String,
    timestampUnix: S.Number,
    concurrentSandboxes: S.Number,
    sandboxStartRate: S.Number,
  }),
).annotate({ identifier: "TeamMetric" }) as any as S.Schema<TeamMetric>;

export type ListTeamMetricsResponseBodyList = Array<TeamMetric>;
export const ListTeamMetricsResponseBodyList = /*@__PURE__*/ S.Array(
  TeamMetric,
) as any as S.Schema<ListTeamMetricsResponseBodyList>;

export type ListTeamMetricsResponse = ListTeamMetricsResponseBodyList;
export const ListTeamMetricsResponse = /*@__PURE__*/ S.suspend(() =>
  ListTeamMetricsResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "ListTeamMetricsResponse",
}) as any as S.Schema<ListTeamMetricsResponse>;

export interface ListTeamsRequest {}
export const ListTeamsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(T.Http({ method: "GET", uri: "/teams", code: 200 })),
).annotate({
  identifier: "ListTeamsRequest",
}) as any as S.Schema<ListTeamsRequest>;

export interface Team {
  /** Identifier of the team */
  teamID: string;
  /** Name of the team */
  name: string;
  /** API key for the team */
  apiKey: string | Redacted.Redacted<string>;
  /** Whether the team is the default team */
  isDefault: boolean;
}
export const Team = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    teamID: S.String,
    name: S.String,
    apiKey: S.String.pipe(T.SensitiveValue({})),
    isDefault: S.Boolean,
  }),
).annotate({ identifier: "Team" }) as any as S.Schema<Team>;

export type ListTeamsResponseBodyList = Array<Team>;
export const ListTeamsResponseBodyList = /*@__PURE__*/ S.Array(
  Team,
) as any as S.Schema<ListTeamsResponseBodyList>;

export type ListTeamsResponse = ListTeamsResponseBodyList;
export const ListTeamsResponse = /*@__PURE__*/ S.suspend(() =>
  ListTeamsResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "ListTeamsResponse",
}) as any as S.Schema<ListTeamsResponse>;

export type GetTeamMetricsMaxError = E2BOpError;
/** Maximum team metrics Get the maximum metrics for the team in the given interval */
export const getTeamMetricsMax: API.OperationMethod<
  GetTeamMetricsMaxRequest,
  MaxTeamMetric,
  GetTeamMetricsMaxError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetTeamMetricsMaxRequest,
  output: MaxTeamMetric,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));

export type ListTeamMetricsError = E2BOpError;
/** Team metrics Get metrics for the team */
export const listTeamMetrics: API.OperationMethod<
  ListTeamMetricsRequest,
  ListTeamMetricsResponse,
  ListTeamMetricsError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListTeamMetricsRequest,
  output: ListTeamMetricsResponse,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));

export type ListTeamsError = E2BOpError;
/** List teams List all teams */
export const listTeams: API.OperationMethod<
  ListTeamsRequest,
  ListTeamsResponse,
  ListTeamsError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListTeamsRequest,
  output: ListTeamsResponse,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));
