// AUTO-GENERATED by scripts/generate.ts from .generated-specs (e2b openapi/envd/proto → smithy). Do not edit.
import * as S from "@rikalabs/distilled-core/schema";
import * as API from "@rikalabs/distilled-core/api";
import * as T from "../traits.ts";
import {
  E2BEnvdProtocol,
  type E2BEnvdOpError,
  type E2BEnvdOpContext,
} from "../protocol.ts";
import { UnknownE2BError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { E2BEnvdOpError, E2BEnvdOpContext };

export interface CreateFileRequest {
  /** Path to the file, URL encoded. Can be relative to the user's home directory (e.g. "file.txt" resolves to ~/file.txt). */
  path?: string;
  /** User for setting file ownership and resolving relative paths. Defaults to the sandbox's default user. */
  username?: string;
  /** Signature used for file access permission verification. */
  signature?: string;
  /** Unix timestamp (seconds) after which the signature expires. Only used with the signature parameter. */
  signature_expiration?: number;
  file?: File | Blob;
}
export const CreateFileRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    path: S.optional(S.String.pipe(T.Query())),
    username: S.optional(S.String.pipe(T.Query())),
    signature: S.optional(S.String.pipe(T.Query())),
    signature_expiration: S.optional(S.Number.pipe(T.Query())),
    file: S.optional(S.String.pipe(T.FormDataFile())),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/files",
      code: 200,
      contentType: "multipart",
    }),
  ),
).annotate({
  identifier: "CreateFileRequest",
}) as any as S.Schema<CreateFileRequest>;

/** Type of the file */
export type EntryInfoType = "file";
export const EntryInfoType = S.String;

/** User-defined metadata stored as extended attributes on the file. */
export type EntryInfoMetadataMap = { [key: string]: string | undefined };
export const EntryInfoMetadataMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<EntryInfoMetadataMap>;

export interface EntryInfo {
  /** Path to the file */
  path: string;
  /** Name of the file */
  name: string;
  /** Type of the file */
  type: EntryInfoType;
  /** User-defined metadata stored as extended attributes on the file. */
  metadata?: EntryInfoMetadataMap;
}
export const EntryInfo = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    path: S.String,
    name: S.String,
    type: EntryInfoType,
    metadata: S.optional(EntryInfoMetadataMap),
  }),
).annotate({ identifier: "EntryInfo" }) as any as S.Schema<EntryInfo>;

export type CreateFileResponseBodyList = Array<EntryInfo>;
export const CreateFileResponseBodyList = /*@__PURE__*/ S.Array(
  EntryInfo,
) as any as S.Schema<CreateFileResponseBodyList>;

export type CreateFileResponse = CreateFileResponseBodyList;
export const CreateFileResponse = /*@__PURE__*/ S.suspend(() =>
  CreateFileResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "CreateFileResponse",
}) as any as S.Schema<CreateFileResponse>;

/** Ordered list of source file paths to concatenate */
export type CreateFileComposeRequestSourcePathsList = Array<string>;
export const CreateFileComposeRequestSourcePathsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<CreateFileComposeRequestSourcePathsList>;

export interface CreateFileComposeRequest {
  /** Ordered list of source file paths to concatenate */
  source_paths: CreateFileComposeRequestSourcePathsList;
  /** Destination file path for the composed file */
  destination: string;
  /** User for setting ownership and resolving relative paths */
  username?: string;
}
export const CreateFileComposeRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    source_paths: CreateFileComposeRequestSourcePathsList,
    destination: S.String,
    username: S.optional(S.String),
  }).pipe(T.Http({ method: "POST", uri: "/files/compose", code: 200 })),
).annotate({
  identifier: "CreateFileComposeRequest",
}) as any as S.Schema<CreateFileComposeRequest>;

export interface GetEnvsRequest {}
export const GetEnvsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(T.Http({ method: "GET", uri: "/envs", code: 200 })),
).annotate({ identifier: "GetEnvsRequest" }) as any as S.Schema<GetEnvsRequest>;

/** Environment variables to set */
export type EnvVars = { [key: string]: string | undefined };
export const EnvVars = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<EnvVars>;

export type GetEnvsResponse = EnvVars;
export const GetEnvsResponse = /*@__PURE__*/ S.suspend(() =>
  EnvVars.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "GetEnvsResponse",
}) as any as S.Schema<GetEnvsResponse>;

export interface GetFilesRequest {
  /** Path to the file, URL encoded. Can be relative to the user's home directory (e.g. "file.txt" resolves to ~/file.txt). */
  path?: string;
  /** User for setting file ownership and resolving relative paths. Defaults to the sandbox's default user. */
  username?: string;
  /** Signature used for file access permission verification. */
  signature?: string;
  /** Unix timestamp (seconds) after which the signature expires. Only used with the signature parameter. */
  signature_expiration?: number;
}
export const GetFilesRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    path: S.optional(S.String.pipe(T.Query())),
    username: S.optional(S.String.pipe(T.Query())),
    signature: S.optional(S.String.pipe(T.Query())),
    signature_expiration: S.optional(S.Number.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/files", code: 200 })),
).annotate({
  identifier: "GetFilesRequest",
}) as any as S.Schema<GetFilesRequest>;

export interface DownloadFileResponse {
  body: Uint8Array;
}
export const DownloadFileResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    body: S.String.pipe(T.HttpBody()),
  }),
).annotate({
  identifier: "DownloadFileResponse",
}) as any as S.Schema<DownloadFileResponse>;

export interface GetHealthRequest {}
export const GetHealthRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(T.Http({ method: "GET", uri: "/health", code: 200 })),
).annotate({
  identifier: "GetHealthRequest",
}) as any as S.Schema<GetHealthRequest>;

export interface GetHealthResponse {}
export const GetHealthResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "GetHealthResponse",
}) as any as S.Schema<GetHealthResponse>;

export interface GetMetricsRequest {}
export const GetMetricsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(T.Http({ method: "GET", uri: "/metrics", code: 200 })),
).annotate({
  identifier: "GetMetricsRequest",
}) as any as S.Schema<GetMetricsRequest>;

/** Resource usage metrics */
export interface Metrics {
  /** Unix timestamp in UTC for current sandbox time */
  ts?: number;
  /** Number of CPU cores */
  cpu_count?: number;
  /** CPU usage percentage */
  cpu_used_pct?: number;
  /** Total virtual memory in bytes */
  mem_total?: number;
  /** Used virtual memory in bytes */
  mem_used?: number;
  /** Cached memory (page cache) in bytes */
  mem_cache?: number;
  /** Total virtual memory in MiB */
  mem_total_mib?: number;
  /** Used virtual memory in MiB */
  mem_used_mib?: number;
  /** Used disk space in bytes */
  disk_used?: number;
  /** Total disk space in bytes */
  disk_total?: number;
}
export const Metrics = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    ts: S.optional(S.Number),
    cpu_count: S.optional(S.Number),
    cpu_used_pct: S.optional(S.Number),
    mem_total: S.optional(S.Number),
    mem_used: S.optional(S.Number),
    mem_cache: S.optional(S.Number),
    mem_total_mib: S.optional(S.Number),
    mem_used_mib: S.optional(S.Number),
    disk_used: S.optional(S.Number),
    disk_total: S.optional(S.Number),
  }),
).annotate({ identifier: "Metrics" }) as any as S.Schema<Metrics>;

export type CreateFileError = E2BEnvdOpError;
/** Upload a file and ensure the parent directories exist. If the file exists, it will be overwritten. Any request header of the form `X-Metadata-<key>: <value>` is persisted as a user-defined extended attribute on the uploaded file. The `X-Metadata-` prefix is stripped and the remaining header name is lowercased to form the metadata key; the resulting map is returned on `EntryInfo` lookups (e.g. `Stat`, `ListDir`). Each upload replaces the file's metadata with the keys provided in that request: keys previously stored but absent from the new request are removed, and an upload that sends no `X-Metadata-*` header clears all existing metadata. Both keys and values must be printable US-ASCII (bytes `0x20`-`0x7E`) and are rejected with HTTP 400 otherwise. Each key is capped at 246 bytes (the Linux VFS xattr-name limit minus the namespace prefix), and the combined size of all metadata on a file (keys plus values, with the namespace prefix counted per key) is capped at 4096 bytes to stay within the filesystem's per-inode xattr budget. Multiple files in a single multipart upload receive the same metadata. If the same `X-Metadata-<key>` header is sent more than once, only the first value is used. */
export const createFile: API.OperationMethod<
  CreateFileRequest,
  CreateFileResponse,
  CreateFileError,
  E2BEnvdOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateFileRequest,
  output: CreateFileResponse,
  errors: [UnknownE2BError],
  protocol: E2BEnvdProtocol,
  retry: Retry.Retry,
}));

export type CreateFileComposeError = E2BEnvdOpError;
/** Compose multiple files into a single file using zero-copy concatenation. Source files are deleted after successful composition. */
export const createFileCompose: API.OperationMethod<
  CreateFileComposeRequest,
  EntryInfo,
  CreateFileComposeError,
  E2BEnvdOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateFileComposeRequest,
  output: EntryInfo,
  errors: [UnknownE2BError],
  protocol: E2BEnvdProtocol,
  retry: Retry.Retry,
}));

export type GetEnvsError = E2BEnvdOpError;
/** Environment variables */
export const getEnvs: API.OperationMethod<
  GetEnvsRequest,
  GetEnvsResponse,
  GetEnvsError,
  E2BEnvdOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetEnvsRequest,
  output: GetEnvsResponse,
  errors: [UnknownE2BError],
  protocol: E2BEnvdProtocol,
  retry: Retry.Retry,
}));

export type GetFilesError = E2BEnvdOpError;
/** Download a file */
export const getFiles: API.OperationMethod<
  GetFilesRequest,
  DownloadFileResponse,
  GetFilesError,
  E2BEnvdOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetFilesRequest,
  output: DownloadFileResponse,
  errors: [UnknownE2BError],
  protocol: E2BEnvdProtocol,
  retry: Retry.Retry,
}));

export type GetHealthError = E2BEnvdOpError;
/** Check the health of the service */
export const getHealth: API.OperationMethod<
  GetHealthRequest,
  GetHealthResponse,
  GetHealthError,
  E2BEnvdOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetHealthRequest,
  output: GetHealthResponse,
  errors: [UnknownE2BError],
  protocol: E2BEnvdProtocol,
  retry: Retry.Retry,
}));

export type GetMetricsError = E2BEnvdOpError;
/** Service stats */
export const getMetrics: API.OperationMethod<
  GetMetricsRequest,
  Metrics,
  GetMetricsError,
  E2BEnvdOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetMetricsRequest,
  output: Metrics,
  errors: [UnknownE2BError],
  protocol: E2BEnvdProtocol,
  retry: Retry.Retry,
}));
