// AUTO-GENERATED by scripts/generate.ts from .generated-specs (e2b openapi/envd/proto → smithy). Do not edit.
import * as S from "@rikalabs/distilled-core/schema";
import * as API from "@rikalabs/distilled-core/api";
import * as T from "../traits.ts";
import {
  E2BProtocol,
  type E2BOpError,
  type E2BOpContext,
} from "../protocol.ts";
import { UnknownE2BError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { E2BOpError, E2BOpContext };

export type GetEventSandboxRequestTypesList = Array<string>;
export const GetEventSandboxRequestTypesList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<GetEventSandboxRequestTypesList>;

export interface GetEventSandboxRequest {
  sandboxID: string;
  offset?: number;
  limit?: number;
  orderAsc?: boolean;
  /** Filter events to the provided event types */
  types?: GetEventSandboxRequestTypesList;
}
export const GetEventSandboxRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    sandboxID: S.String.pipe(T.Label()),
    offset: S.optional(S.Number.pipe(T.Query())),
    limit: S.optional(S.Number.pipe(T.Query())),
    orderAsc: S.optional(S.Boolean.pipe(T.Query())),
    types: S.optional(GetEventSandboxRequestTypesList.pipe(T.Query())),
  }).pipe(
    T.Http({ method: "GET", uri: "/events/sandboxes/{sandboxID}", code: 200 }),
  ),
).annotate({
  identifier: "GetEventSandboxRequest",
}) as any as S.Schema<GetEventSandboxRequest>;

/** Sandbox event */
export interface SandboxEvent {
  /** Event unique identifier */
  id: string;
  /** Event structure version */
  version: string;
  /** Event name */
  type: string;
  /** Category of the event (e.g., 'lifecycle', 'process', etc.) */
  eventCategory?: string;
  /** Label for the specific event type (e.g., 'sandbox_started', 'process_oom', etc.) */
  eventLabel?: string;
  /** Optional JSON data associated with the event */
  eventData?: unknown | null;
  /** Timestamp of the event */
  timestamp: string;
  /** Unique identifier for the sandbox */
  sandboxId: string;
  /** Unique identifier for the sandbox execution */
  sandboxExecutionId: string;
  /** Unique identifier for the sandbox template */
  sandboxTemplateId: string;
  /** Unique identifier for the sandbox build */
  sandboxBuildId: string;
  /** Team identifier associated with the sandbox */
  sandboxTeamId: string;
}
export const SandboxEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    version: S.String,
    type: S.String,
    eventCategory: S.optional(S.String),
    eventLabel: S.optional(S.String),
    eventData: S.optional(S.NullOr(S.Unknown)),
    timestamp: S.String,
    sandboxId: S.String,
    sandboxExecutionId: S.String,
    sandboxTemplateId: S.String,
    sandboxBuildId: S.String,
    sandboxTeamId: S.String,
  }),
).annotate({ identifier: "SandboxEvent" }) as any as S.Schema<SandboxEvent>;

export type GetEventSandboxResponseBodyList = Array<SandboxEvent>;
export const GetEventSandboxResponseBodyList = /*@__PURE__*/ S.Array(
  SandboxEvent,
) as any as S.Schema<GetEventSandboxResponseBodyList>;

export type GetEventSandboxResponse = GetEventSandboxResponseBodyList;
export const GetEventSandboxResponse = /*@__PURE__*/ S.suspend(() =>
  GetEventSandboxResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "GetEventSandboxResponse",
}) as any as S.Schema<GetEventSandboxResponse>;

export type ListEventSandboxesRequestTypesList = Array<string>;
export const ListEventSandboxesRequestTypesList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<ListEventSandboxesRequestTypesList>;

export interface ListEventSandboxesRequest {
  offset?: number;
  limit?: number;
  orderAsc?: boolean;
  /** Filter events to the provided event types */
  types?: ListEventSandboxesRequestTypesList;
}
export const ListEventSandboxesRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    offset: S.optional(S.Number.pipe(T.Query())),
    limit: S.optional(S.Number.pipe(T.Query())),
    orderAsc: S.optional(S.Boolean.pipe(T.Query())),
    types: S.optional(ListEventSandboxesRequestTypesList.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/events/sandboxes", code: 200 })),
).annotate({
  identifier: "ListEventSandboxesRequest",
}) as any as S.Schema<ListEventSandboxesRequest>;

export type ListEventSandboxesResponseBodyList = Array<SandboxEvent>;
export const ListEventSandboxesResponseBodyList = /*@__PURE__*/ S.Array(
  SandboxEvent,
) as any as S.Schema<ListEventSandboxesResponseBodyList>;

export type ListEventSandboxesResponse = ListEventSandboxesResponseBodyList;
export const ListEventSandboxesResponse = /*@__PURE__*/ S.suspend(() =>
  ListEventSandboxesResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "ListEventSandboxesResponse",
}) as any as S.Schema<ListEventSandboxesResponse>;

export type GetEventSandboxError = E2BOpError;
/** Get sandbox events */
export const getEventSandbox: API.OperationMethod<
  GetEventSandboxRequest,
  GetEventSandboxResponse,
  GetEventSandboxError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetEventSandboxRequest,
  output: GetEventSandboxResponse,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));

export type ListEventSandboxesError = E2BOpError;
/** Get all sandbox events for the team associated with the API key */
export const listEventSandboxes: API.OperationMethod<
  ListEventSandboxesRequest,
  ListEventSandboxesResponse,
  ListEventSandboxesError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListEventSandboxesRequest,
  output: ListEventSandboxesResponse,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));
