// AUTO-GENERATED by scripts/generate.ts from .generated-specs (e2b openapi/envd/proto → smithy). Do not edit.
import * as S from "@rikalabs/distilled-core/schema";
import * as API from "@rikalabs/distilled-core/api";
import * as T from "../traits.ts";
import {
  E2BEnvdProtocol,
  type E2BEnvdOpError,
  type E2BEnvdOpContext,
} from "../protocol.ts";
import { UnknownE2BError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { E2BEnvdOpError, E2BEnvdOpContext };

export interface CreateWatcherRequest {
  path?: string;
  recursive?: boolean;
  /** If true, each FilesystemEvent includes the EntryInfo of the affected entry, when available. */
  includeEntry?: boolean;
  /** If true, allows watching paths on network filesystem mounts (NFS, CIFS, SMB, FUSE). Events on network mounts may be unreliable or not delivered at all. */
  allowNetworkMounts?: boolean;
}
export const CreateWatcherRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    path: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    recursive: S.optional(S.Boolean.pipe(T.ProtoField({ n: 2, t: "bool" }))),
    includeEntry: S.optional(S.Boolean.pipe(T.ProtoField({ n: 3, t: "bool" }))),
    allowNetworkMounts: S.optional(
      S.Boolean.pipe(T.ProtoField({ n: 4, t: "bool" })),
    ),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/filesystem.Filesystem/CreateWatcher",
      code: 200,
    }),
  ),
).annotate({
  identifier: "CreateWatcherRequest",
}) as any as S.Schema<CreateWatcherRequest>;

export interface CreateWatcherResponse {
  watcherId?: string;
}
export const CreateWatcherResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    watcherId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
  }),
).annotate({
  identifier: "CreateWatcherResponse",
}) as any as S.Schema<CreateWatcherResponse>;

export interface GetWatcherEventsRequest {
  watcherId?: string;
}
export const GetWatcherEventsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    watcherId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/filesystem.Filesystem/GetWatcherEvents",
      code: 200,
    }),
  ),
).annotate({
  identifier: "GetWatcherEventsRequest",
}) as any as S.Schema<GetWatcherEventsRequest>;

export type EventType =
  | "EVENT_TYPE_UNSPECIFIED"
  | "EVENT_TYPE_CREATE"
  | "EVENT_TYPE_WRITE"
  | "EVENT_TYPE_REMOVE"
  | "EVENT_TYPE_RENAME"
  | "EVENT_TYPE_CHMOD";
export const EventType = S.String;

export type FileType =
  | "FILE_TYPE_UNSPECIFIED"
  | "FILE_TYPE_FILE"
  | "FILE_TYPE_DIRECTORY"
  | "FILE_TYPE_SYMLINK";
export const FileType = S.String;

export type StringMap = { [key: string]: string | undefined };
export const StringMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<StringMap>;

export interface EntryInfo {
  name?: string;
  type?: FileType;
  path?: string;
  size?: string;
  mode?: number;
  permissions?: string;
  owner?: string;
  group?: string;
  modifiedTime?: string;
  /** If the entry is a symlink, this field contains the target of the symlink. */
  symlinkTarget?: string;
  /** User-defined metadata stored as extended attributes (xattrs) on the file. Keys live under the `user.e2b.` xattr namespace; the prefix is stripped here. Plain `user.*` xattrs written by other tooling are not reflected. */
  metadata?: StringMap;
}
export const EntryInfo = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    type: S.optional(
      FileType.pipe(
        T.ProtoField({
          n: 2,
          t: "enum",
          e: {
            FILE_TYPE_UNSPECIFIED: 0,
            FILE_TYPE_FILE: 1,
            FILE_TYPE_DIRECTORY: 2,
            FILE_TYPE_SYMLINK: 3,
          },
        }),
      ),
    ),
    path: S.optional(S.String.pipe(T.ProtoField({ n: 3, t: "string" }))),
    size: S.optional(S.String.pipe(T.ProtoField({ n: 4, t: "int64" }))),
    mode: S.optional(S.Number.pipe(T.ProtoField({ n: 5, t: "uint32" }))),
    permissions: S.optional(S.String.pipe(T.ProtoField({ n: 6, t: "string" }))),
    owner: S.optional(S.String.pipe(T.ProtoField({ n: 7, t: "string" }))),
    group: S.optional(S.String.pipe(T.ProtoField({ n: 8, t: "string" }))),
    modifiedTime: S.optional(
      S.String.pipe(T.ProtoField({ n: 9, t: "wkt", w: "Timestamp" })),
    ),
    symlinkTarget: S.optional(
      S.String.pipe(T.ProtoField({ n: 10, t: "string" })),
    ),
    metadata: S.optional(
      StringMap.pipe(
        T.ProtoField({ n: 11, t: "map", k: "string", v: { t: "string" } }),
      ),
    ),
  }),
).annotate({ identifier: "EntryInfo" }) as any as S.Schema<EntryInfo>;

export interface FilesystemEvent {
  name?: string;
  type?: EventType;
  /** Info of the entry that triggered the event. Only populated when include_entry was requested and the entry could be stat-ed (e.g. not set for remove/rename-away events, where the entry no longer exists at this path). */
  entry?: EntryInfo;
}
export const FilesystemEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    type: S.optional(
      EventType.pipe(
        T.ProtoField({
          n: 2,
          t: "enum",
          e: {
            EVENT_TYPE_UNSPECIFIED: 0,
            EVENT_TYPE_CREATE: 1,
            EVENT_TYPE_WRITE: 2,
            EVENT_TYPE_REMOVE: 3,
            EVENT_TYPE_RENAME: 4,
            EVENT_TYPE_CHMOD: 5,
          },
        }),
      ),
    ),
    entry: S.optional(EntryInfo.pipe(T.ProtoField({ n: 3, t: "message" }))),
  }),
).annotate({
  identifier: "FilesystemEvent",
}) as any as S.Schema<FilesystemEvent>;

export type FilesystemEventList = Array<FilesystemEvent>;
export const FilesystemEventList = /*@__PURE__*/ S.Array(
  FilesystemEvent,
) as any as S.Schema<FilesystemEventList>;

export interface GetWatcherEventsResponse {
  events?: FilesystemEventList;
}
export const GetWatcherEventsResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    events: S.optional(
      FilesystemEventList.pipe(T.ProtoField({ n: 1, t: "message", rep: true })),
    ),
  }),
).annotate({
  identifier: "GetWatcherEventsResponse",
}) as any as S.Schema<GetWatcherEventsResponse>;

export interface ListDirRequest {
  path?: string;
  depth?: number;
}
export const ListDirRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    path: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    depth: S.optional(S.Number.pipe(T.ProtoField({ n: 2, t: "uint32" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/filesystem.Filesystem/ListDir",
      code: 200,
    }),
  ),
).annotate({ identifier: "ListDirRequest" }) as any as S.Schema<ListDirRequest>;

export type EntryInfoList = Array<EntryInfo>;
export const EntryInfoList = /*@__PURE__*/ S.Array(
  EntryInfo,
) as any as S.Schema<EntryInfoList>;

export interface ListDirResponse {
  entries?: EntryInfoList;
}
export const ListDirResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    entries: S.optional(
      EntryInfoList.pipe(T.ProtoField({ n: 1, t: "message", rep: true })),
    ),
  }),
).annotate({
  identifier: "ListDirResponse",
}) as any as S.Schema<ListDirResponse>;

export interface MakeDirRequest {
  path?: string;
}
export const MakeDirRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    path: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/filesystem.Filesystem/MakeDir",
      code: 200,
    }),
  ),
).annotate({ identifier: "MakeDirRequest" }) as any as S.Schema<MakeDirRequest>;

export interface MakeDirResponse {
  entry?: EntryInfo;
}
export const MakeDirResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    entry: S.optional(EntryInfo.pipe(T.ProtoField({ n: 1, t: "message" }))),
  }),
).annotate({
  identifier: "MakeDirResponse",
}) as any as S.Schema<MakeDirResponse>;

export interface MoveRequest {
  source?: string;
  destination?: string;
}
export const MoveRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    source: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    destination: S.optional(S.String.pipe(T.ProtoField({ n: 2, t: "string" }))),
  }).pipe(
    T.Http({ method: "POST", uri: "/filesystem.Filesystem/Move", code: 200 }),
  ),
).annotate({ identifier: "MoveRequest" }) as any as S.Schema<MoveRequest>;

export interface MoveResponse {
  entry?: EntryInfo;
}
export const MoveResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    entry: S.optional(EntryInfo.pipe(T.ProtoField({ n: 1, t: "message" }))),
  }),
).annotate({ identifier: "MoveResponse" }) as any as S.Schema<MoveResponse>;

export interface RemoveRequest {
  path?: string;
}
export const RemoveRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    path: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
  }).pipe(
    T.Http({ method: "POST", uri: "/filesystem.Filesystem/Remove", code: 200 }),
  ),
).annotate({ identifier: "RemoveRequest" }) as any as S.Schema<RemoveRequest>;

export interface RemoveResponse {}
export const RemoveResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({ identifier: "RemoveResponse" }) as any as S.Schema<RemoveResponse>;

export interface RemoveWatcherRequest {
  watcherId?: string;
}
export const RemoveWatcherRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    watcherId: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/filesystem.Filesystem/RemoveWatcher",
      code: 200,
    }),
  ),
).annotate({
  identifier: "RemoveWatcherRequest",
}) as any as S.Schema<RemoveWatcherRequest>;

export interface RemoveWatcherResponse {}
export const RemoveWatcherResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "RemoveWatcherResponse",
}) as any as S.Schema<RemoveWatcherResponse>;

export interface StatRequest {
  path?: string;
}
export const StatRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    path: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
  }).pipe(
    T.Http({ method: "POST", uri: "/filesystem.Filesystem/Stat", code: 200 }),
  ),
).annotate({ identifier: "StatRequest" }) as any as S.Schema<StatRequest>;

export interface StatResponse {
  entry?: EntryInfo;
}
export const StatResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    entry: S.optional(EntryInfo.pipe(T.ProtoField({ n: 1, t: "message" }))),
  }),
).annotate({ identifier: "StatResponse" }) as any as S.Schema<StatResponse>;

export interface WatchDirRequest {
  path?: string;
  recursive?: boolean;
  /** If true, each FilesystemEvent includes the EntryInfo of the affected entry, when available. */
  includeEntry?: boolean;
  /** If true, allows watching paths on network filesystem mounts (NFS, CIFS, SMB, FUSE). Events on network mounts may be unreliable or not delivered at all. */
  allowNetworkMounts?: boolean;
}
export const WatchDirRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    path: S.optional(S.String.pipe(T.ProtoField({ n: 1, t: "string" }))),
    recursive: S.optional(S.Boolean.pipe(T.ProtoField({ n: 2, t: "bool" }))),
    includeEntry: S.optional(S.Boolean.pipe(T.ProtoField({ n: 3, t: "bool" }))),
    allowNetworkMounts: S.optional(
      S.Boolean.pipe(T.ProtoField({ n: 4, t: "bool" })),
    ),
  })
    .pipe(
      T.Http({
        method: "POST",
        uri: "/filesystem.Filesystem/WatchDir",
        code: 200,
      }),
    )
    .pipe(T.ConnectStream()),
).annotate({
  identifier: "WatchDirRequest",
}) as any as S.Schema<WatchDirRequest>;

export interface WatchDirResponseStartEvent {}
export const WatchDirResponseStartEvent = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "WatchDirResponseStartEvent",
}) as any as S.Schema<WatchDirResponseStartEvent>;

export type WatchDirResponseKeepAlive = WatchDirResponseStartEvent;
export const WatchDirResponseKeepAlive = WatchDirResponseStartEvent;

export interface WatchDirResponse {
  start?: WatchDirResponseStartEvent;
  filesystem?: FilesystemEvent;
  keepalive?: WatchDirResponseStartEvent;
}
export const WatchDirResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    start: S.optional(
      WatchDirResponseStartEvent.pipe(T.ProtoField({ n: 1, t: "message" })),
    ),
    filesystem: S.optional(
      FilesystemEvent.pipe(T.ProtoField({ n: 2, t: "message" })),
    ),
    keepalive: S.optional(
      WatchDirResponseStartEvent.pipe(T.ProtoField({ n: 3, t: "message" })),
    ),
  }),
).annotate({
  identifier: "WatchDirResponse",
}) as any as S.Schema<WatchDirResponse>;

export type CreateWatcherError = E2BEnvdOpError;
/** Non-streaming versions of WatchDir */
export const createWatcher: API.OperationMethod<
  CreateWatcherRequest,
  CreateWatcherResponse,
  CreateWatcherError,
  E2BEnvdOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateWatcherRequest,
  output: CreateWatcherResponse,
  errors: [UnknownE2BError],
  protocol: E2BEnvdProtocol,
  retry: Retry.Retry,
}));

export type GetWatcherEventsError = E2BEnvdOpError;
export const getWatcherEvents: API.OperationMethod<
  GetWatcherEventsRequest,
  GetWatcherEventsResponse,
  GetWatcherEventsError,
  E2BEnvdOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetWatcherEventsRequest,
  output: GetWatcherEventsResponse,
  errors: [UnknownE2BError],
  protocol: E2BEnvdProtocol,
  retry: Retry.Retry,
}));

export type ListDirError = E2BEnvdOpError;
export const listDir: API.OperationMethod<
  ListDirRequest,
  ListDirResponse,
  ListDirError,
  E2BEnvdOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListDirRequest,
  output: ListDirResponse,
  errors: [UnknownE2BError],
  protocol: E2BEnvdProtocol,
  retry: Retry.Retry,
}));

export type MakeDirError = E2BEnvdOpError;
export const makeDir: API.OperationMethod<
  MakeDirRequest,
  MakeDirResponse,
  MakeDirError,
  E2BEnvdOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: MakeDirRequest,
  output: MakeDirResponse,
  errors: [UnknownE2BError],
  protocol: E2BEnvdProtocol,
  retry: Retry.Retry,
}));

export type MoveError = E2BEnvdOpError;
export const move: API.OperationMethod<
  MoveRequest,
  MoveResponse,
  MoveError,
  E2BEnvdOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: MoveRequest,
  output: MoveResponse,
  errors: [UnknownE2BError],
  protocol: E2BEnvdProtocol,
  retry: Retry.Retry,
}));

export type RemoveError = E2BEnvdOpError;
export const remove: API.OperationMethod<
  RemoveRequest,
  RemoveResponse,
  RemoveError,
  E2BEnvdOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: RemoveRequest,
  output: RemoveResponse,
  errors: [UnknownE2BError],
  protocol: E2BEnvdProtocol,
  retry: Retry.Retry,
}));

export type RemoveWatcherError = E2BEnvdOpError;
export const removeWatcher: API.OperationMethod<
  RemoveWatcherRequest,
  RemoveWatcherResponse,
  RemoveWatcherError,
  E2BEnvdOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: RemoveWatcherRequest,
  output: RemoveWatcherResponse,
  errors: [UnknownE2BError],
  protocol: E2BEnvdProtocol,
  retry: Retry.Retry,
}));

export type StatError = E2BEnvdOpError;
export const stat: API.OperationMethod<
  StatRequest,
  StatResponse,
  StatError,
  E2BEnvdOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: StatRequest,
  output: StatResponse,
  errors: [UnknownE2BError],
  protocol: E2BEnvdProtocol,
  retry: Retry.Retry,
}));

export type WatchDirError = E2BEnvdOpError;
export const watchDir: API.StreamingOperationMethod<
  WatchDirRequest,
  WatchDirResponse,
  WatchDirError,
  E2BEnvdOpContext
> = /*@__PURE__*/ API.makeStream(() => ({
  input: WatchDirRequest,
  output: WatchDirResponse,
  errors: [UnknownE2BError],
  protocol: E2BEnvdProtocol,
  retry: Retry.Retry,
}));
