// AUTO-GENERATED by scripts/generate.ts from .generated-specs (e2b openapi/envd/proto → smithy). Do not edit.
import * as S from "@rikalabs/distilled-core/schema";
import * as API from "@rikalabs/distilled-core/api";
import * as T from "../traits.ts";
import {
  E2BProtocol,
  type E2BOpError,
  type E2BOpContext,
} from "../protocol.ts";
import { UnknownE2BError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { E2BOpError, E2BOpContext };

export interface GetHealthRequest {}
export const GetHealthRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(T.Http({ method: "GET", uri: "/health", code: 200 })),
).annotate({
  identifier: "GetHealthRequest",
}) as any as S.Schema<GetHealthRequest>;

export interface GetHealthResponse {}
export const GetHealthResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "GetHealthResponse",
}) as any as S.Schema<GetHealthResponse>;

export type GetHealthError = E2BOpError;
/** Health check Health check */
export const getHealth: API.OperationMethod<
  GetHealthRequest,
  GetHealthResponse,
  GetHealthError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetHealthRequest,
  output: GetHealthResponse,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));
