// AUTO-GENERATED by scripts/generate.ts from .generated-specs (e2b openapi/envd/proto → smithy). Do not edit.
import * as S from "@rikalabs/distilled-core/schema";
import * as API from "@rikalabs/distilled-core/api";
import * as T from "../traits.ts";
import {
  E2BProtocol,
  type E2BOpError,
  type E2BOpContext,
} from "../protocol.ts";
import { UnknownE2BError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { E2BOpError, E2BOpContext };

/** Customer metadata of the secret. Always present, empty when unset. At most 32 entries; keys are limited to 128 bytes, values to 1024 bytes, and a secret's metadata to 8192 bytes in total. */
export type SecretMetadata = { [key: string]: string | undefined };
export const SecretMetadata = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<SecretMetadata>;

export interface CreateSecretRequest {
  /** Name of the secret, unique within the project. Names are lower-cased before storage and returned in that canonical form; the sec_ prefix is reserved for secret identifiers. */
  name: string;
  /** Runtime marker stored as the secret's first version. The runtime resolves it to a value at sandbox egress. */
  value: string;
  metadata?: SecretMetadata;
}
export const CreateSecretRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.String,
    value: S.String,
    metadata: S.optional(SecretMetadata),
  }).pipe(T.Http({ method: "POST", uri: "/secrets", code: 200 })),
).annotate({
  identifier: "CreateSecretRequest",
}) as any as S.Schema<CreateSecretRequest>;

/** Metadata of a secret. It never carries the secret value. */
export interface Secret {
  /** Identifier of the secret */
  secretID: string;
  /** Name of the secret, unique within the project */
  name: string;
  /** Version served to readers that do not name one */
  currentVersion: number;
  metadata: SecretMetadata;
  /** Time when the secret was created */
  createdAt: string;
  /** Time when the secret was last updated */
  updatedAt: string;
}
export const Secret = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    secretID: S.String,
    name: S.String,
    currentVersion: S.Number,
    metadata: SecretMetadata,
    createdAt: S.String,
    updatedAt: S.String,
  }),
).annotate({ identifier: "Secret" }) as any as S.Schema<Secret>;

export interface DeleteSecretRequest {
  secretID: string;
}
export const DeleteSecretRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    secretID: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "DELETE", uri: "/secrets/{secretID}", code: 200 })),
).annotate({
  identifier: "DeleteSecretRequest",
}) as any as S.Schema<DeleteSecretRequest>;

export interface DeleteSecretResponse {}
export const DeleteSecretResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "DeleteSecretResponse",
}) as any as S.Schema<DeleteSecretResponse>;

export interface GetSecretRequest {
  secretID: string;
}
export const GetSecretRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    secretID: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "GET", uri: "/secrets/{secretID}", code: 200 })),
).annotate({
  identifier: "GetSecretRequest",
}) as any as S.Schema<GetSecretRequest>;

export interface ListSecretsRequest {
  /** Cursor to start the list from */
  nextToken?: string;
  /** Maximum number of items to return per page */
  limit?: number;
}
export const ListSecretsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    nextToken: S.optional(S.String.pipe(T.Query())),
    limit: S.optional(S.Number.pipe(T.Query())),
  }).pipe(T.Http({ method: "GET", uri: "/secrets", code: 200 })),
).annotate({
  identifier: "ListSecretsRequest",
}) as any as S.Schema<ListSecretsRequest>;

export type ListSecretsResponseBodyList = Array<Secret>;
export const ListSecretsResponseBodyList = /*@__PURE__*/ S.Array(
  Secret,
) as any as S.Schema<ListSecretsResponseBodyList>;

export interface ListSecretsResponse {
  secrets: ListSecretsResponseBodyList;
  nextToken?: string;
}
export const ListSecretsResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    secrets: ListSecretsResponseBodyList.pipe(T.RawResponse()),
    nextToken: S.optional(S.String.pipe(T.Header("X-Next-Token"))),
  }),
).annotate({
  identifier: "ListSecretsResponse",
}) as any as S.Schema<ListSecretsResponse>;

export interface UpdateSecretRequest {
  secretID: string;
  /** Runtime marker stored as the secret's new version. The runtime resolves it to a value at sandbox egress. */
  value: string;
  metadata?: SecretMetadata;
}
export const UpdateSecretRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    secretID: S.String.pipe(T.Label()),
    value: S.String,
    metadata: S.optional(SecretMetadata),
  }).pipe(T.Http({ method: "POST", uri: "/secrets/{secretID}", code: 200 })),
).annotate({
  identifier: "UpdateSecretRequest",
}) as any as S.Schema<UpdateSecretRequest>;

export type CreateSecretError = E2BOpError;
/** Create a secret Create a secret by storing a runtime marker as its first version. The response carries metadata only. */
export const createSecret: API.OperationMethod<
  CreateSecretRequest,
  Secret,
  CreateSecretError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateSecretRequest,
  output: Secret,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));

export type DeleteSecretError = E2BOpError;
/** Delete a secret Revoke the secret and schedule its versions for cleanup. */
export const deleteSecret: API.OperationMethod<
  DeleteSecretRequest,
  DeleteSecretResponse,
  DeleteSecretError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteSecretRequest,
  output: DeleteSecretResponse,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));

export type GetSecretError = E2BOpError;
/** Get a secret Get one secret's metadata, selected by identifier or name. */
export const getSecret: API.OperationMethod<
  GetSecretRequest,
  Secret,
  GetSecretError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetSecretRequest,
  output: Secret,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));

export type ListSecretsError = E2BOpError;
/** List project secrets List the project's secrets. No response carries a secret value. */
export const listSecrets: API.PaginatedOperationMethod<
  ListSecretsRequest,
  ListSecretsResponse,
  ListSecretsError,
  E2BOpContext,
  Secret
> = /*@__PURE__*/ API.makePaginated(() => ({
  input: ListSecretsRequest,
  output: ListSecretsResponse,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
  pagination: {
    mode: "token",
    inputToken: "nextToken",
    outputToken: "nextToken",
    items: "secrets",
  } as const,
})) as any;

export type UpdateSecretError = E2BOpError;
/** Update a secret Replace the secret's stored marker by appending a new version. The response carries metadata only. */
export const updateSecret: API.OperationMethod<
  UpdateSecretRequest,
  Secret,
  UpdateSecretError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateSecretRequest,
  output: Secret,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));
