// AUTO-GENERATED by scripts/generate.ts from .generated-specs (e2b openapi/envd/proto → smithy). Do not edit.
import * as S from "@rikalabs/distilled-core/schema";
import * as API from "@rikalabs/distilled-core/api";
import * as T from "../traits.ts";
import {
  E2BProtocol,
  type E2BOpError,
  type E2BOpContext,
} from "../protocol.ts";
import { UnknownE2BError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { E2BOpError, E2BOpContext };

export interface CreateVolumeRequest {
  /** Name of the volume */
  name: string;
}
export const CreateVolumeRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.String,
  }).pipe(T.Http({ method: "POST", uri: "/volumes", code: 200 })),
).annotate({
  identifier: "CreateVolumeRequest",
}) as any as S.Schema<CreateVolumeRequest>;

export interface VolumeAndToken {
  /** ID of the volume */
  volumeID: string;
  /** Name of the volume */
  name: string;
  /** Auth token to use for interacting with volume content */
  token: string;
  /** Domain to use as the destination for volume content requests, replacing the default `api.<E2B_DOMAIN>`. Only returned when the team is connected to a custom (BYOC) cluster; absent otherwise, in which case the default domain is used. */
  domain?: string;
}
export const VolumeAndToken = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    volumeID: S.String,
    name: S.String,
    token: S.String,
    domain: S.optional(S.String),
  }),
).annotate({ identifier: "VolumeAndToken" }) as any as S.Schema<VolumeAndToken>;

export interface DeleteVolumeRequest {
  volumeID: string;
}
export const DeleteVolumeRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    volumeID: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "DELETE", uri: "/volumes/{volumeID}", code: 200 })),
).annotate({
  identifier: "DeleteVolumeRequest",
}) as any as S.Schema<DeleteVolumeRequest>;

export interface DeleteVolumeResponse {}
export const DeleteVolumeResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "DeleteVolumeResponse",
}) as any as S.Schema<DeleteVolumeResponse>;

export interface GetVolumeRequest {
  volumeID: string;
}
export const GetVolumeRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    volumeID: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "GET", uri: "/volumes/{volumeID}", code: 200 })),
).annotate({
  identifier: "GetVolumeRequest",
}) as any as S.Schema<GetVolumeRequest>;

export interface ListVolumesRequest {}
export const ListVolumesRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(T.Http({ method: "GET", uri: "/volumes", code: 200 })),
).annotate({
  identifier: "ListVolumesRequest",
}) as any as S.Schema<ListVolumesRequest>;

export interface Volume {
  /** ID of the volume */
  volumeID: string;
  /** Name of the volume */
  name: string;
}
export const Volume = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    volumeID: S.String,
    name: S.String,
  }),
).annotate({ identifier: "Volume" }) as any as S.Schema<Volume>;

export type ListVolumesResponseBodyList = Array<Volume>;
export const ListVolumesResponseBodyList = /*@__PURE__*/ S.Array(
  Volume,
) as any as S.Schema<ListVolumesResponseBodyList>;

export type ListVolumesResponse = ListVolumesResponseBodyList;
export const ListVolumesResponse = /*@__PURE__*/ S.suspend(() =>
  ListVolumesResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "ListVolumesResponse",
}) as any as S.Schema<ListVolumesResponse>;

export type CreateVolumeError = E2BOpError;
/** Create team volume Create a new team volume */
export const createVolume: API.OperationMethod<
  CreateVolumeRequest,
  VolumeAndToken,
  CreateVolumeError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateVolumeRequest,
  output: VolumeAndToken,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));

export type DeleteVolumeError = E2BOpError;
/** Delete team volume Delete a team volume */
export const deleteVolume: API.OperationMethod<
  DeleteVolumeRequest,
  DeleteVolumeResponse,
  DeleteVolumeError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteVolumeRequest,
  output: DeleteVolumeResponse,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));

export type GetVolumeError = E2BOpError;
/** Team volume Get team volume info */
export const getVolume: API.OperationMethod<
  GetVolumeRequest,
  VolumeAndToken,
  GetVolumeError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetVolumeRequest,
  output: VolumeAndToken,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));

export type ListVolumesError = E2BOpError;
/** List team volumes List all team volumes */
export const listVolumes: API.OperationMethod<
  ListVolumesRequest,
  ListVolumesResponse,
  ListVolumesError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListVolumesRequest,
  output: ListVolumesResponse,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));
