// AUTO-GENERATED by scripts/generate.ts from .generated-specs (e2b openapi/envd/proto → smithy). Do not edit.
import * as S from "@rikalabs/distilled-core/schema";
import * as API from "@rikalabs/distilled-core/api";
import * as T from "../traits.ts";
import {
  E2BProtocol,
  type E2BOpError,
  type E2BOpContext,
} from "../protocol.ts";
import { UnknownE2BError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { E2BOpError, E2BOpContext };

export type CreateEventWebhookRequestEventsList = Array<string>;
export const CreateEventWebhookRequestEventsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<CreateEventWebhookRequestEventsList>;

export interface CreateEventWebhookRequest {
  name: string;
  url: string;
  events: CreateEventWebhookRequestEventsList;
  enabled?: boolean;
  /** Secret used to sign the webhook payloads */
  signatureSecret: string;
}
export const CreateEventWebhookRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    name: S.String,
    url: S.String,
    events: CreateEventWebhookRequestEventsList,
    enabled: S.optional(S.Boolean),
    signatureSecret: S.String,
  }).pipe(T.Http({ method: "POST", uri: "/events/webhooks", code: 200 })),
).annotate({
  identifier: "CreateEventWebhookRequest",
}) as any as S.Schema<CreateEventWebhookRequest>;

export type WebhookCreationEventsList = Array<string>;
export const WebhookCreationEventsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<WebhookCreationEventsList>;

/** Webhook creation response */
export interface WebhookCreation {
  /** Webhook unique identifier */
  id: string;
  /** Webhook user friendly name */
  name: string;
  /** Time when the template was created */
  createdAt: string;
  /** Unique identifier for the team */
  teamId: string;
  url: string;
  enabled: boolean;
  events: WebhookCreationEventsList;
}
export const WebhookCreation = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    name: S.String,
    createdAt: S.String,
    teamId: S.String,
    url: S.String,
    enabled: S.Boolean,
    events: WebhookCreationEventsList,
  }),
).annotate({
  identifier: "WebhookCreation",
}) as any as S.Schema<WebhookCreation>;

export interface DeleteEventWebhookRequest {
  webhookID: string;
}
export const DeleteEventWebhookRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    webhookID: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "DELETE",
      uri: "/events/webhooks/{webhookID}",
      code: 200,
    }),
  ),
).annotate({
  identifier: "DeleteEventWebhookRequest",
}) as any as S.Schema<DeleteEventWebhookRequest>;

export interface DeleteEventWebhookResponse {}
export const DeleteEventWebhookResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "DeleteEventWebhookResponse",
}) as any as S.Schema<DeleteEventWebhookResponse>;

export interface GetEventWebhookRequest {
  webhookID: string;
}
export const GetEventWebhookRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    webhookID: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({ method: "GET", uri: "/events/webhooks/{webhookID}", code: 200 }),
  ),
).annotate({
  identifier: "GetEventWebhookRequest",
}) as any as S.Schema<GetEventWebhookRequest>;

export type WebhookDetailEventsList = Array<string>;
export const WebhookDetailEventsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<WebhookDetailEventsList>;

/** Webhook detail response */
export interface WebhookDetail {
  /** Webhook unique identifier */
  id: string;
  /** Unique identifier for the team */
  teamId: string;
  /** Webhook user friendly name */
  name: string;
  /** Time when the template was created */
  createdAt: string;
  url: string;
  enabled: boolean;
  events: WebhookDetailEventsList;
}
export const WebhookDetail = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    teamId: S.String,
    name: S.String,
    createdAt: S.String,
    url: S.String,
    enabled: S.Boolean,
    events: WebhookDetailEventsList,
  }),
).annotate({ identifier: "WebhookDetail" }) as any as S.Schema<WebhookDetail>;

export type ListEventWebhookDeliveriesRequestDeliveryStatusItem =
  | "success"
  | "failed";
export const ListEventWebhookDeliveriesRequestDeliveryStatusItem = S.String;

export type ListEventWebhookDeliveriesRequestDeliveryStatusList = Array<
  ListEventWebhookDeliveriesRequestDeliveryStatusItem | (string & {})
>;
export const ListEventWebhookDeliveriesRequestDeliveryStatusList =
  /*@__PURE__*/ S.Array(
    ListEventWebhookDeliveriesRequestDeliveryStatusItem,
  ) as any as S.Schema<ListEventWebhookDeliveriesRequestDeliveryStatusList>;

export type ListEventWebhookDeliveriesRequestEventTypeList = Array<string>;
export const ListEventWebhookDeliveriesRequestEventTypeList =
  /*@__PURE__*/ S.Array(
    S.String,
  ) as any as S.Schema<ListEventWebhookDeliveriesRequestEventTypeList>;

export interface ListEventWebhookDeliveriesRequest {
  webhookID: string;
  /** Opaque cursor from the previous response's nextCursor field. */
  cursor?: string;
  limit?: number;
  orderAsc?: boolean;
  /** Include deliveries at or after this timestamp. */
  start?: string;
  /** Include deliveries before this timestamp. */
  end?: string;
  /** Filter deliveries by delivery status */
  deliveryStatus?: ListEventWebhookDeliveriesRequestDeliveryStatusList;
  /** Filter deliveries by event type */
  eventType?: ListEventWebhookDeliveriesRequestEventTypeList;
}
export const ListEventWebhookDeliveriesRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    webhookID: S.String.pipe(T.Label()),
    cursor: S.optional(S.String.pipe(T.Query())),
    limit: S.optional(S.Number.pipe(T.Query())),
    orderAsc: S.optional(S.Boolean.pipe(T.Query())),
    start: S.optional(S.String.pipe(T.Query())),
    end: S.optional(S.String.pipe(T.Query())),
    deliveryStatus: S.optional(
      ListEventWebhookDeliveriesRequestDeliveryStatusList.pipe(
        T.Query(),
        T.QueryJoin(","),
      ),
    ),
    eventType: S.optional(
      ListEventWebhookDeliveriesRequestEventTypeList.pipe(
        T.Query(),
        T.QueryJoin(","),
      ),
    ),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/events/webhooks/{webhookID}/deliveries",
      code: 200,
    }),
  ),
).annotate({
  identifier: "ListEventWebhookDeliveriesRequest",
}) as any as S.Schema<ListEventWebhookDeliveriesRequest>;

/** Delivery attempt status */
export type WebhookDeliveryStatus = "success" | "failed";
export const WebhookDeliveryStatus = S.String;

/** Machine-readable non-HTTP or HTTP failure class */
export type WebhookDeliveryErrorClass =
  | "http_error"
  | "dns_error"
  | "timeout"
  | "transport_error"
  | "request_error"
  | "signature_error"
  | "canceled";
export const WebhookDeliveryErrorClass = S.String;

/** Webhook delivery attempt */
export interface WebhookDelivery {
  /** Delivery attempt identifier */
  id: string;
  /** Team identifier */
  teamId: string;
  /** Webhook configuration identifier */
  webhookId: string;
  /** Sandbox event identifier */
  eventId: string;
  /** Sandbox identifier */
  sandboxId: string;
  /** Sandbox event type */
  eventType: string;
  /** Delivery attempt status */
  status: WebhookDeliveryStatus;
  /** Delivery request duration in milliseconds */
  durationMs: number;
  /** Serialized webhook request body */
  requestBody: string;
  /** JSON-encoded request headers with sensitive values redacted */
  requestHeaders: string;
  /** URL attempted for this delivery */
  requestUrl: string;
  /** Truncated response body, if a response was received */
  responseBody?: string | null;
  /** JSON-encoded response headers, if a response was received */
  responseHeaders?: string | null;
  /** HTTP response status code, if a response was received */
  responseHttpStatusCode?: number | null;
  /** Machine-readable non-HTTP or HTTP failure class */
  errorClass: WebhookDeliveryErrorClass | null;
  /** Error message for failures without a useful response body */
  errorMessage?: string | null;
  /** Time when the delivery attempt started */
  timestamp: string;
}
export const WebhookDelivery = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    teamId: S.String,
    webhookId: S.String,
    eventId: S.String,
    sandboxId: S.String,
    eventType: S.String,
    status: WebhookDeliveryStatus,
    durationMs: S.Number,
    requestBody: S.String,
    requestHeaders: S.String,
    requestUrl: S.String,
    responseBody: S.optional(S.NullOr(S.String)),
    responseHeaders: S.optional(S.NullOr(S.String)),
    responseHttpStatusCode: S.optional(S.NullOr(S.Number)),
    errorClass: S.NullOr(WebhookDeliveryErrorClass),
    errorMessage: S.optional(S.NullOr(S.String)),
    timestamp: S.String,
  }),
).annotate({
  identifier: "WebhookDelivery",
}) as any as S.Schema<WebhookDelivery>;

export type WebhookDeliveryGroupAttemptsList = Array<WebhookDelivery>;
export const WebhookDeliveryGroupAttemptsList = /*@__PURE__*/ S.Array(
  WebhookDelivery,
) as any as S.Schema<WebhookDeliveryGroupAttemptsList>;

/** Webhook delivery attempts grouped by sandbox event */
export interface WebhookDeliveryGroup {
  eventId: string;
  eventType: string;
  sandboxId: string;
  attempts: WebhookDeliveryGroupAttemptsList;
}
export const WebhookDeliveryGroup = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    eventId: S.String,
    eventType: S.String,
    sandboxId: S.String,
    attempts: WebhookDeliveryGroupAttemptsList,
  }),
).annotate({
  identifier: "WebhookDeliveryGroup",
}) as any as S.Schema<WebhookDeliveryGroup>;

export type WebhookDeliveriesListPayloadDataList = Array<WebhookDeliveryGroup>;
export const WebhookDeliveriesListPayloadDataList = /*@__PURE__*/ S.Array(
  WebhookDeliveryGroup,
) as any as S.Schema<WebhookDeliveriesListPayloadDataList>;

/** Paginated webhook delivery attempts grouped by event */
export interface WebhookDeliveriesListPayload {
  data: WebhookDeliveriesListPayloadDataList;
  /** Cursor to pass to the next list request, or null when there is no next page. */
  nextCursor: string | null;
}
export const WebhookDeliveriesListPayload = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    data: WebhookDeliveriesListPayloadDataList,
    nextCursor: S.NullOr(S.String),
  }),
).annotate({
  identifier: "WebhookDeliveriesListPayload",
}) as any as S.Schema<WebhookDeliveriesListPayload>;

export interface ListEventWebhooksRequest {}
export const ListEventWebhooksRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(
    T.Http({ method: "GET", uri: "/events/webhooks", code: 200 }),
  ),
).annotate({
  identifier: "ListEventWebhooksRequest",
}) as any as S.Schema<ListEventWebhooksRequest>;

export type ListEventWebhooksResponseBodyList = Array<WebhookDetail>;
export const ListEventWebhooksResponseBodyList = /*@__PURE__*/ S.Array(
  WebhookDetail,
) as any as S.Schema<ListEventWebhooksResponseBodyList>;

export type ListEventWebhooksResponse = ListEventWebhooksResponseBodyList;
export const ListEventWebhooksResponse = /*@__PURE__*/ S.suspend(() =>
  ListEventWebhooksResponseBodyList.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "ListEventWebhooksResponse",
}) as any as S.Schema<ListEventWebhooksResponse>;

export interface ListEventWebhookStatsRequest {
  webhookID: string;
  /** Inclusive stats range start. Defaults to 24 hours ago. */
  start?: string;
  /** Exclusive stats range end. Defaults to now. */
  end?: string;
}
export const ListEventWebhookStatsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    webhookID: S.String.pipe(T.Label()),
    start: S.optional(S.String.pipe(T.Query())),
    end: S.optional(S.String.pipe(T.Query())),
  }).pipe(
    T.Http({
      method: "GET",
      uri: "/events/webhooks/{webhookID}/stats",
      code: 200,
    }),
  ),
).annotate({
  identifier: "ListEventWebhookStatsRequest",
}) as any as S.Schema<ListEventWebhookStatsRequest>;

/** Webhook delivery duration statistics in milliseconds */
export interface WebhookDeliveryDurationStats {
  minimum: number;
  average: number;
  maximum: number;
}
export const WebhookDeliveryDurationStats = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    minimum: S.Number,
    average: S.Number,
    maximum: S.Number,
  }),
).annotate({
  identifier: "WebhookDeliveryDurationStats",
}) as any as S.Schema<WebhookDeliveryDurationStats>;

/** Webhook delivery stats for a time bucket */
export interface WebhookDeliveryStatsBucket {
  timestamp: string;
  total: number;
  failed: number;
  durationMs: WebhookDeliveryDurationStats;
}
export const WebhookDeliveryStatsBucket = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    timestamp: S.String,
    total: S.Number,
    failed: S.Number,
    durationMs: WebhookDeliveryDurationStats,
  }),
).annotate({
  identifier: "WebhookDeliveryStatsBucket",
}) as any as S.Schema<WebhookDeliveryStatsBucket>;

export type WebhookDeliveryStatsBucketsList = Array<WebhookDeliveryStatsBucket>;
export const WebhookDeliveryStatsBucketsList = /*@__PURE__*/ S.Array(
  WebhookDeliveryStatsBucket,
) as any as S.Schema<WebhookDeliveryStatsBucketsList>;

/** Webhook delivery aggregate stats */
export interface WebhookDeliveryStats {
  buckets: WebhookDeliveryStatsBucketsList;
  total: number;
  failed: number;
  durationMs: WebhookDeliveryDurationStats;
}
export const WebhookDeliveryStats = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    buckets: WebhookDeliveryStatsBucketsList,
    total: S.Number,
    failed: S.Number,
    durationMs: WebhookDeliveryDurationStats,
  }),
).annotate({
  identifier: "WebhookDeliveryStats",
}) as any as S.Schema<WebhookDeliveryStats>;

export type UpdateEventWebhookRequestEventsList = Array<string>;
export const UpdateEventWebhookRequestEventsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<UpdateEventWebhookRequestEventsList>;

export interface UpdateEventWebhookRequest {
  webhookID: string;
  enabled?: boolean;
  /** Webhook user friendly name */
  name?: string;
  url?: string;
  events?: UpdateEventWebhookRequestEventsList;
  /** Secret used to sign the webhook payloads */
  signatureSecret?: string;
}
export const UpdateEventWebhookRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    webhookID: S.String.pipe(T.Label()),
    enabled: S.optional(S.Boolean),
    name: S.optional(S.String),
    url: S.optional(S.String),
    events: S.optional(UpdateEventWebhookRequestEventsList),
    signatureSecret: S.optional(S.String),
  }).pipe(
    T.Http({ method: "PATCH", uri: "/events/webhooks/{webhookID}", code: 200 }),
  ),
).annotate({
  identifier: "UpdateEventWebhookRequest",
}) as any as S.Schema<UpdateEventWebhookRequest>;

export type CreateEventWebhookError = E2BOpError;
/** Register events webhook. */
export const createEventWebhook: API.OperationMethod<
  CreateEventWebhookRequest,
  WebhookCreation,
  CreateEventWebhookError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateEventWebhookRequest,
  output: WebhookCreation,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));

export type DeleteEventWebhookError = E2BOpError;
/** Delete a registered webhook. */
export const deleteEventWebhook: API.OperationMethod<
  DeleteEventWebhookRequest,
  DeleteEventWebhookResponse,
  DeleteEventWebhookError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteEventWebhookRequest,
  output: DeleteEventWebhookResponse,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));

export type GetEventWebhookError = E2BOpError;
/** Get a registered webhook. */
export const getEventWebhook: API.OperationMethod<
  GetEventWebhookRequest,
  WebhookDetail,
  GetEventWebhookError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetEventWebhookRequest,
  output: WebhookDetail,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));

export type ListEventWebhookDeliveriesError = E2BOpError;
/** List webhook delivery attempts. */
export const listEventWebhookDeliveries: API.OperationMethod<
  ListEventWebhookDeliveriesRequest,
  WebhookDeliveriesListPayload,
  ListEventWebhookDeliveriesError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListEventWebhookDeliveriesRequest,
  output: WebhookDeliveriesListPayload,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));

export type ListEventWebhooksError = E2BOpError;
/** List registered webhooks. */
export const listEventWebhooks: API.OperationMethod<
  ListEventWebhooksRequest,
  ListEventWebhooksResponse,
  ListEventWebhooksError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListEventWebhooksRequest,
  output: ListEventWebhooksResponse,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));

export type ListEventWebhookStatsError = E2BOpError;
/** Get webhook delivery aggregate stats. */
export const listEventWebhookStats: API.OperationMethod<
  ListEventWebhookStatsRequest,
  WebhookDeliveryStats,
  ListEventWebhookStatsError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ListEventWebhookStatsRequest,
  output: WebhookDeliveryStats,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));

export type UpdateEventWebhookError = E2BOpError;
/** Update a registered webhook configuration. */
export const updateEventWebhook: API.OperationMethod<
  UpdateEventWebhookRequest,
  WebhookDetail,
  UpdateEventWebhookError,
  E2BOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UpdateEventWebhookRequest,
  output: WebhookDetail,
  errors: [UnknownE2BError],
  protocol: E2BProtocol,
  retry: Retry.Retry,
}));
