// AUTO-GENERATED by scripts/generate.ts from .generated-specs-sandbox (spec/sandbox-bridge.openapi.json). Do not edit.
import * as S from "@rikalabs/distilled-core/schema";
import * as API from "@rikalabs/distilled-core/api";
import * as C from "@rikalabs/distilled-core/category";
import * as T from "../traits.ts";
import {
  SandboxBridgeProtocol,
  type SandboxBridgeOpError,
  type SandboxBridgeOpContext,
} from "../protocol.ts";
import { UnknownCloudflareSandboxError } from "../errors.ts";
import * as Retry from "../retry.ts";

export type { SandboxBridgeOpError, SandboxBridgeOpContext };

export class BadRequest
  extends /*@__PURE__*/ T.applyErrorMatchers(
    /*@__PURE__*/ S.TaggedError<BadRequest>()("BadRequest", {
      code: S.Number,
      message: S.String,
    }).pipe(C.withBadRequestError),
    [{ status: 400 }],
  ) {}

export interface CheckHealthRequest {}
export const CheckHealthRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(T.Http({ method: "GET", uri: "/health", code: 200 })),
).annotate({
  identifier: "CheckHealthRequest",
}) as any as S.Schema<CheckHealthRequest>;

export interface OkResponse {
  /** Always `true` on success. */
  ok: boolean;
}
export const OkResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    ok: S.Boolean,
  }),
).annotate({ identifier: "OkResponse" }) as any as S.Schema<OkResponse>;

export interface CreateSandboxRequest {}
export const CreateSandboxRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(T.Http({ method: "POST", uri: "/v1/sandbox", code: 200 })),
).annotate({
  identifier: "CreateSandboxRequest",
}) as any as S.Schema<CreateSandboxRequest>;

export interface CreateSandboxResponse {
  /** Unique sandbox ID for use with `/v1/sandbox/{id}/*` routes. */
  id: string;
}
export const CreateSandboxResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
  }),
).annotate({
  identifier: "CreateSandboxResponse",
}) as any as S.Schema<CreateSandboxResponse>;

/** Environment variables scoped to this session. */
export type CreateSessionRequestEnvMap = { [key: string]: string | undefined };
export const CreateSessionRequestEnvMap = /*@__PURE__*/ S.Record(
  S.String,
  S.String,
) as any as S.Schema<CreateSessionRequestEnvMap>;

export interface CreateSessionRequest {
  /** Sandbox instance name. */
  id: string;
  /** Initial working directory for the session. */
  cwd?: string;
  /** Environment variables scoped to this session. */
  env?: CreateSessionRequestEnvMap;
}
export const CreateSessionRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String.pipe(T.Label()),
    cwd: S.optional(S.String),
    env: S.optional(CreateSessionRequestEnvMap),
  }).pipe(
    T.Http({ method: "POST", uri: "/v1/sandbox/{id}/session", code: 200 }),
  ),
).annotate({
  identifier: "CreateSessionRequest",
}) as any as S.Schema<CreateSessionRequest>;

export interface CreateSessionResponse {
  /** Session ID to pass via `Session-Id` header. */
  id: string;
}
export const CreateSessionResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
  }),
).annotate({
  identifier: "CreateSessionResponse",
}) as any as S.Schema<CreateSessionResponse>;

export interface CreateTunnelRequest {
  /** Sandbox instance name. */
  id: string;
  /** Container port to tunnel. Port 3000 is reserved. */
  port: number;
  /** Subdomain prefix for a named tunnel, such as `app`. Do not pass a full hostname. Omit to create or reuse an ephemeral tunnel. */
  name?: string;
}
export const CreateTunnelRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String.pipe(T.Label()),
    port: S.Number.pipe(T.Label()),
    name: S.optional(S.String),
  }).pipe(
    T.Http({
      method: "POST",
      uri: "/v1/sandbox/{id}/tunnel/{port}",
      code: 200,
    }),
  ),
).annotate({
  identifier: "CreateTunnelRequest",
}) as any as S.Schema<CreateTunnelRequest>;

export interface Tunnel {
  id: string;
  /** Container port served by the tunnel. */
  port: number;
  url: string;
  hostname: string;
  createdAt: string;
  /** Present for named tunnels only. */
  name?: string;
}
export const Tunnel = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String,
    port: S.Number,
    url: S.String,
    hostname: S.String,
    createdAt: S.String,
    name: S.optional(S.String),
  }),
).annotate({ identifier: "Tunnel" }) as any as S.Schema<Tunnel>;

export interface DeleteSandboxRequest {
  /** Sandbox instance name. */
  id: string;
}
export const DeleteSandboxRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String.pipe(T.Label()),
  }).pipe(T.Http({ method: "DELETE", uri: "/v1/sandbox/{id}", code: 200 })),
).annotate({
  identifier: "DeleteSandboxRequest",
}) as any as S.Schema<DeleteSandboxRequest>;

export interface DeleteSandboxResponse {}
export const DeleteSandboxResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "DeleteSandboxResponse",
}) as any as S.Schema<DeleteSandboxResponse>;

export interface DeleteSessionRequest {
  /** Sandbox instance name. */
  id: string;
  /** Session ID to delete. */
  sid: string;
}
export const DeleteSessionRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String.pipe(T.Label()),
    sid: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "DELETE",
      uri: "/v1/sandbox/{id}/session/{sid}",
      code: 200,
    }),
  ),
).annotate({
  identifier: "DeleteSessionRequest",
}) as any as S.Schema<DeleteSessionRequest>;

export interface DeleteSessionResponse {
  /** `true` if the session was deleted. */
  success: boolean;
  /** ID of the deleted session. */
  sessionId: string;
}
export const DeleteSessionResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    success: S.Boolean,
    sessionId: S.String,
  }),
).annotate({
  identifier: "DeleteSessionResponse",
}) as any as S.Schema<DeleteSessionResponse>;

export interface DeleteTunnelRequest {
  /** Sandbox instance name. */
  id: string;
  /** Container port whose tunnel should be deleted. Port 3000 is reserved. */
  port: number;
}
export const DeleteTunnelRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String.pipe(T.Label()),
    port: S.Number.pipe(T.Label()),
  }).pipe(
    T.Http({
      method: "DELETE",
      uri: "/v1/sandbox/{id}/tunnel/{port}",
      code: 200,
    }),
  ),
).annotate({
  identifier: "DeleteTunnelRequest",
}) as any as S.Schema<DeleteTunnelRequest>;

export interface DeleteTunnelResponse {}
export const DeleteTunnelResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}),
).annotate({
  identifier: "DeleteTunnelResponse",
}) as any as S.Schema<DeleteTunnelResponse>;

export interface GetOpenApiSchemaRequest {}
export const GetOpenApiSchemaRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(
    T.Http({ method: "GET", uri: "/v1/openapi.json", code: 200 }),
  ),
).annotate({
  identifier: "GetOpenApiSchemaRequest",
}) as any as S.Schema<GetOpenApiSchemaRequest>;

export type GetOpenApiSchemaResponse = unknown;
export const GetOpenApiSchemaResponse = /*@__PURE__*/ S.suspend(() =>
  S.Unknown.pipe(T.RawResponseRoot()),
).annotate({
  identifier: "GetOpenApiSchemaResponse",
}) as any as S.Schema<GetOpenApiSchemaResponse>;

export interface GetPoolStatsRequest {}
export const GetPoolStatsRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(
    T.Http({ method: "GET", uri: "/v1/pool/stats", code: 200 }),
  ),
).annotate({
  identifier: "GetPoolStatsRequest",
}) as any as S.Schema<GetPoolStatsRequest>;

export interface PoolStatsConfig {
  warmTarget?: number;
  refreshInterval?: number;
}
export const PoolStatsConfig = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    warmTarget: S.optional(S.Number),
    refreshInterval: S.optional(S.Number),
  }),
).annotate({
  identifier: "PoolStatsConfig",
}) as any as S.Schema<PoolStatsConfig>;

export interface PoolStats {
  /** Number of warm (unassigned) containers ready for use. */
  warm: number;
  /** Number of containers assigned to sandbox IDs. */
  assigned: number;
  /** Total containers tracked by the pool. */
  total: number;
  config: PoolStatsConfig;
  /** Inferred max_instances limit, or null if not yet known. */
  maxInstances: number | null;
}
export const PoolStats = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    warm: S.Number,
    assigned: S.Number,
    total: S.Number,
    config: PoolStatsConfig,
    maxInstances: S.NullOr(S.Number),
  }),
).annotate({ identifier: "PoolStats" }) as any as S.Schema<PoolStats>;

export interface IsSandboxRunningRequest {
  /** Sandbox instance name. */
  id: string;
}
export const IsSandboxRunningRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String.pipe(T.Label()),
  }).pipe(
    T.Http({ method: "GET", uri: "/v1/sandbox/{id}/running", code: 200 }),
  ),
).annotate({
  identifier: "IsSandboxRunningRequest",
}) as any as S.Schema<IsSandboxRunningRequest>;

export interface RunningResponse {
  /** `true` if the sandbox container is alive and responding. */
  running: boolean;
}
export const RunningResponse = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    running: S.Boolean,
  }),
).annotate({
  identifier: "RunningResponse",
}) as any as S.Schema<RunningResponse>;

export interface MountBucketCredentials {
  /** S3-compatible access key ID. */
  accessKeyId: string;
  /** S3-compatible secret access key. */
  secretAccessKey: string;
}
export const MountBucketCredentials = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    accessKeyId: S.String,
    secretAccessKey: S.String,
  }),
).annotate({
  identifier: "MountBucketCredentials",
}) as any as S.Schema<MountBucketCredentials>;

/** Advanced: Override or extend s3fs mount options for both remote mounts and R2 binding mounts. */
export type MountBucketRequestOptionsS3fsOptionsList = Array<string>;
export const MountBucketRequestOptionsS3fsOptionsList = /*@__PURE__*/ S.Array(
  S.String,
) as any as S.Schema<MountBucketRequestOptionsS3fsOptionsList>;

export interface MountBucketRequestOptions {
  /** S3-compatible endpoint URL for remote mounts. Mutually exclusive with top-level `binding`. */
  endpoint?: string;
  /** Mount filesystem as read-only (default: false). */
  readOnly?: boolean;
  /** Optional prefix/subdirectory within the bucket to mount. Must start with `/`. Trailing slashes are stripped automatically. */
  prefix?: string;
  /** Explicit credentials. When omitted, the SDK auto-detects from Worker secrets (R2_ACCESS_KEY_ID / R2_SECRET_ACCESS_KEY or AWS equivalents). */
  credentials?: MountBucketCredentials;
  /** Keep credentials in the Durable Object and sign intercepted s3fs requests from the Worker. Credentials may be explicit or auto-detected from Worker secrets. */
  credentialProxy?: boolean;
  /** Advanced: Override or extend s3fs mount options for both remote mounts and R2 binding mounts. */
  s3fsOptions?: MountBucketRequestOptionsS3fsOptionsList;
}
export const MountBucketRequestOptions = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    endpoint: S.optional(S.String),
    readOnly: S.optional(S.Boolean),
    prefix: S.optional(S.String),
    credentials: S.optional(MountBucketCredentials),
    credentialProxy: S.optional(S.Boolean),
    s3fsOptions: S.optional(MountBucketRequestOptionsS3fsOptionsList),
  }),
).annotate({
  identifier: "MountBucketRequestOptions",
}) as any as S.Schema<MountBucketRequestOptions>;

export interface MountBucketRequest {
  /** Sandbox instance name. */
  id: string;
  /** Remote bucket name for endpoint-based S3-compatible mounts. */
  bucket?: string;
  /** Worker R2 binding name for credential-less R2 binding mounts. Mutually exclusive with `options.endpoint`. */
  binding?: string;
  /** Absolute path in the container to mount at. */
  mountPath: string;
  options: MountBucketRequestOptions;
}
export const MountBucketRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String.pipe(T.Label()),
    bucket: S.optional(S.String),
    binding: S.optional(S.String),
    mountPath: S.String,
    options: MountBucketRequestOptions,
  }).pipe(T.Http({ method: "POST", uri: "/v1/sandbox/{id}/mount", code: 200 })),
).annotate({
  identifier: "MountBucketRequest",
}) as any as S.Schema<MountBucketRequest>;

export interface PrimePoolRequest {}
export const PrimePoolRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(
    T.Http({ method: "POST", uri: "/v1/pool/prime", code: 200 }),
  ),
).annotate({
  identifier: "PrimePoolRequest",
}) as any as S.Schema<PrimePoolRequest>;

export interface ShutdownPrewarmedRequest {}
export const ShutdownPrewarmedRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({}).pipe(
    T.Http({ method: "POST", uri: "/v1/pool/shutdown-prewarmed", code: 200 }),
  ),
).annotate({
  identifier: "ShutdownPrewarmedRequest",
}) as any as S.Schema<ShutdownPrewarmedRequest>;

export interface UnmountBucketRequest {
  /** Sandbox instance name. */
  id: string;
  /** Absolute path where the bucket is currently mounted. */
  mountPath: string;
}
export const UnmountBucketRequest = /*@__PURE__*/ S.suspend(() =>
  S.Struct({
    id: S.String.pipe(T.Label()),
    mountPath: S.String,
  }).pipe(
    T.Http({ method: "POST", uri: "/v1/sandbox/{id}/unmount", code: 200 }),
  ),
).annotate({
  identifier: "UnmountBucketRequest",
}) as any as S.Schema<UnmountBucketRequest>;

export type CheckHealthError = SandboxBridgeOpError;
/** Worker health check Simple liveness probe. Not protected by authentication. */
export const checkHealth: API.OperationMethod<
  CheckHealthRequest,
  OkResponse,
  CheckHealthError,
  SandboxBridgeOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CheckHealthRequest,
  output: OkResponse,
  errors: [UnknownCloudflareSandboxError],
  protocol: SandboxBridgeProtocol,
  retry: Retry.Retry,
}));

export type CreateSandboxError = SandboxBridgeOpError;
/** Create a new sandbox session Generates a new unique sandbox ID. Use this ID with all `/v1/sandbox/{id}/*` routes. */
export const createSandbox: API.OperationMethod<
  CreateSandboxRequest,
  CreateSandboxResponse,
  CreateSandboxError,
  SandboxBridgeOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateSandboxRequest,
  output: CreateSandboxResponse,
  errors: [UnknownCloudflareSandboxError],
  protocol: SandboxBridgeProtocol,
  retry: Retry.Retry,
}));

export type CreateSessionError = SandboxBridgeOpError;
/** Create an execution session Sessions isolate working directory and environment variables across commands. The returned session ID is used with the `Session-Id` header on exec, file, and PTY endpoints. */
export const createSession: API.OperationMethod<
  CreateSessionRequest,
  CreateSessionResponse,
  CreateSessionError,
  SandboxBridgeOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateSessionRequest,
  output: CreateSessionResponse,
  errors: [UnknownCloudflareSandboxError],
  protocol: SandboxBridgeProtocol,
  retry: Retry.Retry,
}));

export type CreateTunnelError = BadRequest | SandboxBridgeOpError;
/** Create or reuse a tunnel for a sandbox port Returns an existing tunnel for the port when one is already recorded, or provisions one when needed. The service must already be listening inside the sandbox. Omit `name` for an ephemeral `*.trycloudflare.com` tunnel, or pass `name` to choose the subdomain prefix for a named tunnel. Use a value such as `app`, not a full hostname. */
export const createTunnel: API.OperationMethod<
  CreateTunnelRequest,
  Tunnel,
  CreateTunnelError,
  SandboxBridgeOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: CreateTunnelRequest,
  output: Tunnel,
  errors: [BadRequest, UnknownCloudflareSandboxError],
  protocol: SandboxBridgeProtocol,
  retry: Retry.Retry,
}));

export type DeleteSandboxError = SandboxBridgeOpError;
/** Destroy a sandbox instance (best-effort) Calls destroy() on the sandbox Durable Object to release container resources. Best-effort: unknown sandbox IDs return 204 without allocating a container. */
export const deleteSandbox: API.OperationMethod<
  DeleteSandboxRequest,
  DeleteSandboxResponse,
  DeleteSandboxError,
  SandboxBridgeOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteSandboxRequest,
  output: DeleteSandboxResponse,
  errors: [UnknownCloudflareSandboxError],
  protocol: SandboxBridgeProtocol,
  retry: Retry.Retry,
}));

export type DeleteSessionError = SandboxBridgeOpError;
/** Delete an execution session Removes a named session. The default session cannot be deleted. */
export const deleteSession: API.OperationMethod<
  DeleteSessionRequest,
  DeleteSessionResponse,
  DeleteSessionError,
  SandboxBridgeOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteSessionRequest,
  output: DeleteSessionResponse,
  errors: [UnknownCloudflareSandboxError],
  protocol: SandboxBridgeProtocol,
  retry: Retry.Retry,
}));

export type DeleteTunnelError = BadRequest | SandboxBridgeOpError;
/** Delete the tunnel for a sandbox port Stops the tunnel process for the port and removes any named-tunnel Cloudflare resources tracked by the sandbox. */
export const deleteTunnel: API.OperationMethod<
  DeleteTunnelRequest,
  DeleteTunnelResponse,
  DeleteTunnelError,
  SandboxBridgeOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: DeleteTunnelRequest,
  output: DeleteTunnelResponse,
  errors: [BadRequest, UnknownCloudflareSandboxError],
  protocol: SandboxBridgeProtocol,
  retry: Retry.Retry,
}));

export type GetOpenApiSchemaError = SandboxBridgeOpError;
/** OpenAPI schema Returns this OpenAPI 3.1 schema document. */
export const getOpenApiSchema: API.OperationMethod<
  GetOpenApiSchemaRequest,
  GetOpenApiSchemaResponse,
  GetOpenApiSchemaError,
  SandboxBridgeOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetOpenApiSchemaRequest,
  output: GetOpenApiSchemaResponse,
  errors: [UnknownCloudflareSandboxError],
  protocol: SandboxBridgeProtocol,
  retry: Retry.Retry,
}));

export type GetPoolStatsError = SandboxBridgeOpError;
/** Pool statistics Returns current warm pool statistics including warm/assigned counts and configuration. */
export const getPoolStats: API.OperationMethod<
  GetPoolStatsRequest,
  PoolStats,
  GetPoolStatsError,
  SandboxBridgeOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: GetPoolStatsRequest,
  output: PoolStats,
  errors: [UnknownCloudflareSandboxError],
  protocol: SandboxBridgeProtocol,
  retry: Retry.Retry,
}));

export type IsSandboxRunningError = SandboxBridgeOpError;
/** Check whether the sandbox container is alive Executes a no-op command inside the sandbox. Always returns HTTP 200; inspect the `running` field. */
export const isSandboxRunning: API.OperationMethod<
  IsSandboxRunningRequest,
  RunningResponse,
  IsSandboxRunningError,
  SandboxBridgeOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: IsSandboxRunningRequest,
  output: RunningResponse,
  errors: [UnknownCloudflareSandboxError],
  protocol: SandboxBridgeProtocol,
  retry: Retry.Retry,
}));

export type MountBucketError = BadRequest | SandboxBridgeOpError;
/** Mount an S3-compatible bucket into the container Mounts an S3-compatible bucket (R2, S3, GCS, etc.) as a local directory via s3fs-FUSE. Credentials are optional — the SDK auto-detects from Worker secrets when omitted. */
export const mountBucket: API.OperationMethod<
  MountBucketRequest,
  OkResponse,
  MountBucketError,
  SandboxBridgeOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: MountBucketRequest,
  output: OkResponse,
  errors: [BadRequest, UnknownCloudflareSandboxError],
  protocol: SandboxBridgeProtocol,
  retry: Retry.Retry,
}));

export type PrimePoolError = SandboxBridgeOpError;
/** Prime the warm pool Pushes the current pool configuration and starts the alarm loop. Called automatically by the cron trigger; can also be called manually after deploy. */
export const primePool: API.OperationMethod<
  PrimePoolRequest,
  OkResponse,
  PrimePoolError,
  SandboxBridgeOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: PrimePoolRequest,
  output: OkResponse,
  errors: [UnknownCloudflareSandboxError],
  protocol: SandboxBridgeProtocol,
  retry: Retry.Retry,
}));

export type ShutdownPrewarmedError = SandboxBridgeOpError;
/** Shutdown pre-warmed containers Stops all idle (unassigned) warm containers. Does not affect containers assigned to sandbox sessions. */
export const shutdownPrewarmed: API.OperationMethod<
  ShutdownPrewarmedRequest,
  OkResponse,
  ShutdownPrewarmedError,
  SandboxBridgeOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: ShutdownPrewarmedRequest,
  output: OkResponse,
  errors: [UnknownCloudflareSandboxError],
  protocol: SandboxBridgeProtocol,
  retry: Retry.Retry,
}));

export type UnmountBucketError = BadRequest | SandboxBridgeOpError;
/** Unmount a previously mounted bucket Unmounts a bucket filesystem that was previously mounted via `/v1/sandbox/{id}/mount`. */
export const unmountBucket: API.OperationMethod<
  UnmountBucketRequest,
  OkResponse,
  UnmountBucketError,
  SandboxBridgeOpContext
> = /*@__PURE__*/ API.make(() => ({
  input: UnmountBucketRequest,
  output: OkResponse,
  errors: [BadRequest, UnknownCloudflareSandboxError],
  protocol: SandboxBridgeProtocol,
  retry: Retry.Retry,
}));
