/**
 * @rikalabs/distilled-e2b — E2B SDK for Effect.
 *
 * `./services` is generated by `scripts/generate.ts` from the Smithy models in
 * `.generated-specs` (written by `scripts/convert.ts` from E2B's control-plane
 * OpenAPI document, the envd OpenAPI document, and the envd process/filesystem
 * protobuf services). Everything else in this folder is hand-written.
 *
 * Two planes, one package: the control plane (`E2BProtocol` + `Credentials`,
 * `api.<domain>`, `X-API-Key`) and per-sandbox envd (`E2BEnvdProtocol` +
 * `EnvdConnection`, Connect-RPC process/filesystem + REST file/env endpoints,
 * `X-Access-Token`). `Envd` carries the envd facade — `runCommand`,
 * `startProcess`, `sendInput`, watchers, and the `connectionLayer` that binds
 * a call to a sandbox.
 */
export * from "./credentials.ts";
export * from "./errors.ts";
export * as T from "./traits.ts";
export {
  E2BProtocol,
  E2BEnvdProtocol,
  type E2BOpError,
  type E2BOpContext,
  type E2BEnvdOpError,
  type E2BEnvdOpContext,
} from "./protocol.ts";
export * as Envd from "./envd.ts";
export * as Retry from "./retry.ts";
export * as Services from "./services/index.ts";
export { E2BHttpClient } from "./http.ts";
